### ISSUE TITLE
Electric turrets cause power supply problems

### ISSUE THREAD

**Issue by Alex-1248** [Deadlock989/IndustrialRevolution#104]
**Describe the bug**
Laser turrets and electric arc turrets cause a short-term disruption of the power supply of other buildings in the same power grid at the time of construction and during firing. A large number of generators and batteries cannot prevent this. Apparently, the internal batteries of the turrets do not have a rate limiter for consumption from the power grid.

**Factorio version, IR version**
1.1.70, 2.3.2

**Comment by Deadlock989** [comment]
This is fixed for 3.0.0.
