### ISSUE TITLE
Some Typos?

### ISSUE THREAD

**Issue by Fuzzician** [Deadlock989/IndustrialRevolution#105]
Nickel and Chrome plates are called "plating" in the game.  That is, the entity is "chrome plating", rather than chrome plate.
Only saw this on chrome, nickel, and the reinforced versions of those plates.

**Comment by Deadlock989** [comment]
It was deliberate but it wasn't necessarily a good choice. Most of the chrome plated components were previously called "chromed X". "Chromed plate" is OK but when I introduced nickel plating I wobbled about what to call the plates, "nickelled plate" just looks wrong, maybe it's fine, I don't know. "Nickel-plated rivets" works but "Nickel-plated plate" is bad.

**Comment by Deadlock989** [comment]
Fixed this brain freeze by calling all chrome electroplating products "chromed X" and all nickel electroplating products "nickel-coated X".
