### ISSUE TITLE
Sandbox causes unrecoverable error

### ISSUE THREAD

**Issue by Fuzzician** [Deadlock989/IndustrialRevolution#106]
Trying to start a Sandbox game with IR3 gives this error: 

The mod Industrial Revolution 3 (3.0.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event IndustrialRevolution3::on_player_created (ID 26)
...dustrialRevolution3__/code/control/control-transmats.lua:202: attempt to index local 'entity' (a nil value)
stack traceback:
	...dustrialRevolution3__/code/control/control-transmats.lua:202: in function <...dustrialRevolution3__/code/control/control-transmats.lua:201>
	(...tail calls...)
	__IndustrialRevolution3__/code/control/control-events.lua:122: in function <__IndustrialRevolution3__/code/control/control-events.lua:116>

**Comment by Deadlock989** [comment]
This is fixed for the next version.

Can you report IR3 beta issues in the IR3-beta issues area and not here in the public area - this will help me keep track of things. Thanks.
