### ISSUE TITLE
Rocket fuel recipe missing crafting machine tint

### ISSUE THREAD

**Issue by Bilka2** [Deadlock989/IndustrialRevolution#107]
**Describe the bug**
The rocket fuel recipe is made in the chemical plant and does not have a crafting machine tint set, resulting in white smoke/liquid animation for the chem plant. 
![Screenshot_20221217_163647](https://user-images.githubusercontent.com/27060268/208249558-39788dce-7c5e-4158-8a33-d861a4653dcd.png)

**Factorio version, IR version**
Factorio 1.1.74
IR 2.3.2

**Comment by Deadlock989** [comment]
This and a couple of similar cases have been addressed for 3.0.0.
