### ISSUE TITLE
Industrial Revolution mod incompatibility with Squeak Trough 

### ISSUE THREAD

**Issue by 17SchallerJ** [Deadlock989/IndustrialRevolution#110]
"Industrial Revolution 3" is incompatible with the mod "Squeak Through"
Steps to reproduce:
Load Industrial revolution 3 and Squeak Through together.
![image](https://user-images.githubusercontent.com/33696824/209442559-6d835c22-1193-48fa-9012-a52e845a21c2.png)

Factorio version: "Base Mod 1.1.74"
IR version: "Industrial Revolution 3 3.0.1"

Other mods installed: 
Only "Squeak Through 1.8.2"

**Comment by Deadlock989** [comment]
Not surprised, that mod is a menace.
