### ISSUE TITLE
Crash at start of game when leaving teleporter too quickly

### ISSUE THREAD

**Issue by ymgve** [Deadlock989/IndustrialRevolution#111]
If you leave the teleporter pad at the start of the game before the alert sound plays, the mod will crash
 
Factorio 1.1.74, IR 3.0.1

![427520_20221225020218_1](https://user-images.githubusercontent.com/15271733/209454368-2d289351-9be9-497c-b761-afb86f24cc1f.png)

**Comment by Deadlock989** [comment]
Thanks, this is fixed in the next version.
