### ISSUE TITLE
Steam Turbine - Recipe Mistake?

### ISSUE THREAD

**Issue by Fuzzician** [Deadlock989/IndustrialRevolution#12]
The recipe lists a Revolutionary Computer, which makes no sense, given that it also requires a Stainless Steel Frame, which itself already has a Revolutionary Computer.  Given the pattern of other machines only needing the Frame, and never a separate computer in addition, I feel confident in stating that this is a typo, rather than intended.

**Comment by Deadlock989** [comment]
It looks like turbines were missed when the main electronics components of machines were mostly moved into the frame. Also, removing it would still leave 5 ingredients when machines that size are supposed to have a maximum of 4.

**Comment by Deadlock989** [comment]
Fixed by removing the computer AND the frame, boosting the other components to fill the shortfall. There is enough complexity with the invar and the chromed parts.
