### ISSUE TITLE
grandfathered in faq line not yet removed

### ISSUE THREAD

**Issue by Quezler** [Deadlock989/IndustrialRevolution#120]
**Describe the bug**

"This will be closed at some future date." can be removed from the [mod portal faq](https://mods.factorio.com/mod/IndustrialRevolution3/faq) since mod portal discussions are closed:

> Where can I report bugs or other issues?
> You can raise issues on IR's [Github issues tracker](https://github.com/Deadlock989/IndustrialRevolution/issues). This will be closed at some future date.

**Factorio version, IR version**
¬

**Other mods installed**
¬

**Comment by Deadlock989** [comment]
"This" means this issues tracker.

**Comment by Quezler** [comment]
i guess i did not expect it to mean the github issues would ever close, usually mod makers refer to it instead of discussions, maybe ", Which" would have been a clearer choice in favor of ". This", so others don't get confused too 🤔
