### ISSUE TITLE
I can't connect to the server in multiplayer

### ISSUE THREAD

**Issue by flameSla** [Deadlock989/IndustrialRevolution#125]
` 110.748 Error ClientMultiplayerManager.cpp:1074: mod-IndustrialRevolution3 was registered for the following events when the map was saved but has not re-registered them as a result of loading: on_tick (ID 0)
 110.748 Error ClientMultiplayerManager.cpp:99: MultiplayerManager failed: "" + multiplayer.script-event-mismatch + "
" + "
mod-IndustrialRevolution3"`

**Comment by Deadlock989** [comment]
What version of the mod?

**Comment by flameSla** [comment]
3.0.1

**Comment by Deadlock989** [comment]
This was fixed in 3.0.2, see changelog.

Duplicate of #116
