### ISSUE TITLE
Forestries spawns new trees grid-aligned

### ISSUE THREAD

**Issue by Heinarc** [Deadlock989/IndustrialRevolution#129]
First, many thanks for this great mod !

Not sure if it's a mere oversight, a limitation or a deliberate design choice, but forestries spawn new trees grid-aligned, which ends up looking a bit strange on the minimap.
It would also be a nice touch to consider tree varieties of the neighbouring chunks when spawning a new tree (and not only the current chunk), which would open up plenty of possibilities with mods like Alien Biomes.

**Factorio version, IR version**
Factorio v1.1.74, IR3 v3.01

**Other mods installed**
Alien Biomes

**Comment by Deadlock989** [comment]
This was a deliberate choice - it greatly optimises the random selection of positions for new trees without having things bunch up around obstacles, and also matches the trees made with tree beds which also work out better if grid-aligned.

Think of it as being like an orchard.

![image](https://user-images.githubusercontent.com/3128845/209667861-4394757e-afbd-4719-a680-e8ed94ccdfea.png)

Keeping things with a chunk was also an optimisation choice - most of the design choices for forestries are based on keeping UPS hits nicely spread out and low impact, as well as the fact that pollution is chunk-based.
