### ISSUE TITLE
Midgame items are creating/consuming pollution at the start of the game.

### ISSUE THREAD

**Issue by arand** [Deadlock989/IndustrialRevolution#134]
I'm over 5h in IR3 game and just discovered that at the beginning of the game, there were midgame items - advanced and electric mining drills, gas vent, arc furnace, oil refinery, electric furnace, air purifier and air compressor creatring/consumig pollution.

IR3 v. 3.0.3

Some other QoL mods - FNEI 0.4.1, rate calculator 2.4.6, even distribution 1.0.10

![image](https://user-images.githubusercontent.com/183498/209821008-2b72c9a5-02b9-4257-b680-e6bff87a9873.png)

**Comment by Deadlock989** [comment]
These are probably entities in the Manifesto "simulation" windows.

Not sure if anything can be done but I will take a look.
