### ISSUE TITLE
Multiplayer Desync Report

### ISSUE THREAD

**Issue by Blu3wolf** [Deadlock989/IndustrialRevolution#14]
Factorio 1.1.21 (build 58049, linux64)

Industrial Revolution 2.1.1
Informatron 0.2.1
Larger Lamps 1.5.0
Todo List 19.1.0

During multiplayer, several desyncs were observed. Reconnecting was possible, although unreliable. 

The window said its either a bug in a mod, or a bug in the base game, so I guess Im not clear if this is in fact an IR issue at all. I thought you might be interested in the report, if it is in fact a bug in IR. 

Desync reports:
https://blu3wolf.com/Factorio/IR-Desync/desync-report-2021-02-14_16-52-55.zip
https://blu3wolf.com/Factorio/IR-Desync/desync-report-2021-02-14_16-54-48.zip
https://blu3wolf.com/Factorio/IR-Desync/desync-report-2021-02-14_17-11-23.zip

**Comment by Deadlock989** [comment]
Hi, I ran a diff on the heuristics from two of these desync reports. The only differences are in random single characters. I wouldn't rule out memory corruption ("bitflip"). 

However there is no documentation or guidance from Wube on reading and diagnosing desync reports so I can't say that for sure, and this is the limit of what I can do.

I suggest trying running some memory integrity tests on both the host and clients. If they come back negative, report the desync to the "Desyncs with mods" forum for the vanilla game and maybe one of the devs will be able to look at it. If what they find is conclusively linked with IR2 then let me know.

**Comment by Blu3wolf** [comment]
Based on the description of that subforum, Im not sure how much attention it will get: 

> Desyncs in modded game will be ignored most of the time, until it is clearly proven that the desync is not caused by scripting. 

Ill report it anyway. Machine gets memtested pretty frequently, but I guess it could also be the host, so we'll have a look at ruling that out. I guess Ill advise if we continue to get the issue with IR2, and cant reproduce without IR2.

**Comment by Blu3wolf** [comment]
Doing some [debugging with heavy mode](https://wiki.factorio.com/Desynchronization#Using_heavy_mode_command), it seems like this might be related to Informatron rather than Industrial Revolution. Heavy Mode reported differences between save and load when opening the Informatron GUI. 

Ill advise the Informatron dev, and I guess in the interim Ill remove the mod and see if I can reproduce with just Industrial Revolution installed. 

Thanks for the tip pointing in the direction of the forum, that was where I found the advice on troubleshooting desyncs.

**Comment by Deadlock989** [comment]
Duplicate of #15

**Comment by Blu3wolf** [comment]
Ill wait for the fix then. If the two are related, I guess I dont need to inform the Informatron dev. 

Thanks for the mod! I very much enjoyed the first play through of it some years back. Looking forwards to sharing with some friends the magic.

**Comment by Deadlock989** [comment]
No, the issue was on IR2's side. The fixed version is released now.
