### ISSUE TITLE
"Petro Generator - Pipe - Petro Generator" build does not let fuel flow through

### ISSUE THREAD

**Issue by Redman3global** [Deadlock989/IndustrialRevolution#140]
![20221231000620_1](https://user-images.githubusercontent.com/38024517/210076221-9900999a-edfd-4ac5-933c-e2e425b416c3.jpg)

Here's screenshot pretty much describing the problem, the build on the bottom runs just fine, while the one the top does not let fuel flow from left generator to right generator

Factorio Version: 1.1.74
IR3 Version: 3.0.4

**Comment by Deadlock989** [comment]
This was due to a misconfigured fluid box on the petro generator entity, fixed for the next version.
