### ISSUE TITLE
Basic Items uncraftable when using GearGirl skin

### ISSUE THREAD

**Issue by DojoHx** [Deadlock989/IndustrialRevolution#141]
When using the Gear Girl skin many basic items become uncraftable because they are set to be made in "Deafault Character"
IR2 didn't have this issue.
Could the same compatibility be added in the future?  

![image](https://user-images.githubusercontent.com/121688432/210099188-de20283a-fb5b-44f6-bb32-1f38c12b008f.png)

**Comment by Deadlock989** [comment]
IR3 needs a separate crafting category for basic components so that small assemblers can be restricted to that category only. IR2 didn't have small assemblers.

I will investigate this later but my gut feeling is that this is something the skin mod or the skin manager mod should be handling.

**Comment by Deadlock989** [comment]
This is fixed for the next version. Gear Girl currently works fine on its own - it was MiniMaxiMe that was interfering.

Character crafting additions were postponed to data-final-fixes; all characters available at that time are checked and if they can craft with the default category, the IR3 categories are added. If other mods create new characters after that time then there is nothing IR3 can do.
