### ISSUE TITLE
Satellite launches only produces 100 cosmic analysis packs, but recipe mods reports 1000 packs

### ISSUE THREAD

**Issue by chi-feng** [Deadlock989/IndustrialRevolution#142]
**Describe the bug**

Really enjoying the mod so far. We finally launched our first rocket at 110hrs. 

However, launching a rocket with a satellite only produces 100 cosmic analysis packs. This makes infinite researches much costlier than anticipated. The recipe for cosmic analysis packs in Recipe Book reports 1000 packs:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/336681/210132991-bfb11a60-8c99-4428-81a2-db3e8b0148f1.png">

Maybe it is due to the stack size limit of 100 and only one inventory slot for rocket silo products? 

<img width="427" alt="image" src="https://user-images.githubusercontent.com/336681/210133112-8a95aa9f-0bbc-4be6-918a-951dc1771c9e.png">

**Factorio version, IR version**
1.1.74, 3.0.3

**Other mods installed**
n/a

**Comment by Deadlock989** [comment]
Ugh. This was due to a last minute change. Will be fixed later today.

**Comment by Deadlock989** [comment]
You can hotfix this for yourself in a single-player game (or for a private multiplayer game, if all players add exactly the same fix) by opening `code/data/components.lua`, going to line 1295-1297, which reads as follows:

```
	["analysis"] = { -- this component must exist
		type = "tool",
		order = "z",
```

Add the following lines so that it reads as follows:

```
	["analysis"] = { -- this component must exist
		type = "tool",
		order = "z",
		stack_size = 100,
		stack_size_exceptions = {
			hydrogen = 1000,
		},
```
