### ISSUE TITLE
Cannot connect steam pipe to system

### ISSUE THREAD

**Issue by JayOne9** [Deadlock989/IndustrialRevolution#144]
I am getting error "Cannot connect systems with different fluids" when trying to connect a steam pipe into a working pipe system.

**Comment by Deadlock989** [comment]
Filtered pipes (e.g. steam pipes) won't connect to any system that has any other fluid in it. This is a regular gameplay issue. If you're actually trying to make a bug report, please follow the template provided, and give me a way to reproduce the issue.

**Comment by JayOne9** [comment]
I understand that. Fluids have to be compatible but the issue here is that after loading the game, normal behavior where a new unconnected steam pipe should connect to an existing system containing steam is not working and throwing this error. Not sure how to replicate this issue. I will look into this further and see if I can get a stack trace for this behavior and create the bug report like you specified.
