### ISSUE TITLE
Crash with Dectorio

### ISSUE THREAD

**Issue by Porkchop13** [Deadlock989/IndustrialRevolution#146]
**Describe the bug**
If Dectorio is enabled alongside IR3 and the "Enable Waterfill" setting is unchecked, the game won't load due to a script error from IR3.

> 1.957 Error ModManager.cpp:1560: Failed to load mod "IndustrialRevolution3": ...volution3__/code/functions/functions-data-technology.lua:214: attempt to index local 'tech' (a nil value)
> stack traceback:
> 	...volution3__/code/functions/functions-data-technology.lua:214: in function 'disable_technology'
> 	...ustrialRevolution3__/code/mods/mods-data-final-fixes.lua:45: in main chunk
> 	[C]: in function 'require'
> 	__IndustrialRevolution3__/data-final-fixes.lua:15: in main chunk

**Factorio version, IR version**
Factorio version 1.1.74, IR3 version 3.0.5, Dectorio version 0.12.6

**Other mods installed**
None

**Comment by Deadlock989** [comment]
This should be fixed for 3.0.6.

Out of curiosity, how did you get into this state? Was Dectorio previously installed without IR3 and the Enable Waterfill option unchecked beforehand?
