### ISSUE TITLE
Air pipe can’t transport pressurized gasses other than compressed air

### ISSUE THREAD

**Issue by Cadams111** [Deadlock989/IndustrialRevolution#148]
**Describe the bug**
The iron “air pipe” can only transport compressed air and not other gasses, such as steam, sour gas, or cryogenic gasses. As it feels like an “upgraded steam pipe”, it would make sense for the iron version to be able to transport the same fluids and more. Is this a scripting limitation? Can pipes only have one “filter”? Also the “vanilla” iron pipe can, at the moment, transport compressed air even though CA has its own pipe. Also thank you so much for IR3! It’s really well done.
**Factorio version, IR version**
Base 1.1.74, IR 3.0.5

**Comment by Deadlock989** [comment]
Unfortunately this is a game engine limitation - pipes can't filter more than one fluid. This has been asked for time and time again by modders and I would be all over it in a heartbeat if it was ever introduced, but Wube believe it would have game performance consequences.

**Comment by Cadams111** [comment]
Ah. Sad

**Comment by Cadams111** [comment]
I haven’t seen any other miss filter pipes, I had assumed you scripted that yourself.
