### ISSUE TITLE
Cyclical dependency in tech tree

### ISSUE THREAD

**Issue by SevenChords** [Deadlock989/IndustrialRevolution#149]
this happens when i try and enable the mod.
i have all the required dependencies installed and enabled and none of the listed incompatibilities are enables (only got squeak through installed, disabled that, the error still persists)
i only have one mod that adds/changes belt related items, the aai loaders mod, which for one explicitly states it is compatible with ir2 and ir3 and when i disable that mod the same error with underground-belt, splitter, loader-pro-001 occurs, so it can't be that mod, and any other belt related mod neither adds belt related items nor changes belt related technologies/crafting recipes.

if you want i can provide a full modlist, but that one would be quite extensive, since i usually play with quite a few mods, most visual. qol or ltn related.

![image](https://user-images.githubusercontent.com/31819497/210647657-4f087ce0-72ab-40c3-84fe-be6e4883e4e9.png)

**Comment by Deadlock989** [comment]
What mod is loader-pro-001 from?

**Comment by SevenChords** [comment]
i have no other mod installed that adds loaders, how would i find out which mod adds that?

**Comment by Deadlock989** [comment]
Load your mod set without IR3, start a game, look at Logistics tech in the technology tree, mouseover the loader item unlocked by that tech. Make sure you have "Show mod owners in tooltips" in Settings > Interface turned on.

**Comment by SevenChords** [comment]
ok, found the culprit, the mod "advanced furnaces" has an option to add it's own loader, disabled the option, after that another issue with the same mod arose, seems like that mod has some trouble with ir3, lists ir >=2.0.0 as optional dependency, seems like that mod possibly needs an update, thanks for the help
