### ISSUE TITLE
Informatron shows no pages for Industrial Revolution

### ISSUE THREAD

**Issue by Blu3wolf** [Deadlock989/IndustrialRevolution#15]
Factorio 1.1.21 (build 58049, linux64)

Industrial Revolution 2.1.1
Informatron 0.2.1
Larger Lamps 1.5.0
Todo List 19.1.0

Expected behavior: mod pages for Informatron to be shown when playing the game

Observed behavior: Opening the Informatron window displays the Informatron page, with the following text:
Wait a sec, where's all my data? Looks like you don't have any mods installed that are adding any extra pages yet. Don't worry, I'm sure we'll find some soon.

**Comment by Deadlock989** [comment]
Can't reproduce. You should see something like this:

![image](https://user-images.githubusercontent.com/3128845/107877210-e2a35d80-6ec2-11eb-9dbb-663d7de1a299.png)

I'm going to assume this is the same desynced/corrupted game as your other report. Try starting a brand new game and check Informatron immediately.

**Comment by Blu3wolf** [comment]
To clarify, the above behavior is the same in all 5 different games Ive tried to start and check Informatron immediately. 
Ill reboot presently and advise the outcome.

**Comment by Deadlock989** [comment]
Was able to reproduce this. Investigating.

**Comment by Deadlock989** [comment]
There was indeed an issue with the way Informatron's remote calls were being initialised in brand new games - it was being done incorrectly in that case but more correctly in the case where a game (single or multiplayer) was loaded from a save. 

Fixed for next version which I will upload later today.

I guess it is possible that this was the cause of the desync issue you reported as well.
