### ISSUE TITLE
Stone brick visual display bug in crafting recipe

### ISSUE THREAD

**Issue by arwassa** [Deadlock989/IndustrialRevolution#153]
**Describe the bug**
Stone brick is displayed as red (expected orange) in crafting recipe when the player has enough stone in inventory to craft require amount of stone bricks. Stone brick is also displayed as a "raw resources" when the expected raw resource would be "Stone". This is only a visual bug as the player is still able to craft said item.
![bilde](https://user-images.githubusercontent.com/3681885/210867368-40bebc8b-188b-4e05-af17-796c20aeb238.png)

**Factorio version, IR version**
Factorio version: 1.1.74
IR version: 3.0.7

**Other mods installed**
 - FARL
 - fCPU
 - LTN
 - LTN Combinator Modernized
 - LTN Content Reader
 - Nixie Tubes
 - Even More Text Plates
 - Beacon Rebalance
 - Alien Biomes
 - AAI Loaders
 - AAI Containers & Warehouses
 - Larger Lamps

**Comment by Deadlock989** [comment]
This is being caused by stone bricks inheriting the "do_not_decompose" flag from other ingot-shaped items, which unlike bricks need that to be set because they can be made from several different recipes / amounts of resources.
