### ISSUE TITLE
Tier 3 belt not available in assembling machine in editor mode

### ISSUE THREAD

**Issue by angeld29** [Deadlock989/IndustrialRevolution#157]
**Describe the bug**
in edtior mode i cannot select reciept tier 3 belt( blue) in assembler machine
underground and splitter exist

**Factorio version, IR version**
1.1.74
3.0.7

**Other mods installed**
Waterfill

**Comment by Deadlock989** [comment]
Can't reproduce - works for me.

![image](https://user-images.githubusercontent.com/3128845/211190704-7ea98ec7-ce2c-4bac-a3fb-e1b3bca6f740.png)
