### ISSUE TITLE
Property "always show products" inconsistently set for artillery shell recipes

### ISSUE THREAD

**Issue by Bilka2** [Deadlock989/IndustrialRevolution#159]
**Describe the bug**
In the military tab, some recipes have always show products set to true, some have it set to false. Originally noticed this with artillery-shell (set to false) and atomic-artillery-shell (set to true). Magazines and cartridge have it all set to true despite some of them deriving from vanilla, so I assume always show products is meant be set to true on all recipes.

Other notes:
Capsules and cannon shells all have it set to false. IR2 has the same issue.
![Screenshot_20230108_133436](https://user-images.githubusercontent.com/27060268/211196278-70485d02-fccb-4afb-98d7-803034a6457c.png)

**Factorio version, IR version**
   0.396 Loading mod base 1.1.74 (data.lua)
   0.608 Loading mod IndustrialRevolution3 3.0.8 (data.lua)

**Comment by Deadlock989** [comment]
Magazines and cartridges are generated items so they consistently have the flags set, while atomic artillery shells are created as a one-off, and the rest are vanilla items, some of which have the maze of normal/expensive properties.

For the next version I have made this consistent for all ammo recipes but I don't want to spend time chasing this down for every single recipe in IR3 and vanilla, it's not that important.
