### ISSUE TITLE
Editing vanilla prototypes in data

### ISSUE THREAD

**Issue by jacobwatkinsgit** [Deadlock989/IndustrialRevolution#16]
Editing vanilla prototypes in data causes issues with mods that depend on vanilla definitions. In the case of Mobile Factory, the pipe-to-ground graphics were altered, which caused issues (hr_version in pipe_covers, and using layers in pictures).

Is there a possibility to move the vanilla prototype edits to data-updates without breaking compatibility (or some other solution)?

**Comment by Deadlock989** [comment]
To be honest, it's just not an issue for me if other mods depend on vanilla prototypes have particular properties. If I delay any changes I make to any vanilla prototype then it will break or cause extra work for other mods which _depend_ on being able to pick up those changes. If vanilla ever changes its prototypes to something unexpected, those mods will also break.

Overhaul mods break stuff, that's just the way it is.
