### ISSUE TITLE
Cosmic analysis tech missing overlay icon for unlocking analysis pack

### ISSUE THREAD

**Issue by Bilka2** [Deadlock989/IndustrialRevolution#160]
**Describe the bug**
The cosmic analysis technology is missing the overlay icon that signifies it unlocks an analysis pack. Furthermore, the tech icon and the description still reference the vanilla science pack.

![Screenshot_20230108_134227](https://user-images.githubusercontent.com/27060268/211196607-bf94c006-7388-46b6-98e3-25425b56b145.png)

**Factorio version, IR version**
   0.396 Loading mod base 1.1.74 (data.lua)
   0.608 Loading mod IndustrialRevolution3 3.0.8 (data.lua)

**Comment by Deadlock989** [comment]
3.0.9

![image](https://user-images.githubusercontent.com/3128845/211221151-ff712292-36b8-484c-9ac8-aa70a39820c0.png)
