### ISSUE TITLE
[Speculation] Post end game extension

### ISSUE THREAD

**Issue by Cadams111** [Deadlock989/IndustrialRevolution#168]
In vanilla, I’ve always felt like the post end game was unnecessary. You have one option: launch rockets for science. You can push the number of rockets per arbitrary time unit up, or do a couple of other things like artillery or spidertrons, and in IR you can get transmats. But even then, none of those are exclusively post end game. All that is restricted behind the rocket is infinite science. No new content.
Another thing: in vanilla, there aren’t any superfluous intermediates. Every intermediate has at least two uses, likely more. But in IR3, there are. The Solar Assembly and the Polished Telescope Mirror. While these make sense as satellite components, it doesn’t feel very “IR3” to have intermediates just for the sake of intermediates.
These, along with the fact that the IR3 satellite has been renamed to the Scientific Satellite, lead me to think that you’re planning, but have not yet implemented, another type of satellite.
There are also a couple of other “superfluous” intermediates, like the ruby rod and graphite electrode. My speculation is this:
Are you planning to make a military space satellite that fires a huge laser down to the ground, unlocked by the Cosmic analysis? Cause that’d be AWESOME. If not, it won’t change my feelings towards this mod, which are that it is extremely high quality, really fun to play, and nearly free of bugs. I want to be clear that there is no pressure here, just me taking a guess as to what you’re working on next. Thanks!

**Comment by Deadlock989** [comment]
"Plan" is a very strong word. Let's say "elbow room".

In general I try to avoid one-use intermediates but one of the differences between IR3 and IR2 is that I have tried very hard to avoid repeated-use assembling machine recipes which have more than 4 ingredients. The new satellite parts address that issue, and you are right that I have been thinking about different versions of satellites (IR1 did this, pretty unsuccessfully). There are still a few 5 ingredient recipes here and there but it is mostly stuff you don't churn out endlessly, like vehicles. The ruby rod is also on those lines - there wasn't space for both ruby and gold in the recipe I wanted to have.

**Comment by Cadams111** [comment]
That all makes a lot of sense, splitting recipes to cut unique ingredients. So, I won’t get my hopes up for a space laser anytime soon
