### ISSUE TITLE
[Feature request] Pallets could show their contents regardless of alt-mode?

### ISSUE THREAD

**Issue by Crowbarous** [Deadlock989/IndustrialRevolution#169]
I'm not familiar with the modding API so not sure if this is technically feasible, but this could be another distinctive feature of pallets. It would be useful in malls, and inserters putting things onto an empty plate which then remains empty looks a bit silly.

**Comment by Cadams111** [comment]
Would it show like a pile of the item, like klonans Mining Depots, or just the altmode icon?

**Comment by Deadlock989** [comment]
I like the idea but I don't see this happening.

There is no support in the game engine (that I'm aware of) for forcing alt-mode to be on for any particular entity. You can only do the opposite - force a particular prototype to ignore alt-mode. Alt-mode is either on or off.

That leaves you with a scripted solution which I think is most likely sledgehammer-to-crack-a-walnut territory and would entail some level of UPS cost.
