### ISSUE TITLE
Mining drills do not produce small% of diamond, sapphire and ruby.

### ISSUE THREAD

**Issue by dmitrybatyuk** [Deadlock989/IndustrialRevolution#17]
Played for several hours, expanded to full-electricity. Never saw any diamond, sapphire and ruby. Tried in sandbox (all tech unlocked), mined ~10k coal - no diamonds.

**Comment by Deadlock989** [comment]
Working as intended.

**Comment by Fuzzician** [comment]
I think that your starting patches never have those gems.  I only found those in secondary ore patches, further from starting position.
