### ISSUE TITLE
Stronger explosives 1 too early?

### ISSUE THREAD

**Issue by DrRaphello** [Deadlock989/IndustrialRevolution#172]
Hi,
This tech is available with explosives and steel packs and I can now research stronger explosives 1 tech which gives me bonus to grenades that I need to research Military 3 that requires chrome pack.
Stronger explosives 2 gives bonus to mines which I can also research but it's besides the point.

I'd propose to make StrExp1 to give bonus to mines only and lock StrExp2 (with double the grenade bonus) behind military 3.

BTW - great changes to an already great mod. Thanks for your efforts!

**Comment by Deadlock989** [comment]
Thanks for the report. I think these military chains were disordered a bit when the dedicated techs for science packs were removed. Unfortunately these chains are also limited by the appearance of the tech icons as well (e.g. featuring landmine or rocket icons - I don't have time to come up with new versions of them) so it's harder to change the sequence. 

- Move grenades to Military 2
- Remove brass gear from rocket launcher to move Rocketry back a couple of levels
- Projectile firing rate 3 should depend on Rocketry
