### ISSUE TITLE
Unable to make crushed iron ore as all iron ore is crushed into iron gravel

### ISSUE THREAD

**Issue by Exellin** [Deadlock989/IndustrialRevolution#175]
**Describe the bug**
Placing an iron ore into an electric crusher crushes the iron ore into iron gravel by default, with no know way to crush it into crushed iron ore instead.

![image](https://user-images.githubusercontent.com/5897420/213363253-82c7d699-3399-4bda-bac8-b8fdaa1ee96d.png)

**Factorio version, IR version**
Factorio version 1.1.74, IR version 3.0.8

**Comment by Deadlock989** [comment]
What mod is that item from?

**Comment by Exellin** [comment]
Oh it is from [Dectorio](https://mods.factorio.com/mod/Dectorio).  Sorry I had very minimal mods with this run and didn't think there would be a conflict.  Removing the mod and I can make crushed iron ore.  Thank you for the quick response.

**Comment by Deadlock989** [comment]
Dectorio is supported by IR3 so this is an oversight on my part. This will be fixed in the next version, probably by moving the Dectorio decorative gravels to mixer machine recipes.
