### ISSUE TITLE
Industrial Displays

### ISSUE THREAD

**Issue by billbo99** [Deadlock989/IndustrialRevolution#176]
Sorry Deadlock,  I do not know of any other method of communicating with you.

I know you no longer support "Industrial Display Plates",  but I would like to make some updates that I believe need the original graphics assets.

This is what I would like to do.
- Capture the rotate action being used on the display plate and change the background colour from black to grey to white.  Some icons like "coal" would stand out better with a grey or white background.
- I would also like to add green, gold & white bordered versions of the display plates.
- Lastly if possible I was thinking a 4x4 display plate might have some use for people's belt busses or un/loading stations.

By using the original assets I am hoping that I can separate out the layers;  border, shadow & background and create separate PNG files, then have factorio merge them together in-game.

If you're willing, you could DM me the file(s) via the factorio forum's.

**Comment by Deadlock989** [comment]
I have looked for the plate models but can't find them - it has been over 2 years since I last rendered them. Either they're backed up somewhere non-obvious or they got deleted. For a layered design you might be better off starting from scratch anyhow.

**Comment by billbo99** [comment]
thanks for looking
