### ISSUE TITLE
Feature Suggestion: Special Projects

### ISSUE THREAD

**Issue by RepairmanSki** [Deadlock989/IndustrialRevolution#177]
**Removal of Researched "Projects"**
I am wondering if it is possible to leverage _on_research_finished_ to call something like _hidden_from_player_crafting_ in order to clean up projects/packs that won't be needed again. I have found it to be moderately challenging to recall which projects have already been completed between sessions.

It would probably be undesirable (if not impossible) to have the the items completely removed on research being complete (unsetting assembler recipes and such) but perhaps there's some middle ground.

**Factorio version, IR version**
1.1.[x], 3.0.10

**Other mods installed**
N/A

**Comment by Deadlock989** [comment]
I did experiment with this sort of thing. You are correct in that trying to "un-research" packs on project completion was unreliable and created undesirable issues. 

Unfortunately `hidden_from_player_crafting` is a prototype property - it can't be set/unset at runtime. 

Now that the main mod is getting settled I will be looking at IR3SP again, but I have other things going on, so progress won't be swift.

**Comment by Cadams111** [comment]
I’ve seen other mods, see Nullius, that will hide a recipe from the “i” menu once you’ve crafted it enough times. Maybe take a look at that code?
