### ISSUE TITLE
Unbarrelling doesn't work via Barrelling machine

### ISSUE THREAD

**Issue by marcop82** [Deadlock989/IndustrialRevolution#179]
Using a barrelling machine to put fluids into barrels does work, but the unbarrelling recipe also refers to the barrelling machine to do this which doesn't work. It doesn't accept filled barrels and there's no machine I've found that does.

Factorio v1.1.76
IR3 3.0.10

Other mods:
Far Reach
FNEI (also no unbarrelling recipe found here)
Helmod
Miniloader
Waterfill

**Comment by Cadams111** [comment]
Have you tried pressing SHIFT+E over the pump? It has a toggle effect to switch to unbarreling I believe

**Comment by Deadlock989** [comment]
![image](https://user-images.githubusercontent.com/3128845/213886493-e743ef68-5e0a-45e5-a730-ce824c4458c2.png)

![image](https://user-images.githubusercontent.com/3128845/213886509-1b6c836c-0b8e-480c-af44-e6ea97d3c763.png)
