### ISSUE TITLE
Battery locomotive is missing

### ISSUE THREAD

**Issue by dmitrybatyuk** [Deadlock989/IndustrialRevolution#18]
No battery loco technology, no battery loco in sandbox (all tech enabled). Did you decide to remove it? If yes, please modify string in features list:

Trains, vehicles and personal equipment that can run on rechargeable batteries

**Comment by Deadlock989** [comment]
There is no "battery locomotive" any more.

Regular locomotives can also use rechargeable batteries so the description is correct.
