### ISSUE TITLE
[Bug?] Drills all producing the same Pollution per normalized mining speed

### ISSUE THREAD

**Issue by CvAmp** [Deadlock989/IndustrialRevolution#181]
It seems a little off that the Burner Mining Drill and Steam Mining Drill produce the same pollution 15/m @ 1.25 minerals/s as the Electric Drill running at 30/m @ 2.5 mineral/s. 

Would the electric drill either have a reduced pollution amount per resource as it draws it's energy from a burner/polluter that is not local i.e. direct burning at the drill. 

IR3 Version 3.0.10

**Comment by Deadlock989** [comment]
I don't have any problem with this personally - mining is inherently dirty. Electric drills also have efficiency modules available to them which directly reduces their emissions.
