### ISSUE TITLE
Starting screen doesn't look good on an ultrawide monitor

### ISSUE THREAD

**Issue by DrRaphello** [Deadlock989/IndustrialRevolution#184]
Loading screen on an ultrawide monitor does reveal too much (esp on left side):
![Clipboard01](https://user-images.githubusercontent.com/25507737/214289855-ea636592-bce2-4eae-81b0-f2858359badd.jpg)

**Comment by Deadlock989** [comment]
What is your UI scale set to for that image? (Settings > Interface > UI scale)

I will look at this the next time the main menu simulation gets updated but since [vanilla doesn't design for ultra-wide](https://forums.factorio.com/viewtopic.php?p=556152#p556152) and I don't have a wide monitor myself so it's low priority.

**Comment by DrRaphello** [comment]
I've got UI scale set to custom 100%. The menu look almost ok (one cheaty pipe still visible) when set to auto 125%. 
BTW you can check different ratios by running Factorio in a window and changing window size by dragging its borders / corners.

IR3 and Factorio in general runs very well on ultrawide - no problem there. Standard menu sims are fine too even if they lack interesting details outside of 16:9 box. I thought that with the level of polish you strive for the current menu is something you'd want to adjust :)

This is purely visual thing so take your sweet time with this one :)

**Comment by Deadlock989** [comment]
I have made some minor adjustments for the next version which fix the worst offenders, but I don't have time to produce something that will cover all possible situations.

**Comment by Deadlock989** [comment]
Next release (3.1.0) further improves the offscreen dirty laundry, using linked belts and long undergrounds.

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/3128845/d35dc18d-584c-46bd-9a89-b1e14405fbd9)
