### ISSUE TITLE
Small bronze pole seems (almost) strictly inferior to small wooden pole

### ISSUE THREAD

**Issue by Wiwiweb** [Deadlock989/IndustrialRevolution#185]
![image](https://user-images.githubusercontent.com/4723472/214705848-9d027736-6172-4b7d-9821-83b3d0911c08.png)
![image](https://user-images.githubusercontent.com/4723472/214705893-f75465d7-9540-4ad0-92e5-87cee5c6a94c.png)

**Wooden pole pros:**
Cheaper and simpler ingredients. Both need a wooden beam, but the wooden pole doesn't need any bronze.
100 hp vs 75 hp for the bronze pole.

**Bronze pole pros:**
Better damage resistances (barely a factor).
Looks way better (a shame to have to use the boring vanilla pole).

The iron pole has a reason to be picked since it doesn't need any wood.

**Comment by Deadlock989** [comment]
To be honest the aesthetic is 97% of the reason it exists, but I agree it doesn't make sense that the wooden pole has more hp.

**Comment by Cadams111** [comment]
Maybe having it be a super early game substation? Low wire reach but good coverage is something I’m always looking for in my builds…

**Comment by Deadlock989** [comment]
- Small wooden pole hp decreased from 100 to 50
- Small bronze pole hp remains at 75
- Small iron pole hp remains at 100
- Big wooden pole hp decreased from 225 to 200
- Steel pylon hp remains at 250
- Substation hp increased from 200 to 300
- Photonic cannon hp increased from 1500 to 1750

**Comment by Dimava** [comment]
I'm now trying to imagine how would feel poles that are weaker then a default pole
I guess I'll mod that for myself and write a review in a week or so
