### ISSUE TITLE
Separate forestry mod?

### ISSUE THREAD

**Issue by tburrows13** [Deadlock989/IndustrialRevolution#188]
Hello, just a quick request - feel free to ignore!

The forestry system in IR3 is particularly interesting and novel for factorio modding. I was wondering if you fancied releasing a standalone version of it so that other mods can use it if they need automatable wood, rather than depending on the much-more-boring https://mods.factorio.com/mod/bobgreenhouse or https://mods.factorio.com/mod/just-another-greenhouse.

Personally I'm developing a small overhaul/modpack thing, and this could fit quite well in it as a dependency. I'd be happy to make the mod from the various bits of IR3 if you like, for you to release under your account.

**Comment by Deadlock989** [comment]
Thanks for asking. Unfortunately I don't think this (two parallel code bases) is something I will be able to find time or motivation to support. I'm happy for you to adapt the code and credit me if you can use anything substantial (if you can even read my weird self-taught code) but I'm not happy about the forestry graphics being used in other mods.
