### ISSUE TITLE
Wrong fuels for Flamethrower

### ISSUE THREAD

**Issue by Cadams111** [Deadlock989/IndustrialRevolution#189]
**Describe the bug**
Petro generator uses Light, Petro, Ethanol, and Natural Gas. Flamethrower uses Heavy, Light, and Crude, of which only Light is a “burnable”. Is it possible to change flamer’s fuels to Light, Petro, and Ethanol? NG makes sense, that would just flare out, but having the “burnable fluids” all have a little fire mark and be burnable in the Generator, it doesn’t make sense to have the flamer throw non-burnable fluids. Just a little continuity error, mod’s great!

**Factorio version, IR version**
Base 1.1.76, IR 3.0.11

**Other mods installed**
None of consequence

**Comment by Deadlock989** [comment]
You are confusing "burnable" with "fuel". Generators are a precision high tech engine with hundreds of moving parts designed to efficiently capture the energy potential of exploding hydrocarbons. Flamethrower turrets are a big old spout that spews burning crap onto things. They are not directly comparable. Crude oil burns just fine: but you can't run your car on it.

**Comment by Cadams111** [comment]
Got it. That makes plenty of sense, but why can’t you throw Petroleum or Ethanol (maybe with a bigger damage bonus for the more processed Ethanol)? I’m having a bit of a petroleum problem honestly
