### ISSUE TITLE
High pressure project pack requires diamond

### ISSUE THREAD

**Issue by gnikivdlob** [Deadlock989/IndustrialRevolution#190]
High pressure project pack requires diamond to craft, but diamonds become available after project is researched. 
Do I miss anything here, or is it a mistake?

Very cool mods btw, love my first playthrough of Industrial revolution!

**Comment by Deadlock989** [comment]
Thanks for the compliment. You are missing something. Diamonds can be found in the world. Once cubic presses have been researched you can synthesize them.
