### ISSUE TITLE
Manifesto lists "Rocket Part" as prod 3 capable, but mod only has "Rocket Control Unit" which isn't

### ISSUE THREAD

**Issue by alelazar** [Deadlock989/IndustrialRevolution#191]
**Describe the bug**
Manifesto lists "Rocket Part" as prod 3 capable, but mod only has "Rocket Control Unit" which isn't

**Factorio version, IR version**
IR3 3.0.11
Factorio 1.1.76

**Comment by Deadlock989** [comment]
I don't understand what you're trying to report.

**Comment by alelazar** [comment]
![image](https://user-images.githubusercontent.com/6439462/217671830-b7bb5ad3-002b-4faf-892d-deb674da6bb9.png)

vs

![image](https://user-images.githubusercontent.com/6439462/217671928-b2960aa3-156b-4611-a539-6650b931b2d4.png)

I cannot add prod modules to the assembler with this recipe selected

**Comment by Deadlock989** [comment]
"[Rocket part](https://wiki.factorio.com/Rocket_part)" is the internal recipe used by rocket silos to construct rockets - see the recipes unlocked by the Rocket Silo technology in the technology viewer. This is how rocket silos work in vanilla as well. Productivity is enabled for this process.

Rocket control units do not have productivity enabled on purpose. Almost no end-products have productivity enabled in IR3, with the exception of analysis packs.

**Comment by alelazar** [comment]
Well that's embarrassing. I always just thought of it as space science. Thanks for the info!
