### ISSUE TITLE
Loader/underground belt render layer issues

### ISSUE THREAD

**Issue by johnLate** [Deadlock989/IndustrialRevolution#193]
**Describe the bug**
Similar to #170, a loader oriented in west-east direction is painted over an underground belt oriented in the same direction, placed directly south of it.
Screenshot:
![factorio-ir3-loader-rendering](https://user-images.githubusercontent.com/7539154/218326385-31693972-0c64-46c3-9b2c-00af5f9699ec.jpg)

**Factorio version, IR version**
1.1.76, 3.0.10

**Other mods installed**
DeadlockBlackRubberBelts 1.0.3, AAI Containers 0.2.11, AAI Loaders 0.1.3

**Comment by Deadlock989** [comment]
This issue occurs even if IR3 isn't installed - it's an issue for the authors of AAI Loaders.

**Comment by johnLate** [comment]
Sorry for not testing that. Thank you for IR3, I really enjoy it.
