### ISSUE TITLE
Sulphur Byproduct - Molten Equivalents

### ISSUE THREAD

**Issue by RepairmanSki** [Deadlock989/IndustrialRevolution#20]
Assuming the outcome of 2700 units/min of some primary ingot (copper, iron, tin, gold) the sulphur byproduct from crush > wash > molten > ingots is approx 6 units/min. If a secondary product (nickel, chromium, lead, tellurium) output is unavailable and the molten input is switched to crushed ore, the equivalent sulphur output jumps to 1200/min (not to mention the incredible volume of water produced when converting the sulphurous gas).

That there is more is not necessarily the issue, more that 200 times as much is quite challenging when there's so few inputs for sulphur/sulphurous gas the additional water, again, notwithstanding. This may have been more readily possible when acid washing was 60 units per cycle but that was changed just as this tech was becoming available in my game.

**Comment by Deadlock989** [comment]
This isn't a bug.
