### ISSUE TITLE
equipment and batteries, ID3

### ISSUE THREAD

**Issue by BlasterTK2** [Deadlock989/IndustrialRevolution#200]
Have Power armor MK1
It contains 5 personal roboports and 4 battery discharge equipment.
As i put charged advanced batteries into the discharge equipment one-by-one since manager told me it doesn't know which one to put in the said equipment, I accidentally ctrl+clicked (or is it shift) on all discharge equipment and they promptly got into my inventory. 4 advanced batteries however, were lost and not returned. I think that is not intentional and a bug. It is also not the end of the world since batteries aren't that expensive, but still.
IR3 version 3.0.12 and it's assets.
Other mods included: AAI Loaders, Better AAI Loaders for IR3, IR3 Squeak Trough, IR3: Early logistics system and Recipe Book.
Base mod 1.1.76, Game version 1.1.

**Comment by Deadlock989** [comment]
Unfortunately I don't think this is avoidable, at least with the current modding API. If you put a charged battery into an empty equipment generator (such as discharge equipment) then the battery is immediately consumed and the generator's buffer (the red bar) is filled. But the "spent result" is not returned until the bar is emptied. If you remove the equipment in the meantime, the progress bar is lost, and as far as I know there is no way of getting a reference to the actual instance of the equipment removed. I noticed someone recently [asking for interface support](https://forums.factorio.com/viewtopic.php?f=28&t=105300) to cover the same situation.
