### ISSUE TITLE
Air in copper/steel foam

### ISSUE THREAD

**Issue by Grindipo** [Deadlock989/IndustrialRevolution#203]
**Describe the bug**
The copper (and steel) foam recipe requires 20 compressed air, but produces exactly the same amount of air. Why ?

Thanks for the amazing mod !

**Factorio version, IR version**
1.1.76 / IR3 3.0.14

**Other mods installed**
No mods

**Comment by Cadams111** [comment]
It’s a catalyst. Thematically (I assume) you need to blow a ton of air through the ingots, but it’s in a pressurized environment so you don’t lose any. And when the foams come out of the blast furnace, ambient air fills the bubbles. That was, you have to manage fluid loops, but it’s net-zero so you don’t need a compressor. Is this correct, Deadlock?

**Comment by Deadlock989** [comment]
@Cadams111 - this isn't a chatroom, it's a bug tracker - please don't respond to issues on my behalf.

@Grindipo - the air is passed through, allowing you to chain blast furnaces, requiring only one compressor to get a foam production line running.
