### ISSUE TITLE
Adding color mask?

### ISSUE THREAD

**Issue by DiRtens** [Deadlock989/IndustrialRevolution#204]
Hi, Deadlock!
There is one more suggestion.
How about adding color masks to your vehicles?

**Comment by Cadams111** [comment]
I don’t think they would fit very well. The  vanilla car, tank, and spider are, well, vanilla colors meant to be tinted. IR’s vehicles are intensely colored based on materials included, with a copper orange monowheel, a maroon bronze heavy roller, and a chrome silvery heavy picket. The graphic/thematic disconnect is much more polished in IR than in vanilla, seeing as things made with copper actually look like copper, and adding color masks to the vehicles, while being a cool feature, would really not fit well in the existing IR vehicles. Now, I could totally see (another) new IR-specific vehicle, maybe made with steel parts, with some cool gun and a color mask compatibility, no question. But the existing vehicles would not support very well. If I’m reading the mod correctly, it would be cool, but probably not work out.

**Comment by Deadlock989** [comment]
The original monowheel did have a colour mask but it looked terrible for about 75% of the colour wheel. The same would be true for the heavy roller. The heavy picket does have scope for it but the colour mask layer is another burden VRAM and that vehicle is relatively large already.
