### ISSUE TITLE
Can't seem to remove -planted trees.

### ISSUE THREAD

**Issue by klugemonkey** [Deadlock989/IndustrialRevolution#208]
**Describe the bug**
After a play-through, we have a couple places where we had placed Electric Forestry units and decided to relocate them, however, we could not actually remove any of the "-planted" trees on those chunks.  The trees are not selectable and can not be deconstructed.  

Seems as if this is intentionally disabled and was wondering if this is by design or can be fixed, or toggled to disable in per-map mod settings.

**Factorio version, IR version**
Factorio version 1.1.76
IR version 3.0.14

**Other mods installed**
aai-containers	0.2.11
aai-loaders	0.1.4
aai-programmable-structures	0.7.4
aai-programmable-vehicles	0.7.22
aai-pv-crafting-group	0.0.1
aai-signal-transmission	0.4.7
aai-signals	0.6.1
aai-vehicles-chaingunner	0.6.1
aai-vehicles-hauler	0.6.1
aai-vehicles-ironclad	0.6.8
aai-vehicles-miner	0.6.4
aai-vehicles-warden	0.5.3
aai-zones	0.6.4
Advanced_Fishing	0.0.2
barrel-stages	1.0.0
belt-visualizer	1.1.7
big-data-string	1.0.1
biters_drop_money	0.9.7
BlueprintTools	1.3.0
bullet-trails	0.6.0
cargo-ships	0.1.22
cargo-ships-graphics	0.1.0
catch-and-release	1.3.1
circuit-poles	1.0.2
coin_generation	20.0.5
combat-mechanics-overhaul	0.6.24
CursorEnhancements	2.0.2
CustomColor	3.0.2
DeadlockBlackRubberBelts	1.0.3
Dectorio	0.12.6
DeleteChunks	1.1.1
disk	1.1.0
DragonIndustries	1.152.1
EvenDistributionLite	1.1.1
EvenMoreTextPlates	1.2.2
exotic-industries-robots	0.0.1
FactorIO	1.152.1
factorio-cooked-fish	0.0.7
FactorySearch	1.10.11
fcpu	0.4.14
Fill4Me	0.10.0
fireproof-bots	1.1.3
FJEI	0.6.4
Flare-Stack-edited	2.2.12
flib	0.12.4
GUI_Unifyer	1.12.0
helmod	0.12.14
IndustrialDisplayPlates	1,1,4
IndustrialRevolution3	  3.0.14
IndustrialRevolution3Assets1	1.0.7
IndustrialRevolution3Assets2	1.0.4
IndustrialRevolution3Assets3	1.0.1
IndustrialRevolution3Assets4	1.0.1
IndustrialRevolution3Projects	0.0.1
informatron	0.3.2
InlaidLampsExtended	1.1.2
inventory-repair	19.1.0
IR3_Squeak_Through	1.8.3
IslandStart	1.1.0
lightorio	1.1.6
LogisticTrainNetwork	1.18.2
ModuleInserterSimplified	1.1.3
more-fish	0.0.1
NicerFuelGlowButUpdated	1.0.16
no-wall-repair	0.0.4
Noxys_Extra_Settings_Info	0.4.2
Noxys_QuickerStumpFade	0.4.2
Noxys_StackSizeMultiplier	0.4.6
Noxys_Trees	0.4.2
OldWormSound	1.152.1
PMRPGsystem	1.0.1
PollutionColour	1.0.1
PollutionSolutionsLite	1.0.19
prime_intergalactic_delivery	20.0.8
Rampant	3.1.2
RampantArsenal	1.1.6
RateCalculator	2.4.8
RealisticFlashlight	0.2.4
Realistic_Electric_Trains_Fork	0.4.8
Realistic_Heat_Glow	2.1.0
repair-from-vehicle	0.1.1
Repair_Turret	1.0.3
RepeatingIslands_Comp11	  0.1.1
resource-islands	0.1.1
reverse-factory	8.1.17
rs-better-zero	1.1.0
safefill	1.0.11
shallow_water	0.0.1
shield-projector	0.1.6
Signalized_Couplers	0.1.3
single_train_unit	20.0.12
stack-size-tooltip	1.0.0
start-alt	0.0.2
stdlib	1.4.8
textplates	0.6.10
Torches	1.0.0
TrainSchedule	1.1.1
underwater-pipes	2.0.3
Warmonger	1.3.18
water-consumes-pollution	1.1.0
woodcarbonization	1.2.0
wooden-rails	0.1.0

**Comment by klugemonkey** [comment]
Also, not sure if these "-planted" trees are actually getting planted as part of the forestry or if another mod, perhaps is planting them, assuming that they are normal tree prototypes.

**Comment by Deadlock989** [comment]
The "-planted" variants are only intended to be spawned by IR3 when placing a tree bed. Do you have a way to replicate the existence of one without a bed? Deconstructing the tree bed (by hand or by bot or in the course of the forestry's growth/renewal script) is supposed to remove the -planted tree and vice-versa. Those tree variants have no autoplace setting so they are not supposed to spawn in any other situation.

That's quite the mod list so I'm not going to ask for save file. The first one I'd check would be Noxy's Trees which is almost certainly going to be incompatible judging by its description (automatic "spreading" of any tree anywhere). Are you able to confirm if it's the culprit?

**Comment by klugemonkey** [comment]
I'm thinkingthis is just Noxy's Trees mod planting the modified tree prototypes that are "-planted".   Perhaps the trees need to be added to their mod so they don't plant them.  We have also added/removed some mods, so not 100% sure this can't be something else.

**Comment by klugemonkey** [comment]
Also, looks like Noxy's disables trees from their planting, so I guess they try to plant everything that is a tree and is not blacklisted?
At least they put Angel's special trees in a blacklist.

**Comment by klugemonkey** [comment]
Perhaps they need to add some way to put all "-planted" trees in their list?

**Comment by klugemonkey** [comment]
Please close the other issue with similar name as I was trying to edit the original report after determining it might not actually be from the forestry, but rather from Noxy planting it.

**Comment by Deadlock989** [comment]
In the link above (request from 9 months ago) someone asks for a remote call to register non-spawnable trees but it hasn't been implemented. In my view NT shouldn't be trying to spread any tree that doesn't have an autoplace, because trees without an autoplace would not occur "naturally" in the world anyway.

I will fix this for the next version by marking NT as incompatible, if they change the way that mod works in future then the block can be removed.

**Comment by klugemonkey** [comment]
Anyway, if they are planting a tree that is a prototype with "-planted", is there a way to have it so that "-planted" tree can be deconstructed and/or cut down?   What is the normal behavior for a forestry tree?  Is selectable/minable disabled?

**Comment by klugemonkey** [comment]
Perhaps they would be motivated to add the -planted trees to their disabled list or implement the disabling if no autoplace rather than be marked as incompatible?

**Comment by Deadlock989** [comment]
"Forestry trees" - the ones grown and placed by a forestry - are just regular trees. The "-planted" trees are only ever supposed to be accompanied by a tree bed which is only ever placed by a player or by bots - the tree bed is always selectable and if it is removed or destroyed then the unselectable tree is also removed.

**Comment by klugemonkey** [comment]
Ah, ok, I see now, the ones with the stone bases are getting replaced, and then other side-effects occur.   So, basically Noxys needs to test with IR3 forestries and fix their side.

**Comment by klugemonkey** [comment]
OK, well, I suppose then if there is nothing to be done on your side, this issue can be closed.

**Comment by klugemonkey** [comment]
Please remove issue #209 as well.

**Comment by klugemonkey** [comment]
Refer to https://github.com/NoxyNixie/Noxys_Trees/issues/8
