### ISSUE TITLE
Mismatch with Gems - Ruby and Sapphire

### ISSUE THREAD

**Issue by Fuzzician** [Deadlock989/IndustrialRevolution#21]
Rubies require Chromium mineral to make via Cubic Press.  This is odd, given that it is Iron which generates it, instead of the Copper where Rubies are found.
Sapphire is found in Iron, but requires Nickel mineral to make more, which derives from Copper.  It seems that these have been flipped.
Diamond, for example does not have this issue.  It is found in Coal, which, when crushed, produced Carbon, which is exactly what you need to make more Diamonds in the Press.

**Comment by Deadlock989** [comment]
Odd maybe, but not an issue.
