### ISSUE TITLE
Suggestion: Air filter transfer

### ISSUE THREAD

**Issue by mussii** [Deadlock989/IndustrialRevolution#211]
When placing two air purifiers close together you can't transfer the air filters from one to the other via inserter. I'm thinking of the behaviour from labs where you can pass "down" the sciences from one lab to the other. 

I've attached a screenshot to clarify. 

![imagen](https://user-images.githubusercontent.com/27778442/225759767-c13b4e7c-3dc1-43aa-840a-58d3dcbb1c59.png)

**Factorio version, IR version**
IR3 3.0.14
Factorio 1.1.76

**Other mods installed**

**Comment by Deadlock989** [comment]
As far as I know this isn't possible with the current game engine / API. Internally, air purifiers are an assembling machine, and inserters will not ever pick up from the input slot of an assembling machine. Labs are a different kind of entity with special rules.
