### ISSUE TITLE
Rounding error in electric forestries

### ISSUE THREAD

**Issue by Cadams111** [Deadlock989/IndustrialRevolution#214]
Factorio 1.1.77, IR 3.0.11
![74B0167B-2EBF-4E80-95F7-486685B191B8](https://user-images.githubusercontent.com/121828380/226138814-82d67d0a-109c-4481-8d5b-9547bf0781da.jpeg)
(Sorry for photo, GitHub is on my phone and Factorio is on my desktop)
This is an unpowered electric forestry currently managing 29 trees. Typically, each tree adds 2% to the wood chance each forestry cycle. However, as you can see, there is a rounding error and it’s a little off. Since taking this picture, the forestry has somehow generated another tree (double bug report? Are they supposed to grow trees unpowered?) and the number is nice now, at exactly 60%.

**Comment by Deadlock989** [comment]
This is a floating point precision issue. The number 0.58 can't be represented precisely using double precision floating point, the closest you can get is 0.57999999999999998. I don't know why Factorio displays 0.58 as 57.99% for result probabilities when it rounds it up nicely for literally every other case (e.g. it seems perfectly happy to show 0.47999999999999998 as 48%). Lua only uses floating point, there are no integers or fixed point representations available. 

If there is a fix for this I don't know what it is, but I strongly suspect it is something only the game developers could address.

**Comment by Deadlock989** [comment]
Reported to Wube [here](https://forums.factorio.com/viewtopic.php?f=7&t=105661).
