### ISSUE TITLE
Migration issue with focused air separation

### ISSUE THREAD

**Issue by Cadams111** [Deadlock989/IndustrialRevolution#215]
**Describe the bug**
After updating to IR 3.0.15, I did not have the focused separation recipes available, even though I already had the Cryogenics research done, and the recipes for focused separation do appear in the tech menu. The cryo tower just can’t select the recipes.

**Factorio version, IR version**
Factorio 1.1.77, IR 3.0.15

**Comment by Deadlock989** [comment]
I can't reproduce this. If I open a saved game which was saved with an earlier version of IR3 then the on_configuration_changed script runs and I see the new recipes in the cryo plant recipe selection menu.

![image](https://user-images.githubusercontent.com/3128845/226251611-96e267cd-eaa2-4410-ae62-33c66c41bf37.png)

**Comment by Deadlock989** [comment]
Closed due to lack of reproduction steps / further reports.
