### ISSUE TITLE
[SUGGESTION] Changing the ID of the copper pump

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [Deadlock989/IndustrialRevolution#217]
I ask you to consider changing the identifier of the copper pump, namely to add a mod postscript, for example `ir3-copper-pump`

This is necessary to correct possible confusion with both other mods and mods for translation

**Comment by Deadlock989** [comment]
Sorry, this won't happen. The mod adds roughly 100 new entities and if I change one it sets a precedent for changing them all.
