### ISSUE TITLE
Cubic Press gated behind Yellow Science?

### ISSUE THREAD

**Issue by Fuzzician** [Deadlock989/IndustrialRevolution#22]
If the following is intentional, feel free to close this issue.

Currently, you cannot research Cubic Press until you get Yellow Science, but to do so, you need to get Rubies to make Laser Assemblers, which are needed to produce the Blue Circuits which Yellow Science requires.  So you are a bit stuck, unless you find enough Rubies to make enough Laser Assemblers to research the Press to get the process going.

**Comment by Deadlock989** [comment]
Yes, it's intentional.
