### ISSUE TITLE
[1.1.79-specific issue] Error while running event IndustrialRevolution3::script_raised_built (ID 79) attempt to index a nil value

### ISSUE THREAD

**Issue by Nirb8** [Deadlock989/IndustrialRevolution#220]
**Describe the bug**
Please give a clear and concise description of the suspected bug or issue: what is actually happening, what you expect should happen instead, and (if applicable) some steps for reproducing the problem. You can add screenshots if you like. If it is a script error, please include or screenshot the error.
![image](https://user-images.githubusercontent.com/57153743/228899661-3e576c18-4839-4f25-a80b-5895269f36d5.png)

Game crashes upon loading new chunk that contains rocks with gems.
**Factorio version, IR version**
Please confirm your Factorio version number and the Industrial Revolution version number.
IR3 3.0.16
Factorio 1.1.79 (build 60614, win64)
**Other mods installed**
If you are running other mods which change game content (entities, recipes etc.) list them here. No need if they are small QOL mods.
Grappling Hook - Earendel

**Comment by Deadlock989** [comment]
Factorio 1.1.79 is an experimental release; from what I can tell the rendering API is very broken in that version. Your options are to go back to a previous version or wait for another experimental release from Wube to fix it. I don't recommend using the experimental branch for regular play.

**Comment by Deadlock989** [comment]
This has apparently been fixed in [1.1.80](https://forums.factorio.com/viewtopic.php?f=3&t=105761).
