### ISSUE TITLE
Module Programmers are very loud

### ISSUE THREAD

**Issue by simply-peachy** [Deadlock989/IndustrialRevolution#223]
**Describe the bug**
I've finally had my first Module Programmer assembled, hurrah! I stood by as the computers flowed into it and had my ears surprised by the glorious, if rather loud, bleepy-bloopity, especially when there are three on the go at once. I suggest the volume for this sound effect might be reduced to a similar ambience of the other machines.

**Factorio version, IR version**
Factorio: 1.1.80
IR3: 3.0.16

Thank you for such an immersive and beautiful conversion.

**Comment by Deadlock989** [comment]
This is somewhat improved for the next version (reduced base volume by 60%) although most of the perceived volume is from the high pitch and pure tone of the beeps, so it simply hits the ear harder than technically louder but fuzzier sounds.
