### ISSUE TITLE
Progression with Cubic Press

### ISSUE THREAD

**Issue by wodzu93** [Deadlock989/IndustrialRevolution#224]
Is not being able to mass-produce things like Pulse Lasers or Steel Repair Kits at Blue Tech intentional? You can unlock those at Blue Tech, but to produce them, you need Rubies and Diamonds, which are produced from a Cubic Press - which is behind Purple Tech. I do know you can get those gems from rocks, but you only get a handful of them - just enough to kickstart mass production once you get the Cubic Press.

Would it make more sense to replace chromium components in the Cubic Press with steel ones and make it available at Blue Tech (as a prerequisite to 'Crushing and Mixing 3' and 'Pulse Laser' technologies), so gem dependent items can be utilized when they get unlocked?

Factorio 1.1.80, IR3 3.0.16

**Comment by Deadlock989** [comment]
Yes, it's intentional.
