### ISSUE TITLE
Dectorio Glowing Lamp has an easy recipe

### ISSUE THREAD

**Issue by theironrelic** [Deadlock989/IndustrialRevolution#225]
As of IR 3 3.0.17, I just noticed a minor issue when being used with Dectorio, a mod the FAQ says should be compatible.

The recipe for the special glowing lamps the mod adds are way too easy and not in the IR 3 spirit, if that makes. This isn't necessary but it would be nice to bring that in line with the lamp's recipe!

Thank you for the great mod!

**Comment by Deadlock989** [comment]
In a future version of the mod, Dectorio "small glowing lamps" will use the same recipe as IR3 small lamps.
