### ISSUE TITLE
Brick roads overpass cliffs

### ISSUE THREAD

**Issue by areyesca** [Deadlock989/IndustrialRevolution#227]
Dear Deadlock,

Making my happy roads i found this:

![imagen](https://user-images.githubusercontent.com/6408323/235721438-0ea5c9f1-a36a-4988-b3a1-db98d8b112d2.png)

It´s an easy to fix issue? anyway i will bomb away the cliff later on, but just to reach the perfection. I remember that you cannot place "floor bricks" close to cliffs. 

Congrats for the works, once again, and your time to fix the bug/issues. 

Best´s

**Comment by Deadlock989** [comment]
I'm able to replicate this without IR3 installed:

![image](https://user-images.githubusercontent.com/3128845/235729655-d2eff098-1e3e-41c0-a72d-b5d2db9d208a.png)

So I consider this either a non-issue or an issue with the base game.
