### ISSUE TITLE
diamonds spawn 

### ISSUE THREAD

**Issue by pepperbox2020** [Deadlock989/IndustrialRevolution#228]
It seems very difficult to get enough diamonds to kick start the cubic press. I need advanced crushers (requires 16 diamonds to make) to crush diamonds to powder but I could only get 14 diamonds from 2 hours of map exploration. At the same time I already got 80+ rubies. It seems like I could only find diamonds from iron patches, not coal patches.

I think it would be good to add a way to get gems from acid washing (perhaps new recipes). Or just add more gems per rock (or more gem rocks per ore patch)

**Comment by Deadlock989** [comment]
There is a hefty dose of RNG involved with this, as well as ore patches being dependent on map settings. It sounds to me from the limited information provided that you were simply just a bit unlucky. But essentially, I want it to be relatively difficult and to involve at least some exploration. Guaranteeing that they will spawn within arm's reach on even the stingiest map settings just means it will become trivially easy on regular maps.

Gems were a byproduct of ore washing back in IR1 - returning to that scheme would be going back full circle to a mechanic that was abandoned a couple of years back. There are enough issues with balancing ore washing without introducing a third product from the process. IR1 games typically featured piles of warehoused diamonds stacked to the heavens, or shovelling rubies wholesale into incinerators.

**Comment by pepperbox2020** [comment]
![image](https://github.com/Deadlock989/IndustrialRevolution/assets/72322226/3b51893c-04ed-4bd5-89fb-7f2965aa7f08)
I don't know how difficult it was intended to be. I have explored 100+ ore patches and reached behemoth worms on an ir3 recommended map setting before getting enough diamonds, and all of them came from iron ore patches. Is it intended that diamonds can't be found in coal patches?

**Comment by pepperbox2020** [comment]
> Gems were a byproduct of ore washing back in IR1 - returning to that scheme would be going back full circle to a mechanic that was abandoned a couple of years ago. There are enough issues with balancing ore washing without re-introducing a third product to the process. IR1 games typically featured piles of warehoused diamonds stacked to the heavens, or shovelling rubies wholesale into incinerators.

The ore washing issue could be solved by adding more washing options. For example, adding a washing recipe with much less secondary mineral output (without changing the existing one). Adding a washing recipe where you can collect gems can be a solution to prevent soft locks on heavy biter maps. Example recipe: 2x chromium mineral + acid --> 1x chromium mineral + 1% ruby. similarly, for diamonds: 2x graphite + acid --> 1x graphite + 1% diamond
