### ISSUE TITLE
Unlisted mod conflict with Vortik's Deep Core Mining.

### ISSUE THREAD

**Issue by Jesseman1** [Deadlock989/IndustrialRevolution#230]
**Describe the bug**
Mod conflict between IR3 and Vortik's Deep Core Mining, having them both enabled causes Factorio to give an error on launch and force both mods to be disabled to launch successfully.

**Factorio version, IR version**
Factorio version 1.1.8, IR3 version 3.0.18.

**Other mods installed**
AAI Loaders, Afraid of the Dark, Aquafarm Extended, Better AAI Loaders for IR3, Cargo ships, Industrial Cargo Ships,  IR3 Squeak Through, Island Start, Train and Fuel Overhaul, Vortik's Deep Core Mining.

**Comment by Deadlock989** [comment]
There are likely hundreds if not thousands of incompatible mods out there, I can't list them all. Mod conflicts are inevitable.
