### ISSUE TITLE
Double instance of Steam Lab sound loop.

### ISSUE THREAD

**Issue by Jesseman1** [Deadlock989/IndustrialRevolution#232]
I'm not sure if this is intentional or not, or if it only affects the steam lab, but if you have a single steam lab actively running and you open the UI for it at the same time, two different instances of the same sound loop will be playing simultaneously for as long as the UI is open.

Factorio version 1.1.80, IR3 version 3.0.18

Other mods: AAI Loaders, Aquafarm Extended, Black Rubber Belts, Larger Lamps, IR3 Squeak Through, Island Start, Cargo Ships, Train Overhaul, AAI IR3 Patch, IR3 Cargo Ships.

**Comment by Deadlock989** [comment]
This also appears to be true for at least some other entity types, e.g. assemblers. I don't know if it is true for every entity. It can be confirmed using the F5 debug info ("Sound instances"). My guess is that the extra sound originates in the entity preview pane in the entity GUI. This feature also occurs in vanilla, there is nothing I can do about it.
