### ISSUE TITLE
Forestries Counting Landfill as Artificial Tiles

### ISSUE THREAD

**Issue by ejinotti** [Deadlock989/IndustrialRevolution#235]
Forestries seem to be counting landfill as an artificial tile and not spawning new trees on it.  This results in forestries entirely on landfill slowly losing trees as they attempt to replace player-built trees with new native trees, but the spawns fail.  This seems unintended?

In the screenshot below you can see how all new, native trees have spawned exclusively on the few tiles of natural, non-landfill terrain at the bottom of the chunk.

![screenshot-tick-4254426](https://github.com/Deadlock989/IndustrialRevolution/assets/9387539/f84d343f-f47c-47de-b06d-9e04002fd837)

**Comment by Deadlock989** [comment]
That's ... frustrating. I have been using `get_hidden_tile()` as a shortcut for determining whether a given tile position is "artificial", i.e. has a mineable tile covering. However on testing for this issue it seems that landfilled tiles can end up with weird hidden tile values despite landfill not being mineable and only ever having been water before being landfilled. Searching on the forums, it seems other people have been tricked by this method in the past and the devs think it is working as intended. 

Workaround is to use some other less efficient way of determining whether a tile position is "artificial" or not instead, I guess by looking up the tile's prototype and checking `mineable_properties`.

**Comment by Deadlock989** [comment]
Fixed for next version. In theory (but rarely in practice) this issue could also affect the "driving autocorrect" option in per-player settings.
