### ISSUE TITLE
Efficiency Module Description is Misleading

### ISSUE THREAD

**Issue by danbopes** [Deadlock989/IndustrialRevolution#236]
**Describe the bug**
See this image:
![](https://i.imgur.com/RViTCxP.png)

Since these modules do not reduce emissions, the tooltip should be updated to reflect that.

**Factorio version, IR version**
Factorio Version: 1.1.80
IR Version: 3.0.18

**Comment by Deadlock989** [comment]
No, this accurate. Emissions are directly proportional to energy use. If energy use is reduced then emissions are reduced.

https://wiki.factorio.com/Efficiency_module
