### ISSUE TITLE
Air purifier

### ISSUE THREAD

**Issue by mmmmmmorten** [Deadlock989/IndustrialRevolution#239]
**Seems to not be working at all?**
Placed four machines in four different chunks to clear up some oil production pollution and it does not seem to do anything...  eating air filters like there is no tomorrow, but not cleaning up the air.
There is actually no change in pollution dissipation from chunks with air purifiers and adjacent chunks.  Should be -30/m right?
Attached pic of air value where you can see 4 machines that has been on for 20 min at least.

Thank you for a great mod - having tons of fun (even with sour gas issues all the time)!
Morten

**Factorio version, IR version**
Faction 1.1.80 IR3 1.1.0.9

**Other mods installed**
Attached txt file with all active mods (txs kuxynator for great mod)

![Air polution values](https://github.com/Deadlock989/IndustrialRevolution/assets/73776660/49cfc33d-5653-451f-a757-4f7c35ace27e)
[active_modsversion.txt](https://github.com/Deadlock989/IndustrialRevolution/files/11712544/active_modsversion.txt)

**Comment by Deadlock989** [comment]
It definitely works, has worked for a couple of years or so.

From that screenshot I can see 18 nearby oil refineries putting out at least 6ppm each (depending on what modules you have in them) and then I don't know how many chem plants and furnaces as well putting out similar. So your 4 air purifiers are not even matching that output. I don't know what is offscreen, there may be some other big pollution hotspot nearby. The bigger the disparity in pollution value between two neighbouring chunks, the quicker pollution spreads between them.

If by "pollution dissipation" you're referring to the middle number in that debug info then I don't think that's what that is. I didn't know that debug option existed until today - there is no description of what the number refers to. My guess is that it only refers to the absorption value of the terrain and trees in that chunk, see the chunks with trees bottom right - vanilla Factorio doesn't use negative pollution values on any other entity. But it's just a guess, you would have to ask the Factorio devs or community.

If you can give me some reproduction steps which show that it is clearly not working and can verify that the stats on air purifiers and air extractors have not been changed by another mod, I can look at this again, but barring that, it's working as advertised.
