### ISSUE TITLE
Iron pipe overlapping flamethrower turret pipe

### ISSUE THREAD

**Issue by Bilka2** [Deadlock989/IndustrialRevolution#24]
Again, images really help:
![image](https://user-images.githubusercontent.com/27060268/108899397-a685a080-7618-11eb-8853-6064289e02f0.png)

Vanilla:
![image](https://user-images.githubusercontent.com/27060268/108899424-ae454500-7618-11eb-9a20-95620030b816.png)

Not sure what's going on here or if it's fixable, but I wanted to make sure it's logged anyway.

**Comment by Deadlock989** [comment]
IR2 pipes are composed differently and aren't cropped to tile boundaries. There were similar issues with the north-facing connections on vanilla storage tanks and pumps. In those cases I was able to patch the sprite with vanilla assets fairly easily.
