### ISSUE TITLE
Question/Alternate to a Conflict mod

### ISSUE THREAD

**Issue by yaitsbilly** [Deadlock989/IndustrialRevolution#241]
Is there an alternative mod to use for Squeak Through, or a way to walk over pipes?

**Comment by Deadlock989** [comment]
There is one on the mod portal but currently it still breaks things.

The best way for a pipe cheat mod to do it would be to simply remove "player-layer" from the collision mask of pipes and undergrounds. This isn't something I'm interested in doing, sorry.
