### ISSUE TITLE
modified dectorio gravel recipes disabled

### ISSUE THREAD

**Issue by ThreePounds** [Deadlock989/IndustrialRevolution#247]
**Describe the bug**
The recipes for the decorative gravel-types are disabled. Even though the corresponding tech (gravel 1) is researched, they are not listed in the inventory screen, nor are the recipes selectable in the steam mixer. Upon investigation in file `\code\mods\mods-data-final-fixes.lua` on `line 80` the flag `enabled = false` is set. Setting this flag to `true` instead makes the recipes available for crafting with no apparent side effects.

**Factorio version, IR version**
1.1.85, 3.0.19

**Other mods installed**
Dectorio 0.12.6

**Comment by Deadlock989** [comment]
Setting `enabled = true` on a recipe makes it always available, i.e. without being researched.

I can't reproduce this - if I research Crushing & Mixing 1 then the Dectorio gravels are unlocked.

Did you add Dectorio mid-game, after researching C&M 1?

**Comment by ThreePounds** [comment]
That makes sense. I'm not familiar with factorio's code so I didn't know what `enabled` is used for.

>Did you add Dectorio mid-game, after researching C&M 1?

Yes, that's indeed the culprit. Sorry for the confusion.

Thanks for the help.

**Comment by Deadlock989** [comment]
I can add a migration check here. In most cases I would leave other mods to fix their own installation / migrations, but in this case IR3 has made a change to Dectorio's assumptions by locking the decorative gravels away behind techs.

In the next release of IR3, adding Dectorio to an existing save will force a technology effects reset, enabling the gravels if the crushing techs have already been researched.
