### ISSUE TITLE
Electroplater SFX seems a bit too loud

### ISSUE THREAD

**Issue by Kromster80** [Deadlock989/IndustrialRevolution#252]
**Describe the bug**
Not a bug really, just a small observation. Electroplater SFX when doing electroplating seems a bit too loud compared to other machines sound effects.

**Factorio version, IR version**
1.1.80 - 3.0.18

**Other mods installed**
None

**Comment by Deadlock989** [comment]
Reduced slightly for next version; also reduced ore washing plant.
