### ISSUE TITLE
Steam inserters are not upgradable

### ISSUE THREAD

**Issue by TonyDecvA180XN** [Deadlock989/IndustrialRevolution#253]
**Describe the bug**
Hello,
Is there a reason steam inserters and long steam inserters are not upgraded? They just are not available in upgrade planner lists. And building over is also not working. Have to deconstruct and place again. Steam assemblers do upgrade, so I think inserters should also be able to be upgraded. Same for Telescope/Radar. Also, in-game feature "Flip horizontally/vertically don't work if steam inserters present in blueprint. (idk if there is anything more, just started playthrough)

**Factorio version, IR version**
Factorio 1.1.80 (build 60618, win64)
IR3 3.0.19

**Other mods installed**
Alien Biomes
Black Rubber Belts
Larger Lamps

**Comment by Deadlock989** [comment]
Yes, there are reasons they are not upgradable: see #171, #165, #62

Blueprint flipping isn't accessible to modders and doesn't take energy sources into account: see #249, #89, #35, https://forums.factorio.com/viewtopic.php?f=48&t=100988
