### ISSUE TITLE
Electric scrapping machine missing recipe

### ISSUE THREAD

**Issue by magu5026** [Deadlock989/IndustrialRevolution#26]
It is not possible to build an electric scrapping machine due to the lack of technology to unlock the recipe.

**Comment by RepairmanSki** [comment]
You either have conflicting mods or need to look again:

![scrapping](https://user-images.githubusercontent.com/26292463/109433492-71d16a80-79c5-11eb-945c-4245363c2de0.png)

**Comment by magu5026** [comment]
conflicting mod: Reverse Factory
