### ISSUE TITLE
Insulated pipes and storage tanks for molten metals

### ISSUE THREAD

**Issue by Kromster80** [Deadlock989/IndustrialRevolution#262]
**Situation**
- It feels quite odd that normal steel piping and storage tanks can be used to transport molten metals (including steel itself).
- Piping cost can seem too inexpensive.
- IR could benefit from a bit of additional complexity with Arc Furnace tech stage.

**Suggestion / discussion**
Include separate branch of pipe and tank products featuring "magic" insulation. Does not have to be based in reality (after all we typically dont pipe molten metals). The magic can be a number of ideas, tailored to the required tech level:
- "super-capillary cooling", pipes/tanks could require foam steel to produce
- "self-sustained maglev nano-effect", pipes/tanks could require field effect nano-mesh to produce
- "super-insulation", pipes/tanks could require stone wool produced from gravel and compressed air
- etc.

If that idea has any merit from gameplay standpoint, I'm open to discuss details and/or other approaches to it.

**Comment by Deadlock989** [comment]
I have always wanted to do this and similar things, e.g. dedicated gas pipes.

Unfortunately the game engine allows pipes and fluidbox connections to have either zero filters or one filter. You cannot have multiple filters. This is why steam pipes allow steam and nothing else, and water pipes allow water and nothing else, and the iron pipes allow everything. To have molten-only pipes would require a different pipe per molten metal.

Several modders have asked Wube to revisit this design decision but they apparently perceive it as potentially compromising the performance they've worked so hard on, and the fluid system has other more pressing issues, has had at least two (not especially successful) attempts to improve it, etc. There had to be [quite the campaign](https://forums.factorio.com/viewtopic.php?f=28&t=46302) even just to get one filter per fluidbox.
