### ISSUE TITLE
Lengths for the short underground and long underground pipes are swapped

### ISSUE THREAD

**Issue by MoltenLichQueen** [Deadlock989/IndustrialRevolution#263]
The Short underground pipes have a max length of 21 and cost 10 pipes, while the normal ones cost twice as much and have a max length of 10.
![2023-07-14_15-42-27](https://github.com/Deadlock989/IndustrialRevolution/assets/4225736/d5e707ff-5838-442a-b912-8659a4095d7c)
![2023-07-14_15-42-38](https://github.com/Deadlock989/IndustrialRevolution/assets/4225736/d77fb080-04ee-4029-b840-7c5fd379a3df)

**Comment by Deadlock989** [comment]
This isn't the case in IR3: all of the short undergrounds cost 5 pipes and are 5 tiles long, all of the regular undergrounds are 10 and cost 10 with the exception of plain pipes which are 15 and 15. In your screenshot I can see that at least two other mods have altered the short underground pipes.
