### ISSUE TITLE
Can't load the mod

### ISSUE THREAD

**Issue by LeftHandCode** [Deadlock989/IndustrialRevolution#265]
**Describe the bug**
When trying to get the mod to work it's constantly red, saying it's inactive, I have all the assets packs and everything should be workign but its still inactive

**Factorio version, IR version**
1.1.87, and 3.1.0 packs 1.1.0

**Other mods installed**
Black rubber belts, Cargo ships, Disco science, factorio Libraraty, flow control FNEI, Informatron, large lamps,milestones, player auto build, rate calculator, recipe book

**Comment by Deadlock989** [comment]
When a mod name appears in red, it means you have another incompatible mod installed. In this case, Disco Science.

**Comment by LeftHandCode** [comment]
Thank you
