### ISSUE TITLE
Molten recipes in Factory Planner

### ISSUE THREAD

**Issue by janfeitsma** [Deadlock989/IndustrialRevolution#27]
Hi Deadlock,

The Factory Planner mod gives a strange error when I click to expand molten carbon steel: "no existing recipe"...

Is this a problem with the FP mod, or is there something you could do in IR2?

![image](https://user-images.githubusercontent.com/24246517/110142878-eb5ac580-7dd6-11eb-81fd-10b76de8ce9f.png)

(Great mod by the way, I'm glad you got back into it!!)

Cheers, Jan

**Comment by Deadlock989** [comment]
I'm not familiar with Factory Planner. There is nothing particularly unusual about the molten metal recipes - the only thing I can think of is that they have the hide_from_player_crafting flag set, which stops them from appearing in the player's crafting menu but still allows them to be shown in machine config crafting menus.
