### ISSUE TITLE
[REQUEST] Add my Recycling Machines Mod to your incompatability list

### ISSUE THREAD

**Issue by DRY411S** [Deadlock989/IndustrialRevolution#270]
**Describe the issue**
My mod is not compatible with IR3 and replicates some IR3 functionality anyway. Please can you add it to your incompatability list. I will be doing the same on the next release of my mod.

**Factorio version, IR version**
1.1.87, all IR versions

**Other mods installed**
My mod is coded internally as 'ZRecycling', current version is 1.1.4.

**Comment by Deadlock989** [comment]
It doesn't need to be in both lists.
