### ISSUE TITLE
3.1 balance changes make Gas & Blast furnaces almost pointless

### ISSUE THREAD

**Issue by matthew-sharp** [Deadlock989/IndustrialRevolution#278]
**Describe the issue**
So maybe I'm missing something, and maybe this is just my playstyle. However once I have efficiency 2 modules I can't see any reason to use gas or blast furnaces.

*Gas Furnace*
* Energy consumption can be almost matched by electric furnace with 2 efficiency 2 modules. Electrical logistics are far easier than NG logistics. I say almost as once you add the idle drain of an electric furnace, then a gas furnace is slightly better.
* Pollution per item is far lower with an electric furnace with 2 efficiency 2 modules. This is true even if I burn the NG in a generator to power the electric furnace.
* The tech path to Gas furnace diverges from the path to modules 2, it's hard to say if it's easier or harder. However even if it's easier, efficiency 1 modules are a good enough substitute that I wouldn't build out gas furnaces for the small time where I have gas furnaces but not modules 2.

*Blast Furnace*
* Energy consumption can be beaten by electric furnace with 2 efficiency 2 modules.
* Pollution per item is generally far lower with an electric furnace with 2 efficiency 2 modules. Maybe if I generated my electricity from burning coke, considered the pollution offset from compressing air (which I don't think is valid as that doesn't negate evolution and can be done without a blast furnace anyway), and ignored the CO2 then I could make a blast furnace come out better.
* Electric furnaces are easier to set up than blast furnaces.
* Blast furnaces use half the coke per unit of steel/silicon, however I'm not usually short short on coke once I get charcoal and/or solar up and going (which is well before blast furnaces). And that was before coke got removed from plastic production. Even if I consider the pollution/energy used to produce the "extra" coke I need for electric smelting, that barely moves the needle.
* Blast furnaces are twice as fast per furnace. That doesn't seem important enough to justify blast furnaces over just building twice as many electric furnaces with efficiency modules.

**Factorio version, IR version**
1.1.87, 3.1.3

Someone might say "but what if you put productivity modules in your electric furnaces". Well at least that's an option that electric furnaces have that gas and blast furnaces do not any more. If I do that, then I've decided that it's a better choice than efficiency modules.

As I said maybe this is just playstyle specific or maybe I'm missing something, but it would be nice to have a reason to use gas and/or blast furnaces. Right now they seem to only have niche applications (NG glut but can't set up generators, coke shortage, tight on space, or furnaces which will spend huge amounts of time idle so the 10kW idle drain becomes an issue).

**Comment by Deadlock989** [comment]
Don't use them then.

**Comment by Wiwiweb** [comment]
> Don't use them then.

But what is the design idea? They are meant to be worse on purpose as a noob trap?

I specifically looked for this thread because we were also confused by the gas/blast furnaces and I figured someone had already brought it up.

**Comment by matthew-sharp** [comment]
I can't answer definitively, but before 3.1 these furnaces did have a point. 3.1 was a rebalance. Blast and gas furnaces lost the ability to accept modules, and were given some offsetting (but insufficient) buffs. I suspect they are only still here so that bases built with 3.0 still mostly function.

If we were missing something, I would have thought someone would point it out by now.

**Comment by aristaeus** [comment]
Gas furnaces also have the disadvantage of being tied to oil processing - if plastic backs up then so do your gas furnaces. It's much easier to circuit prioritise burning natural gas with a fallback to coal/coke boiler electricity. I'm only just past blue science so maybe this concern is unfounded, but I'm hesitant to set up a gas smelter without an electric one beside it to fill in the gaps - and at that point, why bother?

Actually, this raises a good point.

> The tech path to Gas furnace diverges from the path to modules 2, it's hard to say if it's easier or harder. However even if it's easier, efficiency 1 modules are a good enough substitute that I wouldn't build out gas furnaces for the small time where I have gas furnaces but not modules 2.

Gas furnaces aren't viable at all until you have continuous consumption of oil products, i.e. red circuit production, and it's a very short step from there to tier 2 modules. So they aren't even unlocked earlier at all!

I think the pollution from them could be reduced - an electric furnace with 80% efficiency from modules and powered by natural gas produces less than a third the pollution of a gas furnace (1.903125/m for the electric furnace if my maths is correct), and that seems strange to me. I'm not sure how realistic this is, but I'd even be ok trading higher energy consumption in a gas furnace for lower overall pollution per ingot than is possible with an electric furnace. At least then there's an interesting tradeoff if you want a green factory.
