### ISSUE TITLE
Shortcuts badly ordered in the quick panel (gamepad support)

### ISSUE THREAD

**Issue by Bilka2** [Deadlock989/IndustrialRevolution#279]
**Describe the issue**
The fuel manager and manifesto shortcuts are ordered first in the quick panel, which is used when controlling Factorio with a gamepad/controller. The shortcuts in the quick panel cannot be reordered but rely on muscle memory based on the position. So putting new shortcuts at the start of the panel breaks that muscle memory acquired in the base game. See 
[Controller modding guide / FAQ](https://forums.factorio.com/106661). All other parts of the mod work without problems with controllers, this is the only snag. If you want to set a default controller hotkey for the entity adjustment hotkey, I can report that `controller-righttrigger + controller-b` works well for me.

![Screenshot_20230725_184725](https://github.com/Deadlock989/IndustrialRevolution/assets/27060268/4638fbff-f682-4ca2-9dfb-f797c0284da8)

**Factorio version, IR version**
   1.468 Loading mod base 1.1.88 (data.lua)
   1.733 Loading mod IndustrialRevolution3 3.1.3 (data.lua)

**Other mods installed**
   3.530 Checksum of alert-center: 3111057282
   3.530 Checksum of DeadlockBlackRubberBelts: 1182093044
   3.530 Checksum of DeadlockLargerLamp: 4210112940
   3.530 Checksum of IndustrialRevolution3Assets1: 0
   3.530 Checksum of IndustrialRevolution3Assets2: 0
   3.530 Checksum of IndustrialRevolution3Assets3: 0
   3.530 Checksum of IndustrialRevolution3Assets4: 0
   3.530 Checksum of rainbow-player-color: 1597214319
   3.530 Checksum of sleepy-bean-trains: 1376014250

**Comment by Deadlock989** [comment]
This sounds like a base game issue to me. I don't have a controller, am not interested in supporting controllers. These shortcuts have worked fine for the last 2-3 years.

**Comment by Bilka2** [comment]
Base game could order shortcuts without an order string better, yeah, but I don't see it happening. There was some complicated reason why it works how it works that I'm not gonna look up now because I'm on vacation from work.

Since this can be fixed by just setting an order string (that is sorted after "c") on the shortcuts, I could do the change in an extra mod. That's a completely fine option for me if you'd rather not touch controller support related things.

**Comment by Deadlock989** [comment]
Yeah, to be honest, I'm not motivated to touch this. These shortcuts have no order string set because (a) it was an optional property then and is [still listed as an optional property now](https://wiki.factorio.com/Prototype/Shortcut), and (b) there was never a reason to set an order because it had zero effect on the order of the shortcut bar, which (I'm guessing) is based on player data. Requiring every modder to use an order that is higher than the arbitrary value of "c" seems like asking for trouble.
