### ISSUE TITLE
AAI Zones compatibility

### ISSUE THREAD

**Issue by xBeathovenx** [Deadlock989/IndustrialRevolution#28]
The Zone Planner is not unlocked with the Electronics research. Also cant find it in any other research.
Issiue seems to be cause "electronics" got renamed to "ir2-electronics-1". no clue if you can somehow make it compatible from your side. i fixed it for me with renaming it in AAI Zones, but no clue how to make a compat mod. :/

**Comment by RepairmanSki** [comment]
The only noted mod compatibility for AAI is 'Containers and Warehouses ' and 'AAI Vehicles: Hauler'.

**Comment by Deadlock989** [comment]
AAI Zones isn't going to be supported.
