### ISSUE TITLE
Barrelling code does not check for fluids with layered icons

### ISSUE THREAD

**Issue by kasanryukin** [Deadlock989/IndustrialRevolution#281]
![image](https://github.com/Deadlock989/IndustrialRevolution/assets/8062699/ca72f1ec-36d8-4a75-8911-27e96aa022df)

**Factorio version, IR version**
Factorio latest stable, I.R 3.1.4

**Other mods installed**
None (I had intented a lot of side long mods, but the initial load of IR3 doesn't even let me get into the game to do it)

**Comment by kasanryukin** [comment]
Well above is incorrect, I did have another mod enabled; Rampant Arsenal.  The error above I'm almost certain is related to the Napalm fluid that mod adds.  Disabling it got the game to load.

**Comment by Deadlock989** [comment]
This is due to IR3's barrel code not anticipating that a fluid might have a multiple-layer icons definition. Fixed for next version (but that will not be released for a while).
