### ISSUE TITLE
Roboport construction area

### ISSUE THREAD

**Issue by red-arclite** [Deadlock989/IndustrialRevolution#282]
**Describe the issue**
The roboport's logistics area is 64x64, while the construction area is 128x128. That means when building a new roboport at the maximum distance allowing a logistic network connection to an existing roboport, the outer 2 rows/columns of tiles of the new roboport will not be within the construction area. If there are trees, rocks or to be deconstructed entities within those tiles, construction robots cannot build the new roboport, since no construction robot can remove the obstacle. This can be an issue that may require manual clearing or additional preparations for placing blueprints, especially for larger scale blueprints like city blocks. 

Both the robotower as well as the vanilla roboport are not affected by this issue, since their construction area's diameter is more than twice the diameter of their logistic area.

I therefore would humbly suggest a slight increase of the roboport's construction area.

Thank you for your consideration.

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/140971748/427446f3-9804-4870-9fc9-5b3c69170782)

**Factorio version, IR version**
1.1.87, 3.1.4

**Other mods installed**
QOL mods only

**Comment by Deadlock989** [comment]
This makes sense, and I can see that vanilla made the same adjustment (way back in version 0.15.6).

**Comment by Deadlock989** [comment]
It's been nagging at me for at least a couple of years that you can fit four robotowers (total charging stations: 8) into the same footprint as a roboport (charging stations: 4), and the total cost of four towers is perhaps borderline cheaper, which means that four towers outperforms a roboport on almost every metric except a slightly lesser construction range (which still needs to be increased on roboports anyway, as argued in the report above). 

For next version:

- Roboport radius increased from 128x128 to 192x192, mirroring the robotower formula of a construction area 3x the width of the logistics area
- Roboport charging stations increased from 4 to 8
