### ISSUE TITLE
No burner leach at stone alloy furnaces

### ISSUE THREAD

**Issue by janfeitsma** [Deadlock989/IndustrialRevolution#284]
**Describe the issue**

I was expecting the burner inserters to leach off these new stone alloy furnaces, as they do with burner miners.
However it seems this does not work. 
It feels like a bug. Or was it intentional?

Screenshot:
![image](https://github.com/Deadlock989/IndustrialRevolution/assets/24246517/a741b2d2-9a54-4bdc-b336-d27d5bd5dc2c)

**Factorio version, IR version**
IR 3.1.4
factorio 1.1.88

**Other mods installed**
QoL only. For completeness:
```
   1.999 Loading mod core 0.0.0 (data.lua)
   2.035 Loading mod base 1.1.88 (data.lua)
   2.147 Loading mod flib 0.12.9 (data.lua)
   2.154 Loading mod FNEI 0.4.1 (data.lua)
   2.161 Loading mod factoryplanner 1.1.72 (data.lua)
   2.168 Loading mod IndustrialRevolution3 3.1.4 (data.lua)
   2.299 Loading mod base 1.1.88 (data-updates.lua)
   2.314 Loading mod WideChests 4.1.0 (data-updates.lua)
   4.159 Loading mod inland_pumps 0.1.0 (data-updates.lua)
```

**Comment by Deadlock989** [comment]
This is the core game's behaviour for leeching ([this property](https://wiki.factorio.com/Prototype/Inserter#allow_burner_leech)) - it is intended that the inserter fills its own inventory but taking out of the source burner slot and putting it anywhere else seems to be quite patchily supported. It isn't just the new alloy furnaces, it also does not function with regular stone furnaces or any other burner furnace, so at least the alloy furnaces are consistent with their cousins. It does work from burner drill to burner drill, I don't know why. If you think this inconsistency counts as a bug then you could report it to Wube on their official forum.

**Comment by janfeitsma** [comment]
OK clear, thanks!
