### ISSUE TITLE
More detailed “can’t go there” messages in furnace-type entities

### ISSUE THREAD

**Issue by Cadams111** [Deadlock989/IndustrialRevolution#285]
**Describe the issue**
In Factorio 1.1.89, mods can now change the error text when you try to put something in a furnace-type entity that doesn’t belong there, such as trying to stuff ingots into barreling pumps. ([108146](https://forums.factorio.com/108146)) Are you planning to update the error texts to look nicer, such as “Steel Ingot isn’t a barrel” or “Revolutionary Circuit can’t be washed” instead of “Steel Ingot can not be placed there”?

**Factorio version, IR version**
Factorio 1.1.89
IR3 3.1.5

**Other mods installed**
N/A

**Comment by Deadlock989** [comment]
I wouldn't get your hopes up - it doesn't feel like a great use of my time given that it's a flavour text that people will hardly ever see. The mod already replaced the game engine's default `X cannot be smelted` text to `X cannot be placed here` which seems to me to be at least adequate.

However I will check this out once this new property leaves the experimental branch (i.e. after 1.1.89+ is marked as stable).

**Comment by Deadlock989** [comment]
Actually - I don't think this is worth the customisation. Manually picking up an item stack and then clicking on an input slot is a relatively rare activity. The "smelted" message jarred me enough to change it but coming up with active verbs for every crafting category type seems like work. 

There are also loads of inconsistencies around this in the game engine when trying to insert an unsupported item into a furnace-type entity:

With GUI open:

- By manually dropping the stack into item input slots: **localised message** (per entity prototype as of 1.1.89)
- By manually dropping the stack into fluid input slots: **nothing**
- By manually dropping the stack into item output slots: **generic message** (`X cannot be inserted here`)
- By manually dropping the stack into fluid output slots: **nothing**
- By shift-clicking the stack still in inventory: **nothing**

With GUI closed:

- By shift-clicking the stack in the cursor directly onto an entity itself: **nothing**

Thanks for the heads-up but I don't see myself spending time on this.
