### ISSUE TITLE
cannot build radar from raw materials

### ISSUE THREAD

**Issue by i-make-robots** [Deadlock989/IndustrialRevolution#286]
**Describe the issue**
I have enough raw materials in hand to make em coils, and all the other parts to make radar BUT it will not let me queue radar until I have manually crafted the coils.

**Factorio version, IR version**
1.1.89
IR3 latest

**Other mods installed**
IR3, vehicle snap, FP, FNEI.

**Comment by Deadlock989** [comment]
I can't reproduce this. If I have sufficient rubber, copper ingots, iron ingots and glass in my inventory, I can craft a radar and it will queue all of the intermediates (copper wire, copper foil, thermionic tubes, electronic circuits, iron plates, iron rods, iron rivets, small iron frame, computer mk1, iron beams, large iron frame, EM coils, heavy copper cable).

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/3128845/a1a8bfc7-55f7-4495-a098-06a1c9a9633e)
