### ISSUE TITLE
Guru Meditation Error on Startup

### ISSUE THREAD

**Issue by Goldobsidian** [Deadlock989/IndustrialRevolution#29]
I am getting the following error. I am not sure if it is a incompatibility but wanted to pass it on. I am running a fairly heavily modded system with Bob's as a core which I am guessing maybe the issue.

Failed to Load Mods:

Guru meditation error: Industrial Revolution has detected a cycle in the technology tree.
Probable cause: A mod has added an incompatible recipe unlock or technology prerequisite to one of the following:

oil-processing (oil-refinery, pumpjack, chemical-plant, iron-gas-vent, basic-oil-processing, heavy-oil-cracking, light-oil-cracking, solid-fuel-from-heavy-oil, solid-fuel-from-light-oil, solid-fuel-from-petroleum-gas)
fluid-handling(storage-tank, pump, angels-storage-tank-3, check-valve, overflow-valve, underflow-valve, iron-pipe-mr, iron-pipe-lr, empty-canister, bob-overflow-valve, bob-topup-valve, bob-storage-tank-all-corners, small-tank)
chemical-science-pack (chemical-science-pack)
ir2-research-1 (lab)
ir2-electronics-1 (tin-cable, copper-board, copper-foil, copper-gate, electronic-circuit, computer-mk1, iron-frame-small, iron-frame-large, sensor)
ir-concrete-1 (concrete, hazard-concrete)
automation-2 (assembling-machine-2, iron-scapper)
ir2-inserters-1 (inserter, long-handed-inserter, slow-filter-inserter)
ir2-iron-motor (iron-motor)
ir2-steel-milestone (steel-mix, steel-ingot, steel-ingot-from-scrap, steel-plate, steel-plate-heavy, steel-gear-wheel, steel-rod, steel-rivet, steel-repair-tool, steel-piston, steel-beam, steel-cable, steel-chest)
ir2-gold-milestone (gold-ingot, gold-crushed, gold-ingot-from-crushed, gold-ingot-from-scrap, gold-cable, gold-foil)
ir2-mining-1 (electric-mining-drill)
plastics (plastic-bar)
oil-processing (oil-refinery, pumpjack, chemical-plant, iron-gas-vent, basic-oil-processing, heavy-oil-cracking, light-oil-cracking, solid-fuel-from-light-oil, solid-fuel-from-petroleum-gas)

stack traceback:
[C]: in function 'error'
__IndustrialRevolution__/code/functions/function-datea.lua:2172: in function 'get_ancestors_of_tech'
__IndustrialRevolution__/code/functions/function-datea.lua:2180: in function 'get_ancestors_of_tech'
__IndustrialRevolution__/code/functions/function-datea.lua:2180: in function 'get_ancestors_of_tech'
__IndustrialRevolution__/code/functions/function-datea.lua:2180: in function 'get_ancestors_of_tech'
__IndustrialRevolution__/code/functions/function-datea.lua:2180: in function 'get_ancestors_of_tech'
__IndustrialRevolution__/code/functions/function-datea.lua:2180: in function 'get_ancestors_of_tech'
...alRevolution__/code/technology/technology-regenerate.lau:101:in main chunk
[C]: in function 'require'
__IndustrialRevolution__/code/technology/technology.lua:35:in main chunk
[C]: in function 'require'
__IndustrialRevolution__/datea-updates.lua:9: in main chunk

Mods to be disabled:
Industrial Revolution (2.1.3) [ ] Reset Mod Settings

**Comment by RepairmanSki** [comment]
> I am running a fairly heavily modded system with Bob's as a core which I am guessing maybe the issue.

Certainly the case as noted in the thrown error "Probable cause: A mod has added an incompatible recipe unlock or technology prerequisite..."

Note the 'compatible mods' section in teh FAQ: https://mods.factorio.com/mod/IndustrialRevolution/faq

**Comment by Deadlock989** [comment]
Bob's mods aren't supported.
