### ISSUE TITLE
Furnace Balance

### ISSUE THREAD

**Issue by dbs4261** [Deadlock989/IndustrialRevolution#290]
During my playthrough of IR3, I have been using Helmod to optimize my base. And I found a strange quirk. The fuel burning furnaces emit the same amount of pollution as their electric counterparts. But, by having fuel pollution modifiers below 100% (coke specifically is 75%), bronze furnaces are strictly better than electric furnaces, if you ignore the potential for modules. This is exacerbated if the electrical power comes from a fossil fuel source. Now, I am on board with efficiency decreasing when using electrical furnaces plus fossil fuel power. However, because of the fuel pollution modifier, using Bronze furnaces fueled with coke is strictly better than using electrical furnaces with solar. I would recommend either re-balancing the pollution modifiers of different fuels so the best fossil fuel is 100% (maybe a bit better for liquid fuels?), or reducing the base pollution of electric furnaces.

[Screenshots](https://imgur.com/a/1pu9fmx)

Factorio Version: 1.1.89 linux64
Industrial Revolution Version: 3.1.5

**Comment by Deadlock989** [comment]
> if you ignore the potential for modules

This would be choosing to ignore the best and most useful feature of electric furnaces, pretty much the reason they exist. You can get energy consumption and pollution emissions down to 20% on electric furnaces by inserting two Efficiency II modules (or finicking some beacon arrangement or other). If your electricity is coming from non-nuclear steam, the consumption efficiency is also passed on to the boilers, so the emissions to run that one furnace are multiplied by whatever bonus the fuel in the boiler has. Coke has 75% emissions, so if the furnace is pulling only 20% power, the furnace itself produces 20% emissions and the fuel consumption adds another 20% x 75% = 15%, making a total of 35%. If you were somehow getting all of your power from ethanol, you could get it down to 30%. If your furnace is running from solar, nuclear or hydrogen, you can run at the literal 20%. Raw coal in the boilers at 100% emissions with maximum efficiency in the furnaces works out at 40% overall. Even that is lower than any burner furnace can achieve, just over half the emissions. 

So the only comparison where a bronze furnace fuelled with coke is "strictly better" than an electric furnace is the one where your electric furnace has either no modules or speed/productivity only. I don't really have a problem with that: electric furnaces are absolutely characterised by their module flexibility and choosing to ignore that (or instead choosing to "overclock" them with speed/prod) should have a consequence. Electric furnaces are also the simplest to supply logistically (no fuel required), which is a benefit you can't really measure in percentage points. 

In vanilla and some other overhaul mods, machines are just straight linear upgrades of each other with no wrinkles, but that wasn't the mod I wanted to make. At any rate, when there's something clearly wrong - and I don't think this is one of those times - if I'm going to change anything at all, I need hard numbers.
