### ISSUE TITLE
Blueprinting Transmats Crash

### ISSUE THREAD

**Issue by darkbrothervs** [Deadlock989/IndustrialRevolution#291]
**Describe the issue**
Tried to create a blueprint that included a named transmat. Before naming didn't seem to have an issue? This is the only transmat I had on the map.

> Error while running event IndustrialRevolution3::on_player_setup_blueprint (ID 70)
> Index out of bounds: 3 > 0.
> stack traceback:
> 	[C]: in function 'set_blueprint_entity_tag'
> 	__IndustrialRevolution3__/code/control/control-events.lua:592: in function <__IndustrialRevolution3__/code/control/control-events.lua:581>

**Factorio version, IR version**
IR 3.1.5
Factorio 1.1.87

**Other mods installed**
Lots of QoL but I don't think they're causing this.

**Comment by darkbrothervs** [comment]
Okay I was able to play with this more and think I can reproduce now. It's not the initial creation of a blueprint that causes an issue, it's altering an existing blueprint. Try these steps:

1. Create a blueprint including a transmat.
2. Put blueprint in blueprint library (didn't test putting in player inventory). 
3. Use blue + button to add new contents to the blueprint and reselect the transmat.
4. Crash, error as listed above.

My save is 1 MB too big to attach -_- I don't know a good way to extract the mod list, so pics attached.

<img width="144" alt="factorio_lahTe5oZ2M" src="https://github.com/Deadlock989/IndustrialRevolution/assets/144298920/e564cfd9-1e7a-41d8-bbc1-cef80da4f1c8">
<img width="146" alt="factorio_UO307gc7TS" src="https://github.com/Deadlock989/IndustrialRevolution/assets/144298920/3f7f3492-9074-4554-a813-76d92f878513">
<img width="150" alt="factorio_v8x0xW1pC4" src="https://github.com/Deadlock989/IndustrialRevolution/assets/144298920/9c966e85-7327-4f5b-a209-e25bec36ac94">
<img width="139" alt="factorio_wYNsNmz5hU" src="https://github.com/Deadlock989/IndustrialRevolution/assets/144298920/c4d74051-5f21-4ab4-9697-28b6a396df22">
<img width="146" alt="factorio_HKAYAm2Pme" src="https://github.com/Deadlock989/IndustrialRevolution/assets/144298920/ac27f101-ed79-43cd-a293-f08377964eae">

**Comment by Deadlock989** [comment]
Thanks, I can reproduce that without third party mods installed. It's not related to the blueprint library. I will investigate this but I'll need to get around to it. In the meantime you can work around it by only creating brand new blueprints for named transmats, i.e. avoid using the blue "Select new contents for the blueprint" button on them.

For future reference you can find a JSON format list of activate mods in a file called `mod-list.json` in your Factorio/mods folder.

**Comment by darkbrothervs** [comment]
It's no big worry, I was actually trying to blueprint the tiles under the transmat :). 

Thank you for your work putting this mod together.

**Comment by Deadlock989** [comment]
It seems this issue is caused by a long-standing bug in the main game which has been left unaddressed for 3 years:

https://forums.factorio.com/viewtopic.php?f=182&t=88100

I can stop the script error from happening, but it seems there is no way to set the entity tag in the blueprint when the "Select new contents" button is used, pending a fix in the main game. So
