### ISSUE TITLE
Blast smelting recipe productivity

### ISSUE THREAD

**Issue by Nebisan** [Deadlock989/IndustrialRevolution#293]
**Describe the issue**
This is of course not a big issue, just a minor inconsistency I have noticed. As the title says, the manifesto says that productivity modules can be used with all the blast smelting recipes, but blast furnaces do not have module slots, and are not affected by beacons either. It is mildly confusing. 

The mod is fantastic. Thank you for making it. It is definitely the most beautiful overhaul out there.

**Factorio version, IR version**
Factorio 1.1.87
IR 3.1.6

**Other mods installed**
Only QOL or visual

**Comment by Deadlock989** [comment]
Well spotted - in 3.0.x versions of the mod, blast furnaces were electric and did have module slots, but the data for their recipes was not updated when they were changed to coke burners.
