### ISSUE TITLE
Mark mod incompatible

### ISSUE THREAD

**Issue by AzaluluDingir** [Deadlock989/IndustrialRevolution#294]
**Describe the issue**
Please mark this mod as incompatible because it is.
https://mods.factorio.com/mod/PoweredFloorExtended

**Factorio version, IR version**
1.1.87
3.1.6

**Other mods installed**
https://mods.factorio.com/mod/PoweredFloorExtended

**Comment by Deadlock989** [comment]
Sorry, no. There are likely hundreds of incompatible mods out there, I only explicitly block the most popular ones that routinely generate work for me.
