### ISSUE TITLE
Transmats crashing when using Beacon Overhaul 

### ISSUE THREAD

**Issue by bennolor** [Deadlock989/IndustrialRevolution#295]
**Describe the issue**
Place at least 2 transmats. 
Teleport
Upon Teleporting a crash happens

**Factorio version, IR version**
IR 3.1.6 Factorio 1.1.87
**Other mods installed**
Beacon Overhaul, Editor Extensions
![factorio_UzVYFo2Kym](https://github.com/Deadlock989/IndustrialRevolution/assets/20340882/86540ea3-3c7d-47e1-acc1-6b71a09acb57)

**Comment by bennolor** [comment]
It works fine with "beacon rebalance", so I switched to that for now, but it might be still worthwhile to either investigate the underlying issue or consider marking beacon overhaul as incompatible especially since the two are so similarly named and beacon rebalance is recommended in the IR3 FAQ.

**Comment by Deadlock989** [comment]
This is a known issue with Beacon Overhaul (#138), that was reported to the author 8 months ago, but has not been addressed at the time of writing. It's not specifically a conflict with IR3, it's a more general mistake in the mod itself.

https://mods.factorio.com/mod/beacon-overhaul/discussion/63ad78955893f143835f4939

**Comment by Deadlock989** [comment]
I have marked this mod as incompatible in the next version.
