### ISSUE TITLE
Incompatible with Micro Furnace 1.0.13

### ISSUE THREAD

**Issue by SirGouki** [Deadlock989/IndustrialRevolution#297]
**Describe the issue**
Industrial Revolution is incompatible with Micro Furnace, but it isn't listed on the description as not compatible.  If Micro Furnace is enabled, Factorio throws an error when loading saying that ir3-furnace- (didn't get the whole name) is unavailable, and mentions the tech furnaces 3.  Factorio only offers to disable IR3 for this, and not micro furnaces as it thinks the problem is with your mod.

**Factorio version, IR version**
Factorio: 1.1.87
IR3: 3.1.7

**Other mods installed**
Micro Furnace (the offender) - disabling this made your mod load
fCPU
Factorissimo 2 (notnotmelon fork)
Companion Drones
Better Energy production
AAI warehouses and containers
Infinite Technologies
Light overhaul
outpost planner for v1.1
planner core for 1.1
Santa's Nixie Tubes
everything in your mod's requirements list, including the optionals.

**Comment by Deadlock989** [comment]
There are likely hundreds of incompatible mods out there, I can't block them all.
