### ISSUE TITLE
Manifesto mistake?

### ISSUE THREAD

**Issue by AzaluluDingir** [Deadlock989/IndustrialRevolution#298]
**Describe the issue**
Manifesto says I can void water but I believe I can't.

**Comment by Deadlock989** [comment]
Screenshot or it didn't happen.

**Comment by AzaluluDingir** [comment]
![Screenshot 2023-09-16 at 20 02 51](https://github.com/Deadlock989/IndustrialRevolution/assets/52681451/b319ae50-5dde-4c8c-abe7-be515ad944da)
![Screenshot 2023-09-16 at 20 55 28](https://github.com/Deadlock989/IndustrialRevolution/assets/52681451/7f14e85d-6767-4d84-ab2a-4cac29979550)

**Comment by Deadlock989** [comment]
You have misunderstood. The line above the list of fluids says "The following fluids are completely safe to flush or vent". The page previously discusses how to flush fluid systems ("The same applies to flushing pipes manually using a pipe's GUI"). You can flush water from any pipe system by selecting the pipe and clicking the delete button. So this is correct.

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/3128845/ea2522f0-409f-4cb9-83fb-23b5f6936318)
