### ISSUE TITLE
Low fuel warning

### ISSUE THREAD

**Issue by AzaluluDingir** [Deadlock989/IndustrialRevolution#299]
When You have multiple fuel types low fuel warning starts to blink when only one type of fuel runs out despite having a full stack of (different) fuel. Notice on screenshot a full stack of copper steam canisters right beside empty stack of iron steam canisters (on hotbar).
![Screenshot 2023-09-17 at 22 03 02](https://github.com/Deadlock989/IndustrialRevolution/assets/52681451/80b1b25f-84d9-4ae4-957a-9f60d9536f66)

**Comment by Deadlock989** [comment]
This is working as intended.

**Comment by AzaluluDingir** [comment]
But it says that I'm low on fuel while I'm clearly not.

**Comment by Deadlock989** [comment]
No, the yellow warning means that you don't have any more of that kind of fuel in your inventory, which is true. If you don't find this warning useful, you can turn it off in player settings.

Please stop raising non-issues and using up my leisure time.
