### ISSUE TITLE
Electric pole upgrade needs the same collision mask - mod compatibility issue

### ISSUE THREAD

**Issue by AlveKatt** [Deadlock989/IndustrialRevolution#30]
Issue is another mod. Seems to be Beautiful Bridge Railway that's messing things up. Error message in screenshot.

![Screenshot at 2021-03-07 09-47-21](https://user-images.githubusercontent.com/38208171/110307517-440ca700-7fff-11eb-81cd-15683102767f.png)

**Comment by Deadlock989** [comment]
BBR changes the collision mask. Not an IR2 issue.
