### ISSUE TITLE
Scrapping loop with train tunnels

### ISSUE THREAD

**Issue by Austin5003** [Deadlock989/IndustrialRevolution#303]
**Describe the issue**
`IR3: Scrap calculator got stuck in a loop while trying to process item traintunnelup.

Most likely cause: another mod has created a cyclical chain of crafting recipes without setting allow_as_intermediate or allow_intermediates to false for at least one recipe in the chain.
stack traceback:
	[C]: in function 'error'
	...evolution3__/code/functions/functions-data-scrapping.lua:58: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...evolution3__/code/functions/functions-data-scrapping.lua:75: in function 'calculate_scraps'
	...ution3__/code/items-fluids-recipes/recipes-scrapping.lua:48: in main chunk
	[C]: in function 'require'
	__IndustrialRevolution3__/data-final-fixes.lua:18: in main chunk`

**Factorio version, IR version**
Factorio: 1.1.91
IR: 3.1.8

**Other mods installed**

- Ammo Loader +
- Black Market 2
- Combat Mechanics Overhaul
- Corrode to Coal
- Industrial Revolution 3 (and assets)
- Miniloader
- Placeables
- Platforms
- Pollution Solutions Lite
- Pushbutton
- Renai Transportation
- Text plates
- Train Tunnels

**Comment by Deadlock989** [comment]
This isn't something I can fix. Looped recipe chains must have a recipe where one of those flags is set or it won't work with IR3 and will have other issues even without IR3 installed. If you're referring to [this mod](https://mods.factorio.com/mod/traintunnels), it hasn't been updated for years and appears to have many other issues, self-describes as "very instable".
