### ISSUE TITLE
supermagnets not affected by beacons?

### ISSUE THREAD

**Issue by i-make-robots** [Deadlock989/IndustrialRevolution#304]
**Describe the issue**
Beacons in range do not add a speed bonus to supermagnets.

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/1464454/8fd1add9-270d-4eb0-841c-fdb275f94307)

**Factorio version, IR version**
base 1.1.92
IR3 3.1.6

**Comment by i-make-robots** [comment]
All supermagnets have crafting speed 1, regardless of beacon proximity.

**Comment by Deadlock989** [comment]
They don't have module slots so they don't support modules regardless of the source. There are several machines like this (e.g. barrelling machines, air compressors, cubic presses).
