### ISSUE TITLE
[Black Rubber Belts] Minor visual issues

### ISSUE THREAD

**Issue by Alex-1248** [Deadlock989/IndustrialRevolution#305]
Factorio 1.1.91
Black Rubber Belts 1.0.3

These problems are not related to IR3. I know this is an IR3 only tracker, but I don't know where I should write about it.

issue 1

When a vertical belt approaches a horizontal belt from above, it covers too much of the top surface of the horizontal belt, while a vertical belt approaching a horizontal belt from below does not cover the top surface of the horizontal belt at all.
![F8](https://github.com/Deadlock989/IndustrialRevolution/assets/114651872/49b4b0a2-50a4-4442-8802-8591277f8004)

By comparison, in vanilla Factorio all the vertical belts slightly cover the top surface of the horizontal belt.
![F1](https://github.com/Deadlock989/IndustrialRevolution/assets/114651872/f162461b-bd64-44e7-9c40-e14fab87c528)

It's not a big problem, but the sight of the top vertical belt significantly blocking the horizontal belt is a little annoying.

issue 2

When the "Coloured rails" option is enabled, the rails of some belts are sometimes drawn on top of other belts.
![F5](https://github.com/Deadlock989/IndustrialRevolution/assets/114651872/4b24fb0f-97a8-426e-a721-056aba4386f7)

The case in the bottom screenshot does not always happen and seems to depend on the location.
![F7](https://github.com/Deadlock989/IndustrialRevolution/assets/114651872/044a4c7a-16a0-48ff-b437-ab4c57a434a3)

issue 3

When the "IR3 material rails" option is enabled, the rails on the vertical versions of copper and iron belts are almost invisible, unlike steel belts. This also makes the holes that form at the bottom of the connection between the horizontal and turning belts more visible.
![F6](https://github.com/Deadlock989/IndustrialRevolution/assets/114651872/1f704323-4494-4715-ba10-d14c73128906)

**Comment by Deadlock989** [comment]
These are very, _very_ minor issues, some of them literally a matter of one pixel. Vanilla belts, and some other things in the vanilla game, also have this level of "problem" if you blow them up to 32x the size they are routinely viewed at. Sorry, but the time/benefit ratio of me spending any more of my free time on this would be unacceptably low.

**Comment by Alex-1248** [comment]
I agree that these are insignificant issues, but I have one last suggestion for the first issue: to make sure that the upper vertical belt is always drawn behind the lower horizontal belt, like the upper right vertical belt in the lower screenshot. It seems to me that it looks better and is better combined with the lower vertical belt. If it is possible to control the order of drawing, then the implementation should not take much time, although I'm not sure.
![F3](https://github.com/Deadlock989/IndustrialRevolution/assets/114651872/0a4f7920-bb06-410c-8dab-7e8d48a13cb6)

**Comment by Deadlock989** [comment]
> If it is possible to control the order of drawing

It is not, for this particular animation on this particular entity type. I [asked for support with this](https://forums.factorio.com/viewtopic.php?f=28&t=99567) and there was no response.
