### ISSUE TITLE
Steam-powered Loaders & Stackers Non-Functional

### ISSUE THREAD

**Issue by afewvowels** [Deadlock989/IndustrialRevolution#307]
**Describe the issue**
I've been playing around with IR3 and I've noticed that the tier 0 steam loaders and stackers don't seem to work. I've tried higher level loaders and stackers that require electricity and they seem to handle loading/unloading from containers and stacking/unstacking items.

**Factorio version, IR version**
Factorio - 1.1
Industrial Revolution 3 - 3.1.8
Industrial Revolution 3: Powered Loaders & Ingot Stacking - 1.0.3

**Other mods installed**
Mini Trains & Early Mini Trains + Compatibility
^^ Seems to be the only other mod I'm running that reallly messes with prototypes and unlocks and such.

**Comment by Deadlock989** [comment]
They do work so I'm predicting that this is going to turn out to be a user error. Otherwise I'll be needing exact reproduction steps, or a saved game with them set up showing how they don't work.

**Comment by afewvowels** [comment]
Ah! You are correct. I was testing using an infinity pipe and the temperature was set at 15C. Cold steam!

Any chance you'll make a full steampunk conversion with like dirigibles and stuff? I'm really enjoying the steam era phase in IR3. The steam pipes remind me of myelin in muscles.

![Factorio 1 1 91 10_5_2023 7_10_50 AM](https://github.com/Deadlock989/IndustrialRevolution/assets/32456218/8d48869b-dda9-43b0-a8ea-58e2402c9d45)
![Factorio 1 1 91 10_5_2023 7_15_00 AM](https://github.com/Deadlock989/IndustrialRevolution/assets/32456218/19ea486f-eb90-4d7d-baf8-2b866a5f8dfc)

**Comment by Deadlock989** [comment]
I have thought about dirigibles - either early-game steam hot air balloons with propellers, or late-game hydrogen/helium zeppelins. But graphics work is hugely time-consuming and realistically this is not something I will get around to soon, if ever.

**Comment by afewvowels** [comment]
For sure. I've been looking into some generative AI for icons and there's some promising stuff. Hopefully they'll get to the point of rendering full 3d models pretty soon. At least in the next decade. I really think Factorio is going to be much bigger than it already is. The fixed perspective and sprite-based nature of the game combined with it's easy to access code should mean we see lots of really goofy and out there things soon.

It's so much fun using it as an excuse to code. Playing this game after learning to do basic OOP is so much different than before. It's amazing playing the game, getting an itch to change something and make it different and just getting under the hood to tweak values and write code to make it happen.

Anyways, after a few days of testing and bashing together mods I think I'm finally ready to start playing IR3, cheers!
