### ISSUE TITLE
Blast furnaces cannot make steel ingots

### ISSUE THREAD

**Issue by Elyviere** [Deadlock989/IndustrialRevolution#311]
**Describe the issue**
Iron ingots cannot be placed in blast furnaces to make steel ingots, see screenshot.
![Blast furnace bug](https://github.com/Deadlock989/IndustrialRevolution/assets/23457506/6ef697cf-89c3-4711-8840-5ab574864693)

**Factorio version, IR version**
Factorio: 1.1.91
IR: 3.1.6

**Other mods installed**
Only recommended QoL mods

**Comment by Deadlock989** [comment]
All of the blast furnace recipes require compressed air. Factorio won't allow loading of solid ingredients into furnace-type entities unless the accompanying fluid ingredient is present. Supplying any amount of compressed air will allow the solid ingredients to be inserted. This is a game engine limitation, I can't do anything about it.
