### ISSUE TITLE
Disallow fast replace of small buffer tank with (underground) pipes

### ISSUE THREAD

**Issue by doktorstick** [Deadlock989/IndustrialRevolution#314]
**Describe the issue**
Don't allow pipes, particularly underground pipes, to replace a small buffer tank. The reason is that the vertical height of the small buffer tank obscures the tile north of it, making it too easy to accidentally replace the small buffer tank with a pipe/underground pipe (wasting liquid, dumping pollution) when the intent is to connect it to the north-side of the buffer tank.

**Factorio version, IR version**
Latest as of 10/21/2023 ~13:50 CST

**Other mods installed**
Too many to type.

**Comment by Deadlock989** [comment]
I will consider this further but the small tanks have been in the mod since 2019 and I've not come across this opinion until now. The cost of doing it would mean that you can't fast-replace a pipe with a tank, which is something I do all the time. If the "height" of the tank is the real issue, I would probably rather address that.

**Comment by Deadlock989** [comment]
I have gone ahead and done this for the next version - I suppose it is not that much of a hassle to right-click deconstruct a pipe while you have a tank to left-click build in the cursor. Both small tanks are now in their own fast-replace group - this means they can fast-replace and upgrade each other, meaning that it's possible to spill pollution if you replace an iron tank with a steam tank, but this is difficult to do by accident (no default upgrade path is set).

I'm not ruling out changing the tank sprite and reverting this change in future but it feels unlikely to happen.
