### ISSUE TITLE
An electric arc turret is causing power problems

### ISSUE THREAD

**Issue by Alex-1248** [Deadlock989/IndustrialRevolution#316]
**Describe the issue**
An electric arc turret causes power problems for other buildings on the same power grid at the time of installation. It appears to have no electrical input limit.

**Factorio version, IR version**
    1.1.91, 3.1.8

**Comment by Deadlock989** [comment]
Fixed for next version. The fix in #104 wasn't being applied to arc turrets because I fixed the laser turret input limit but wrongly thought that arc turrets were set up to inherit the same energy source properties.
