### ISSUE TITLE
Suggestion: Small Assembler distinction

### ISSUE THREAD

**Issue by mussii** [Deadlock989/IndustrialRevolution#318]
**Describe the issue**
Maybe it is my monitor or my color settings but I find _hard_ to quickly distinguish between **Small electric assemblers** and the **Small advanced assemblers**. 

For the other machines e.g. assemblers, crushers... it is super clear. I can see that the same colour logic  is also applied to the small assemblers but the difference is much more subtle and at least for me it is quite harder to tell which _version_ I have of the small ones while I hover over my base.

See picture 

![imagen](https://github.com/Deadlock989/IndustrialRevolution/assets/27778442/be2b86a1-4592-4647-ae48-fb74c3c7c790)

Thank you for this great mod. 

**Factorio version, IR version**
IR3 3.1.8

**Comment by Deadlock989** [comment]
I agree, it was a quick retextured clone and there aren't enough pixels available for that to be distinct, I just haven't had time to address it. It's on my to-do list to revamp all of the small assemblers (and the stackers from the Loaders & Stacking add-on) so there is a bit more surface area to put gubbinses on, but it will be a while before I get round to it.

**Comment by Deadlock989** [comment]
These have been improved for the next version (3.1.10), all three small assemblers all now follow the same rectangular footprint as the stackers from the Loaders & Stacking add-on, but they fill the tile better and align with other entities more nicely, and there is more surface area for the yellow and blue of tiers 2 and 3 to stand out.
