### ISSUE TITLE
Assets that look like air filters

### ISSUE THREAD

**Issue by AngledLuffa** [Deadlock989/IndustrialRevolution#32]
Do you have any interest in adding a couple art assets for air pollution removing machines?  I've been playing two separate games - one long running game where I added the better-air-filtering mod, and another one I recently started of IR2.  I was thinking that I could adjust the filter recipes to take into account the intermediates in IR2, but it would also be nice to have some machines that fit the overall theme of the IR2 visuals.

https://mods.factorio.com/mod/better-air-filtering

**Comment by Deadlock989** [comment]
I'm not sure I understand this request. The mod already has two kinds of pollution reducing machines - forestries and air purification towers.

![image](https://user-images.githubusercontent.com/3128845/110538588-1a956d80-811c-11eb-9e52-cdfd13774dba.png)

**Comment by AngledLuffa** [comment]
Hah, we had just gotten to blue science in the IR2 game I'm playing.  Had not yet seen the air purification.  Thanks for the patient response.

Great mod, btw.
