### ISSUE TITLE
Sprite and icon improvement candidates

### ISSUE THREAD

**Issue by Deadlock989** [Deadlock989/IndustrialRevolution#320]
**Describe the issue**
List of entity sprites and/or their icons in need of more visual distinction, or aren't up to the same standard as other things. You can suggest other candidates if you like and I will take a look.

Priority:

- [x] Small assembler sprites (hard to tell tier 2 and 3 apart, not tile/pipe aligned all that well)
- [ ] Barrelling machine, steam pipe interface - never liked them, ~~steam version also has wrong pipe cover~~
- [x] Copper boiler sprite (missing feet, steam output pipe is wrong type and has wrong cover) 
- [x] Crushed ore icons
- [x] Long handed steam inserter arms (same colour as the other steam inserter, hard to see against pipe/arms tangle)
- [x] Repair kits

Not a priority:

- [x] Steam inserter icons
- [ ] Powder icons
- [ ] Sulphur icon
- [ ] Battery chargers - insanely huge 5 foot batteries - because it was scaled up from a 2x2 design
- [ ] Supermagnet - not happy with it
- [x] Steel wall gate patch - red/green diodes are several pixels off

**Factorio version, IR version**
1.1.91+, 3.1.8+

**Other mods installed**
n/a

**Comment by Cadams111** [comment]
The sulfur icons from IR2 were cool and now they’re the vanilla ones again, if you’ve still got the old ones around it should be easy to swap them out, right?

**Comment by Deadlock989** [comment]
The most needed cases have been addressed in the last few versions but I don't see myself reaching the other candidates for some time. Closing for now, may re-open later.
