### ISSUE TITLE
Transfer plates don't work when there is a container containing items and another container set with filters of said item. 

### ISSUE THREAD

**Issue by ajklotz** [Deadlock989/IndustrialRevolution#322]
**Describe the issue**
If I place a transfer plate down and place two tin pallets down: 1 filled with copper plates and the other empty set with 3 copper plate filters (reserved slots), while having filters in the engineer inventory, triggering the transfer plate does not move items from one chest to another. 

My expectation was that the tin pallet containing copper plates would PUSH to my character, and then the container with the filters would PULL from my engineer to satisfy the transfer. 

**Factorio version, IR version**
1.1.94 and the IR 3.1.8

**Comment by Deadlock989** [comment]
That isn't how it's meant to work.

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/3128845/f3d2064f-803e-4504-bb7d-64eb1d2eb46f)

Containers don't push or pull. Only your inventory pushes and pulls. If a container has the same filters as your inventory, the filters in your inventory are disregarded. I experimented with alternatives to this during development and generally they created problems. Inventory transfers are all about QOL for your character until you get logistic robots. They are not meant to shift things from chest to chest. You can use an inserter for that.
