### ISSUE TITLE
IR3 has detected a cyclical dependency in the technology tree.

### ISSUE THREAD

**Issue by kuxynator** [Deadlock989/IndustrialRevolution#323]
Guru meditation error: IR3 has detected a cyclical dependency in the technology tree.
Probable cause: a vanilla or IR3 recipe/technology has been changed so that recipe A depends on item B but recipe B depends on item A.

ir-iron-milestone [ir-grinding-1, ir-bronze-furnace, ir-bronze-milestone, ir-glass-milestone] (iron-ingot, iron-ingot-from-scrap, iron-plate, iron-plate-heavy, iron-gear-wheel, iron-stick, iron-rivet, iron-piston, iron-pellet, iron-beam, iron-frame-small, repair-pack, iron-chest, pipe, pipe-to-ground, pipe-to-ground-short, valve, offshore-pump, logistic-science-pack)
ir-grinding-1 [logistics, automation, ir-charcoal] (copper-grinder, gravel, silica, carbon-crushed, copper-crushed, copper-ingot-from-crushed, tin-crushed, tin-ingot-from-crushed, wood-chips, rubber, charcoal-from-scrap)
automation [ir-iron-milestone] (assembling-machine-1, long-slim-inserter, long-double-slim-inserter, small-assembler-1, steam-barrelling-machine, empty-cell, fill-steam-cell, empty-steam-cell)
ir-iron-milestone [ir-grinding-1, ir-bronze-furnace, ir-bronze-milestone, ir-glass-milestone] (iron-ingot, iron-ingot-from-scrap, iron-plate, iron-plate-heavy, iron-gear-wheel, iron-stick, iron-rivet, iron-piston, iron-pellet, iron-beam, iron-frame-small, repair-pack, iron-chest, pipe, pipe-to-ground, pipe-to-ground-short, valve, offshore-pump, logistic-science-pack)

stack traceback:
        [C]: in function 'error'
        ...volution3__/code/functions/functions-data-technology.lua:314: in function 'get_ancestors_of_tech'
        
The listed technologoies above are only from IR3.        
How do you find the real dependency that causes this?

**Comment by Deadlock989** [comment]
There is no easy way. Many modders asked over several years for a way of tracking which mods alter prototypes in the data stage so that we can debug issues like this. Eventually we got it for runtime only.

 I don't know what a long slim or long double slim inserter is, those look like the culprits to me. Automation 1 is a very early tech but if it's chaining to ir-iron-milestone then there must be a recipe in there that has iron components, which is creating the circle.

**Comment by kuxynator** [comment]
i have disabled all slim inserters and add them now step bey step.
interesting thing is, that only long-slim-inserter, long-double-slim-inserter, are listed. these two, which I never use.
if I add the all slim-inserters in data-updates into "ir-inserters-1/2/3" and not in data into automation, this seems to work.

**Comment by Deadlock989** [comment]
IR3 runs its technology tree generator in data-updates, so if your mod is changing recipe unlocks in either vanilla or IR3 technologies and you have specified a hard dependency on IR3, you can do it in your data-updates or data-final-fixes. If you don't have a dependency then you can only do it in data-final-fixes.

However there are also flags and options available to you which change the way the tech tree generator handles technology and recipe prototypes - see code/technology/technology-regenerate.lua for a bit of help.
