### ISSUE TITLE
Additional prerequisites are added unexpectedly

### ISSUE THREAD

**Issue by kuxynator** [Deadlock989/IndustrialRevolution#324]
If I add a new technology (in data-updates) which requires  only logistics and the recipe requires iron-plates, why are so many more unnecessary technologies being added? ir-inserters-2 or ir-steel-milestoe  does not makes sense for me. ir-ironmilestone makes more sense because the recipes requires it, but it would work without, the recipe would only be displayed too early.  How can this be prevented? Removing all these unwanted references in data-final-fixes is unnecessary work and I want to at least understand why I have to do them ;-)
![image](https://github.com/Deadlock989/IndustrialRevolution/assets/66268429/be78c9a3-2413-49d7-acac-0890f4fb9b50)

**Comment by Deadlock989** [comment]
If this is a brand new technology then IR3 won't touch it. If you're overwriting a vanilla or IR3 technology then IR3 will touch it heavily. If you've got a dependency on IR3 and you're doing this in data-updates or later then it isn't IR3 doing this.

I can't help without more detail about this new technology: please post the prototype inside code tags.

**Comment by kuxynator** [comment]
you've already helped. thanks for the super-fast reply. 
in my mod I found "forgotten" old logic in it which add vanilla technologies (which no longer exist) and your mod converts them into the new technologies instead to assert, than these old could not be found, what I have expected.  I have to base check the technology and requirements for all of my mods more thorough before they can be used in IR3. and not simply wait for errors.
so thanks you very much for your time.
