### ISSUE TITLE
Transfer plate voids items from if container gets newly configured filters

### ISSUE THREAD

**Issue by ajklotz** [Deadlock989/IndustrialRevolution#327]
**Describe the issue**
I have an iron outpost that used a transfer plate to transfer crushed coal to feed the outpost boilers. When I finally started making coke, I came to the outpost and reconfigured the chest that had crushed coal filter and set it to coke while it still had a full chest of crushed coal. When my vehicle ran over the transfer plate, all the coke was taken out of the vehicle and I saw animations that appeared as if coke was transferring to the already full container, all the coke disappeared from my vehicle. 

https://streamable.com/1ib8lx

**Factorio version, IR version**
1.1.94 and the IR 3.1.8

**Other mods installed**

**Comment by Deadlock989** [comment]
Thanks for the report. There was an omission in the item transfer logic - it wasn't accounting for the possibility that an inventory slot might be filtered for one thing but contains another thing. This wasn't something you could easily arrange when item transfers were first drafted (you can't middle-click-filter a filled slot with anything other than the thing in it), but the set-all-filters sidebar (added later) now makes it trivial to do. This is fixed for the next version.

**Comment by Deadlock989** [comment]
Also, transfer plate is a better name for them.
