### ISSUE TITLE
Explosive rocket recipe requires 8 rockets - might be incorrect

### ISSUE THREAD

**Issue by Soul-Burn** [Deadlock989/IndustrialRevolution#33]
When compared with the explosive cannon shell recipe of 1 shell + 4 explosives 
Or the vanilla explosive rocket recipe of 1 rocket + 2 explosives

If this is as intended, it's easy enough for me to mod it locally.

**Comment by Deadlock989** [comment]
It's not intended - I think the 8 is supposed to be the crafting time modifier.
