### ISSUE TITLE
Ore washing plant does not accept crushed copper ore

### ISSUE THREAD

**Issue by hollowstrawberry** [Deadlock989/IndustrialRevolution#333]
**Describe the issue**

I've tried breaking and placing the buildings again, crafting new buildings, etc. Can't get it to work. Worked fine with iron, until some machines stopped accepting iron too.

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/33796679/5dad8c2b-b876-4ab7-9dfc-5aafcffe30a6)

**Factorio version, IR version**
Factorio build 61774 win64, IR version 3.1.11

**Other mods installed**
base, AutoDeconstruct, Automatic_Train_Painter, belt-visualizer, Better-TrainHorn, calculator-ui, CleanFloor, CopyPasteModules, DeadlockBlackRubberBelts, DeadlockLargerLamp, Enhanced_Map_Colors, EpicArtillerySounds, even-distribution, EvoGUI, factoryplanner, FactorySearch, FilterChests, flib, FuelTrainStop, GhostInHand, GUI_Unifyer, IndustrialRevolution3, IndustrialRevolution3Assets1, IndustrialRevolution3Assets2, IndustrialRevolution3Assets3, IndustrialRevolution3Assets4, IndustrialRevolution3LoadersStacking, IndustrialRevolution3SpaceMining, Milestones, MushroomCloud, PipeVisualizer, RateCalculator, Realistic_Heat_Glow, RecipeBook, Shortcuts-ick, simple-qol, solar-calc, StatsGui, StatsGui-HandcraftTimer, stdlib, UltimateResearchQueue

**Comment by ArmoredReaper** [comment]
Was able to reproduce the issue. Electric ore washers don't accept any ore input if they don't have water. If that's the intended behaviour then the item or the mod doesn't make it clear.

**Comment by hollowstrawberry** [comment]
Yes, it was the water, thank you. I'll leave the issue open until it's reviewed just in case.

**Comment by Deadlock989** [comment]
This is just how Factorio treats recipes in furnace-type entities (auto-selecting crafting machines) if there is a fluid ingredient. Same issue as #311.
