### ISSUE TITLE
Not an issue, requesting to use an IR2 asset for an add-on mod

### ISSUE THREAD

**Issue by the-clorax** [Deadlock989/IndustrialRevolution#334]
I would like to use the animations and sounds for the IR2 incinerator to be used in a variant of bio industries for IR3 players. This variant of the mod will use an incinerator and electric furnace/coke kiln to do the things that a cokery normally does (making ash and charcoal) in bio industries.

**Comment by Deadlock989** [comment]
Permission granted.
