### ISSUE TITLE
Potential version mismatch(?) between latest update and assets

### ISSUE THREAD

**Issue by dhasial** [Deadlock989/IndustrialRevolution#342]
**Describe the issue**
I manually (I know) installed all the bits of IR3 according to the dependency list found at the [mod portal's download section](https://mods.factorio.com/mod/IndustrialRevolution3/downloads). However, when actually loading into Factorio, IR3 and the asset packs are red and all appear to have some issue I believe to be a dependency version mismatch, but I'm honestly not certain.

The mod also doesn't appear to load any content (e.g. no info in Informatron, no recipes, etc.)

**Factorio version, IR version**
Factorio version: 1.1.94
IR3 version: 3.1.12
IR3 asset pack 1: 1.1.6
IR3 asset pack 2: 1.1.0
IR3 asset pack 3: 1.1.5
IR3 asset pack 4: 1.1.0

Relevant screenshots of the mod screen
![2023-11-26-033647_screenshot-MEPLEASE](https://github.com/Deadlock989/IndustrialRevolution/assets/44693166/78ed58dc-c362-4905-8a74-334c5c5c7896)
![2023-11-26-033653_screenshot-MEPLEASE](https://github.com/Deadlock989/IndustrialRevolution/assets/44693166/e69b37ac-7dd6-4ec8-8710-3f85e2dd5dc0)
![2023-11-26-033629_screenshot-MEPLEASE](https://github.com/Deadlock989/IndustrialRevolution/assets/44693166/f83640cb-97fe-4164-8ec5-ae364155fc43)
![2023-11-26-033635_screenshot-MEPLEASE](https://github.com/Deadlock989/IndustrialRevolution/assets/44693166/e071089e-cbbe-4121-bcf6-9f552f45857d)

**Other mods installed**
[mod list gist](https://gist.github.com/dhasial/ab88f969bedd0ce91da8d1ac00e2f1b5)

**Comment by Deadlock989** [comment]
You have at least one mod installed that IR3 marks as incompatible (deadlock-beltboxes-loaders), possibly others.

**Comment by dhasial** [comment]
Thanks for the feedback, I finally got it working. For reference (in case you want to add them to the incompatible mods list), the incompatible mod's IDs were:

LightedPolesPlus
deadlock-beltboxes-loaders
electric-furnaces-fork-complex
Air-Filtering_Fix
