### ISSUE TITLE
Does AAI Containers & Warehouses no longer work?

### ISSUE THREAD

**Issue by 5knnbdwm** [Deadlock989/IndustrialRevolution#343]
**Describe the issue**
In the FAQ of IR3 it states that AAI Containers & Warehouses are supported, however with adjustments made my IR3.
However currently AAI Containers & Warehouses is in the "Incompatible with" list of IR3.

**Factorio version, IR version**
Factorio: 1.1.94 (build 61774, win64)
IR3: 3.1.12

**Other mods installed**
AAI: 0.2.11

**Comment by Deadlock989** [comment]
I don't know why this is happening for you or exactly what you mean. AAI Containers & Warehouses is definitely supported by IR3 (recipe adjustments only). It is not on the incompatible list, which you can check [here](https://mods.factorio.com/mod/IndustrialRevolution3/downloads) and/or by inspecting the info.json file in the root folder of the main IR3 mod.

**Comment by 5knnbdwm** [comment]
Hey, yeah just rechecked and yes you are right it is working for me. Can't explain what happened but I'm 100% sure (as i remember that i switched the icon size) that I installed AAI Containers & Warehouses and not Industries.
