### ISSUE TITLE
Steam machines can't be flipped in blueprints

### ISSUE THREAD

**Issue by xykite** [Deadlock989/IndustrialRevolution#35]
None of steam inserter, long-handed steam inserter, assembler, crusher, mixer, lab can be flipped, despite having the requisite symmetry.

(all of burner drill, bronze furnace, offshore pump, copper pipes all _can_ be flipped so I guess it's to do with fluid inputs).

Game 1.1.27 / IR 2.1.3 / no other mods

**Comment by Deadlock989** [comment]
What those entities have in common is not that they have fluid inputs but that they are non-generator entities that have fluid energy sources. Blueprint flipping was added in 1.1 experimental but fluid energy sources existed long before that. 

There isn't currently any meaningful change I'm aware of which can fix this. Essentially I see this as a base game issue. Fluid energy sources are not used by the vanilla game for non-generators, which may be why it was never picked up before.
