### ISSUE TITLE
Failed to load - cyclical dependency error

### ISSUE THREAD

**Issue by BTAnthony** [Deadlock989/IndustrialRevolution#353]
Both the latest and previous versions (3.1.12 and 3.1.13) shows an error when trying to load it. See attached image for details. I'm not running any incompatible mods.

![ir3error](https://github.com/Deadlock989/IndustrialRevolution/assets/153691183/b56c2a72-ec01-4341-8557-38d7e35ac39a)

**Comment by Deadlock989** [comment]
As it says, you have some other mod installed that changes the recipe content of vanilla technologies in a way that makes them incompatible with IR3. You will have to raise it with the other mod author. I recognise "long-slim-inserter" from these support requests: #324 #323
