### ISSUE TITLE
Loading error - function "final_recipes_pass"

### ISSUE THREAD

**Issue by BTAnthony** [Deadlock989/IndustrialRevolution#354]
I started a new IR3 game, then exited out to turn off a "no handcrafting" mod. Now I keep getting this wierd loading error that I can't explain...

![ir3error2](https://github.com/Deadlock989/IndustrialRevolution/assets/153691183/511c7c7a-c010-4a64-9276-8c43961199aa)

To me, it looks like something within IR3 itself and not an incompatibility with some other mod.

**Comment by Deadlock989** [comment]
The issue report form asked you to list other mods installed and confirm version numbers. If you don't supply the information I need, nothing is going to happen.

**Comment by BTAnthony** [comment]
All these are their latest versions.

big lab fork 0.0.4
cable making 1.4.2
flare stack 2.2.10
sonaxaton infinite resources 0.4.8
vehiclesnap 1.18.5
automatic underground pipe connectors 1.1.3
better poles 0.0.6
big storage tank 0.0.10
efficient smelting 0.0.18
electric boiler 1.1.0
factorio reach 2.7.1
fluid must flow 1.3.5
FNEI 0.4.1
helmod 0.12.19
IR3 3.1.13
IR3 assets 1 1.1.6
IR3 assets 2 1.1.0
IR3 assets 3 1.1.5
IR3 assets 4 1.1.0
no crafting time 0.0.3
ore eraser continued 1.5.6
pump anywhere 0.1.10
quality of life 0.0.4
schall remains pickup 1.1.1
always day 2.1.1
long reach 2.1.1
ultimate belts 1.1.1
ultimate energy 0.0.4
warehousing 0.5.7
bottleneck lite 1.2.8
even distribution lite 1.3.0
miniloader 1.15.7
nanobots early bots 3.2.19
ultra fast magnetic inserter extra 0.1.6

**Comment by Deadlock989** [comment]
Fixed for next version.
