### ISSUE TITLE
Steam fissures are self-renewable.

### ISSUE THREAD

**Issue by Hanczar666** [Deadlock989/IndustrialRevolution#355]
**Describe the issue**
In my current play(and first time IR3) there is steam-fissure (with steam-derrick on it) near start location with initial output of 60 steam/s (as described in expected resources). It gradually depleted to around 6 steam/s then it starts giving 60 steam/s again and then decreasing output again. Such cycle repeated already 3 times in my play (~15hours). I think it should behave like oil patches in vanilla and remain on low output value after reaching it.

**Factorio version, IR version**
Factorio: 1.1.100 (build 61920, linux64)
IR: 3.1.14

**Other mods installed**
Space extension mods (Feoras Fork) 1.2.9
Remote Configuration 1.2.4
Mini Trains 1.0.0
Milestones 1.3.20
Larger Lamps 1.5.1
Industrial Carbo Ships, Dectorio, Even More Text Plates, Black Rubber Belts

**Comment by Deadlock989** [comment]
No, this is intentional and was scripted deliberately. Fissures are described in the Manifesto documentation as "cyclic".

**Comment by Hanczar666** [comment]
My bad, I read whole manifesto before placing this issue, but somehow missed this part about cyclic nature of steam-fissure which of course there is under resource section (although this cyclic behaviour is a bit strange for me). Sorry for bothering and thank you very much for this amazing mod.
