### ISSUE TITLE
Airships Alpha (0.1.0) Crash on selecting airport

### ISSUE THREAD

**Issue by dkohlbre** [Deadlock989/IndustrialRevolution#356]
**Describe the issue**
When opening the gui for an airport in freeplay mode, I'm getting a crash ~50% of the time:

```
The mod Industrial Revolution 3: Airships (alpha) (0.1.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event IndustrialRevolution3Airships::ir3a-open-gui (ID 195)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__index'
	...evolution3Airships__/code/functions/control-stations.lua:1028: in function 'create_station_gui'
	__IndustrialRevolution3Airships__/control.lua:103: in function <__IndustrialRevolution3Airships__/control.lua:98>
```

**Reproduction Steps**
Start freeplay, all default settings. Enable all tech-day-etc.
Build 3-4 airports near each other, spawn an airship (unsure if required).
Select an airport.
~50% of the time the airport UI appears, ~50% of the time I get the crash above.
May be related to building the airport and selecting it quickly? Unsure.

**Factorio version, IR version**
Factorio 1.1.100 (build 61920, win64)
IR3 3.1.14
IR3: Airships (alpha) 0.1.0
IR3 Assets 1: 1.1.7
IR3 Assets 2: 1.1.1
IR3 Assets 3: 1.1.6
IR3 Assets 4: 1.1.0

**Other mods installed**
I am running no other mods.

**Comment by Deadlock989** [comment]
I'm not able to replicate this from the steps provided - I always get the GUI opened successfully without errors. 

Are you able to provide a small save file with the buggy stations already set up?

If I can't reproduce it I can still add some additional validation, but I'm surprised to get an error at that line and would like to understand how it is happening.

**Comment by dkohlbre** [comment]
Of course I can no longer reproduce to get a save :)
I was able when I filed the issue to get it to occur in about 50% of new sandbox games I started, again with no other mods loaded.
Following the same steps is no longer causing crashes.

More context if its helpful:
I use an ultrawide monitor
I had a number of other mods loaded initially, then progressively unloaded them (without fully quitting factorio, just letting it do the usual load/unload process) to narrow it down.

I'll try and get the exact same conditions in terms of mods loaded when started, then unloading those mods, then seeing if that can reproduce.

**Comment by dkohlbre** [comment]
No luck. I'll update this issue if I can produce a save.
Sorry if this turns out to be entirely non-reproducible, except for that 10 minute window!

**Comment by Deadlock989** [comment]
I'm really uncertain about how this might have happened, especially given that it didn't always happen to begin with and then couldn't be reproduced after other mods were removed. All I can think of is that some other mod was interfering with the station GUI. I can add some validation to the code segment responsible for the reported error but that would result in stations sometimes not opening their GUI so I'd prefer to understand why this happened before I make changes. 

- Were there any other mod GUIs open at the time you opened the station?
- Was editor mode involved?

Otherwise I'll leave this open for a week or so in case anyone else can reproduce it.

**Comment by Kaimdrol** [comment]
It happened to me too. I think I found how to reproduce :

- put a station on the ground
- open another GUI : player, airship, spidertron, chest, locomotive, electric network info, production, constant combinator, assembler/crusher/etc, ...
- with that GUI open, click the station
- crash every time for me

Clicking from a station to another station doesn't crash.
I also have an ultrawide but it crashes on the secondary regular monitor too.

**Comment by Deadlock989** [comment]
Thanks, I can reproduce that. There was a crucial missing line in the GUI creation script. Fixed for next version.
