### ISSUE TITLE
Rubber trees not spawning with Alien Biomes is a quick and easy fix

### ISSUE THREAD

**Issue by Barerock** [Deadlock989/IndustrialRevolution#357]
Since github is where I looked to discover this issue and preemptively fix it, I'll put this here so others can find it in a quick google search.

You can fix the trees not spawning (being overwritten) with Alien Biomes by adding IR3 and its dependencies to the dependencies list of Alien Biomes. This works because dependencies are always loaded FIRST, and thus Alien Biomes' system for replacing all flora skips over IR3's rubber trees. I have confirmed that both mods are working and I am looking at a cluster of rubber trees right now in a new map!

Setting is found in info.json in the Factorio mod directory in your Roaming folder, which can be located via the route: %appdata%\factorio\mods\

Simply copy paste IR3 dependencies AND the IR3 title, all documented in its info.json, into the dependency field for Alien Biomes.

Syntax:
{
    ...,
    "dependencies": ["mod_to_load_earlier"]
}

Thanks, Deadlock, for the cool mod, I am just starting it with the Rampant mod and some settings courtesy of King Adam XVII on YouTube.

**Comment by Barerock** [comment]
Correction: I have NOW made it work, IR3 needs to be listed as "IndustrialRevolution3 >= 3.1.14"

For whatever reason, the info.json has issues if there isn't a version attached, and also make sure to write changes to the archive correctly. Sometimes 7zip decides it just won't, so make sure you either have an external you overwrite it with or get the prompt to update the archive. To check if Alien Biomes loads, check your mod list; it will show up red if the json file is incorrect.

Cheers, am looking at some weird trees and purple grass and a bunch of rubber trees rn, so I can confirm it absolutely works.

**Comment by Deadlock989** [comment]
There is a long background to this, due to the not entirely intuitive way that Factorio handles mod loading order in the absence of any dependencies. Last year AB improved the way it handles IR3 rubber trees ([e.g.](https://github.com/EarendelDevelopers/factorio-mods/issues/250)) but you're probably right that the best way to guarantee that it doesn't wipe out rubber along with every other tree type is to add a dependency.
