### ISSUE TITLE
Zero fluid ingredient crash on startup (Factorio experimental branch)

### ISSUE THREAD

**Issue by AvengerStar** [Deadlock989/IndustrialRevolution#358]
**Describe the issue**
A change made just today to Factorio's modding API disallows fluid ingredients that are zero, which causes a crash on startup related to the forestry's fertilizer. There may be other failure points, but this is the one that immediately shows up on boot. 

**Factorio version, IR version**
Factorio 1.1.101
IndustrialRevolution3 3.1.14

**Other mods installed**
Happens with no other mods installed.

**Comment by SteveVaneeckhout** [comment]
Same problem, this is what I see in the logfile:
> Error ModManager.cpp:1625: Error while loading recipe prototype "forestry-wood-fertiliser-00" (recipe): Difficulty normal: amount must be larger than 0 in property tree at ROOT.recipe.forestry-wood-fertiliser-00.ingredients[1]
> Modifications: Industrial Revolution 3

**Comment by DIDoS** [comment]
Release Notes [Version 1.1.101](https://forums.factorio.com/viewtopic.php?f=3&t=110371) say: "
  Modding:
    - Fluid ingredient amounts must be larger than zero."

**Comment by Deadlock989** [comment]
Thanks for the heads-up. Obviously I wasn't expecting Wube to release a breaking API change on a public holiday ... I will address this as soon as I can, but in general I don't recommend using the Factorio experimental branch for regular play, there have been more issues with it in recent months than there used to be.
