### ISSUE TITLE
Crashed on v1.1.101

### ISSUE THREAD

**Issue by quandhz** [Deadlock989/IndustrialRevolution#360]
**Describe the issue**
![Screenshot 2023-12-27 115810](https://github.com/Deadlock989/IndustrialRevolution/assets/15902179/edc234f8-d5d7-4193-b6e1-8961a5313638)

**Factorio version, IR version**
Factorio: 1.1.101
IR3: 3.1.14

**Comment by quandhz** [comment]
Duplicate

**Comment by Deadlock989** [comment]
Duplicate of #358
