### ISSUE TITLE
Airships (0.1.2) stations lose destinations

### ISSUE THREAD

**Issue by doktorstick** [Deadlock989/IndustrialRevolution#368]
I noticed that when I added a third airship station it didn't have any available stations in the in the forwarding section. When I checked on my other two, they also no longer had their two configured stations.

I loaded up Editor Extensions and recreated a similar problem. The order I did this matched what I remembered doing in game, but without all the fiddling around and extra details when figuring out the mod.

1. Create station
2. Create station
3. Add forwarding station from (2) to (1)
4. Add forwarding station from (1) to (2)
5. Rename station (2) to "Cells"
6. Rename station (1) to "Mall"
7. Create station
8. Observe station (7) has no forwarding destinations other than "Circle and return"
9. Observe station "Mall" has forwarding destination unset to "No destination" and only "Unnamed station (13m)" (station (7)) as a station option
10. Observe station "Cell" has forwarding destination unset to "No destination" and only "Unnamed station (7m)" (station (7)) as a station option

**Factorio version**: 1.1.101
**IR version**: 3.1.16 (base); 0.1.2 (airships)

**Other mods installed**: A lot

**Comment by Deadlock989** [comment]
I noted a similar issue earlier, clearly a result of rushing #364.

**Comment by Deadlock989** [comment]
This is fixed in Airships 0.1.3 - destinations set in previous versions seem to be preserved. Been making a lot mistakes this week, I blame the sherry.
