### ISSUE TITLE
Airships - Sound Effect(s)

### ISSUE THREAD

**Issue by RepairmanSki** [Deadlock989/IndustrialRevolution#371]
Spidertron "walking" sound plays when airship moves.

Factorio - 1.1.X (Current Beta)
IR - 3.1.16
Airships - 0.1.4

**Comment by Deadlock989** [comment]
Can't reproduce. Airship entities are built from scratch and they don't reference vanilla sounds anywhere at all. Please list your other installed mods and give the Factorio version.

**Comment by RepairmanSki** [comment]
Current modlist:
base
AlertsList2
AutoDeconstruct
blueprint-sandboxes
blueprint_flip_and_turn
ChangeMapSettings
CleanFloor
Constructron-Continued
DeadlockBlackRubberBelts
even-distribution
factoryplanner
flib
IndustrialRevolution3
IndustrialRevolution3Airships
IndustrialRevolution3Assets1
IndustrialRevolution3Assets2
IndustrialRevolution3Assets3
IndustrialRevolution3Assets4
IndustrialRevolution3LoadersStacking
IndustrialRevolution3SpaceMining
MaxRateCalculator
Milestones
ModuleInserterER
no-wall-repair
PickerDollies
RecipeBook
RemoteConfiguration
rewire-tool
so_as_red_and_green
spidertron-control-center
stdlib
TaskList
ThickerLines
Train_Control_Signals


Factorio version  - 1.1.101

There is a specific volume setting for walking sounds. perhaps yours is off/low? Here's a clip of the sound:
https://www.loom.com/share/75ff7323706f4289a517fb75e73b9c47

**Comment by Deadlock989** [comment]
Yes, I had it turned down low, and it's a quiet sound already on some tiles. It turns out that although spider legs don't have any definitions for walking sounds, sounds are played anyway, presumably derived from tile properties. But there is an optional volume modifier property which I have set to 0 for the next version.
