### ISSUE TITLE
[Question] How would I go about changing the faction of Big Wooden Pole to neutral to disable Rampant AI from targeting them?

### ISSUE THREAD

**Issue by Barerock** [Deadlock989/IndustrialRevolution#379]
I've found the entities-power.lua, but I have absolutely 0 knowledge of Factorio lua language and near nothing of lua in general. I see the flags entry and note that "placeable-neutral" and "player-creation" are there, which might mean I can remove "player-creation" to disable player faction assignment upon placement?

Idk, it'd be awesome to get a good answer, since Veden seems to have abandoned the only similar issue in their Github.

**Comment by Barerock** [comment]
No, removing "player-creation" doesn't change the faction or any function as far as I can see. Biters still destroyed them when attacked.

**Comment by Barerock** [comment]
I am seeing if factorio lua resource can help me effectively. I will update when I figure it out.

**Comment by Barerock** [comment]
It seems like "player-creation" being deleted should have had some effect, and most likely did. The resource states that that string enables the distraction capability, and I noted that biters didn't immediately attack any poles, only after being shot at did they destroy all three types.

**Comment by Barerock** [comment]
Yeah, after looking through this stuff I definitely can see that what I want is possible, but I have no idea how or where to implement it lol. Help would be appreciated :)

**Comment by Deadlock989** [comment]
Those flags are only to do with editor mode according to the [documentation](https://lua-api.factorio.com/latest/types/EntityPrototypeFlags.html). 

There is no concept of "faction" in Factorio. It does have the concept of forces, but power poles built by the player will always have the player force unless some mod changes that with scripts (IR3 does not). The vanilla biter AI typically ignores entities unless they have the [is_military_target](https://lua-api.factorio.com/latest/prototypes/EntityWithOwnerPrototype.html#is_military_target) property set to true - for most entities the default is false. But Rampant might or might not respect that property, I don't know - if these attacks are scripted then biters will do whatever Rampant is telling them to do. 

I can't advise further as I don't know anything about Rampant.

**Comment by Barerock** [comment]
Thanks for the detailed reply. There is a forum discussion around that briefly covers someone casually setting something's force to neutral; however, they don't share how they did it. Rampant apparently doesn't edit forces to any extent that would break this function -- this person was using it and found that invulnerable structures were still unusually targeted by Rampan'ts AI -- so neutrality was the solution.

I asked here because you're way more familiar with the locations of settings in IR3, than say, anyone else.

**Comment by Deadlock989** [comment]
Changing the force of an entity is something done by control stage scripting - prototypes (e.g. the definition for the power pole in IR3's entities-power.lua file) don't have a force yet. I would ask for support on the "Modding help" subforum of the official Factorio forum.

**Comment by Barerock** [comment]
Excellent advice. Someone on reddit, years ago, helped immensely with the comment "/editor and go into the force tab and poke around a bit you should find it" lol, which I thought about but am unfamiliar with. I've only got 230 hours in Factorio and have never touched this stuff.

**Comment by Deadlock989** [comment]
FWIW I bitterly regret directing you to that forum, I had forgotten what it's like there. Won't make that mistake again.

**Comment by Barerock** [comment]
> FWIW I bitterly regret directing you to that forum, I had forgotten what it's like there. Won't make that mistake again.

Ha, I get what you mean; but it was an overall productive experience. Forums are forums, and it seems the Factorio forums are exactly how I expected. Those were some extremely "Factorio player" responses!
