### ISSUE TITLE
The same time for the production of charcoal from wood chips and from wood

### ISSUE THREAD

**Issue by Kadyrbai** [Deadlock989/IndustrialRevolution#381]
Hello,

The same time for the production of charcoal from wood chips and from wood in early game. Maybe make increase the time recipe charcoal from wood? Without this, the recipe of crushing wood is not in demand at the early game.

![1](https://github.com/Deadlock989/IndustrialRevolution/assets/156506058/443ebf17-65aa-439f-afbd-d9b91fe058c4)
![2](https://github.com/Deadlock989/IndustrialRevolution/assets/156506058/48726909-5d50-40ba-af30-d5b6ddb17f5d)
![3](https://github.com/Deadlock989/IndustrialRevolution/assets/156506058/09015c4f-349b-4bdf-b41e-0488352d1c88)

**Comment by Kadyrbai** [comment]
add screenshot

**Comment by Deadlock989** [comment]
This is working as intended and will not change.
