### ISSUE TITLE
Copper Scatterbots don’t need energy

### ISSUE THREAD

**Issue by Cadams111** [Deadlock989/IndustrialRevolution#387]
**Describe the issue**
Though Defenders etc need charged batteries, the copper scatterbots don’t need charged steam cells.

**Factorio version, IR version**
Most recent as of 2024/01/28

**Other mods installed**
Just the IR3 add on packs

**Comment by Deadlock989** [comment]
I'm fine with this as it is. Steam cells did not exist when scatterbots were introduced. I suppose I could/should have updated their recipe when steam cells were added in 3.1.0, but I don't want to change recipes and break people's saved games unless it's absolutely necessary.
