### ISSUE TITLE
Beacons don't affect forestries

### ISSUE THREAD

**Issue by Floyden** [Deadlock989/IndustrialRevolution#39]
Hey,

Currently beacons don't affect forestries even though it is indicated that they should when hovering above a beacon:
![grafik](https://user-images.githubusercontent.com/28449556/112373999-e015fe00-8ce1-11eb-9e54-49ba51a73844.png)
(On the left is an ingot foundry and on the right is a laser assembler, both showing correctly that they are or are not affected by the beacon)

**Comment by Deadlock989** [comment]
They were set up to allow the pollution modifier only - but no vanilla or IR2 module provides only a pollution modifier.
