### ISSUE TITLE
Victory screen doesn't appear upon launching a satellite with Better Victory Screen installed.

### ISSUE THREAD

**Issue by Nordblum** [Deadlock989/IndustrialRevolution#392]
**Describe the issue**
Upon launching a rocket with a satellite, victory screen didn't appear at all. Maybe it's an issue on Better Victory Screen's part although compatibility with Industrial Revolution 3 is claimed in its description. Just in case I opened a [bug report](https://mods.factorio.com/mod/better-victory-screen/discussion/65cad500358489e577b3c428) in Better Victory Screen's discussions too.

**Factorio version, IR version**
Factorio version: 1.1.101
IR version: 3.1.20

**Other mods installed**
Better Victory Screen version: 0.2.12

**Comment by Deadlock989** [comment]
Thanks for the report. IR3 doesn't make any changes to the vanilla victory condition (launch a rocket). To double check, I tested without BVS installed (both with and without satellite) and confirmed that it works as expected. So this must be some issue with BVS.

**Comment by Nordblum** [comment]
Understood, thank you for clearing this up.
