### ISSUE TITLE
IR3 error while loading recipe

### ISSUE THREAD

**Issue by Zamboa7** [Deadlock989/IndustrialRevolution#393]
Screenshot:
![IR3_Recipe_Error](https://github.com/Deadlock989/IndustrialRevolution/assets/160351957/9cf7486f-d48f-4d96-876b-a29b537123e4)

**Describe the issue**
There is an error while loading IR3:

"Failed to load mods: Error while loading recipe prototype "forestry-wood-fertiliser-00" (recipe): Difficulty normal: amount must be larger than 0 in property tree at ROOT.recipe.forestry-wood-fertiliser-00.ingredients[1]

Modifications: Industrial Revolution 3"

**Versions**
Factorio version: 1.1.104
IR version: 3.1.13

**Other mods installed**
Black Rubber Belts
Larger Lamps
Deep Space Mining
Power Loaders and Ingot Stacking

**Potential Cause**
The Factorio version 1.1.101 update has "Fluid ingredient amounts must be larger than zero".
Link: https://forums.factorio.com/viewtopic.php?f=3&t=110371

**Comment by Deadlock989** [comment]
Your IR version is out of date. You are on 3.1.13. The issue above with breaking API changes in Factorio 1.101 was fixed for version 3.1.15 (#383). The most recent version is 3.1.20.

**Comment by Zamboa7** [comment]
Thanks!
