### ISSUE TITLE
Airship station interface

### ISSUE THREAD

**Issue by AlexK0l** [Deadlock989/IndustrialRevolution#395]
**Describe the issue**
Airship station interface not full

**Factorio version, IR version**
Factorio version 1.1.104, IR version 3.1.20, Airships version 1.0

**Other mods installed**
LTN and helmod

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/54741142/ab29bad0-e44d-4b29-812d-d27d1c72c3e0)

**Comment by Deadlock989** [comment]
> **Describe the issue** Airship station interface not full

I don't know what you mean by this.

**Comment by AlexK0l** [comment]
> > **Describe the issue** Airship station interface not full
> 
> I don't know what you mean by this.

Buttons for prioritize and delete rules are missing

**Comment by Deadlock989** [comment]
In your screenshot it looks like the refuelling behaviour setting is distorted by a very long translated string. You must have some kind of localisation mod installed. I need to know which one, and which language this is.

**Comment by AlexK0l** [comment]
> In your screenshot it looks like the refuelling behaviour setting is distorted by a very long translated string. You must have some kind of localisation mod installed. I need to know which one, and which language this is.

It is russian language. Localization mod: https://mods.factorio.com/mod/IndustrialRevolution_Language_Pack

**Comment by Deadlock989** [comment]
The main problem is being caused by the Russian localisation in that mod. Two of the rich text icons in the refuelling setting's drop-down options are broken references:

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/3128845/54c94194-8b37-42b8-bffd-86405da75bf0)

The correct icon references are `[img=refuel-refuel-and-empty]` and `[img=refuel-refuel]`. You will need to raise this with the authors of that mod.

I can prevent this kind of mistake from breaking the interface by setting a maximum width for some of the GUI elements. I put this on my list of things to do, but this is a low priority task for me because if the localised strings do not contain broken icon references and are of reasonable length then there is no problem.

**Comment by AlexK0l** [comment]
> The main problem is being caused by the Russian localisation in that mod. Two of the rich text icons in the refuelling setting's drop-down options are broken references:
> 
> ![image](https://private-user-images.githubusercontent.com/3128845/309725805-54c94194-8b37-42b8-bffd-86405da75bf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTAyMjcsIm5iZiI6MTcwOTU0OTkyNywicGF0aCI6Ii8zMTI4ODQ1LzMwOTcyNTgwNS01NGM5NDE5NC04YjM3LTQyYjgtYmZmZC04NjQwNWRhNzViZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTA1ODQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWYwZDZlZTBlNTliOTVlM2FmZWFlZTRiZTZhNTkxMGQ3MmIyYTM5NzI2MjAwMTI3Mzk0YmU4NjgzZjRmMDNiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.w_9ePfpLNG0XlsqjPQzB5uIl7TeNRDDlBm-0zjcF0dU)
> 
> The correct icon references are `[img=refuel-refuel-and-empty]` and `[img=refuel-refuel]`. You will need to raise this with the authors of that mod.
> 
> I can prevent this kind of mistake from breaking the interface by setting a maximum width for some of the GUI elements. I will put this on my list of things to do, but this is a low priority task for me because if the localised strings do not contain broken icon references and are of reasonable length then there is no problem.

Thanks

**Comment by Deadlock989** [comment]
I have made some adjustments for the next release of Airships, which will be out later this week. This should help with the broken references in the Russian localisation mod but may also help for other languages where some phrases can only be expressed with much longer or shorter character strings than English. But where third party localisation mods have broken references or other mistakes, only the author of those mods can fix the issue.

- Limit dropdowns in the Settings section to a maximum width
- Allow item label in Loading/Unloading sections to be squashed as well as stretched

![airshipgui](https://github.com/Deadlock989/IndustrialRevolution/assets/3128845/94887bc0-22a8-49ba-8648-d559ab548d76)

**Comment by AlexK0l** [comment]
Thanks a lot

**Comment by Astorin** [comment]
Broken strings for refuel icons in Russian language fixed.
Thanks for report.
