### ISSUE TITLE
Suggestion: molten glass and molten silicon

### ISSUE THREAD

**Issue by FrancoisDevemy5** [Deadlock989/IndustrialRevolution#397]
I believe that molten glass and silicon would be a great fit for the arc furnace.
I believe that glass and silicon are the two meltable materials being produced by furnace or alloy furnace that are not being produced by arc furnace.

Since in the IR universe both are produced with silica, they could form a two step process similar to iron and steel: 
- Melt silica to form molten silica.
- Molten silica can be cast into silicon or mixed with melted tin to form molten glass.

Some references:
https://en.wikipedia.org/wiki/Wafer_(electronics)#Formation
https://en.wikipedia.org/wiki/Float_glass

**Factorio version, IR version**
Factorio 1.1.104
IR 3.1.20

**Comment by Deadlock989** [comment]
Molten glass existed in IR2 but it was removed when IR2's foundry building was replaced with casts for IR3. I'm unaware of graphite-electrode arc furnaces ever being used for non-metals, although IR3 doesn't always aim for pure realism anyway. I don't have any plans to add more molten materials at this late stage of the mod's life.
