### ISSUE TITLE
Strange selection of possible ingredient for stone and bronze furnace

### ISSUE THREAD

**Issue by FrancoisDevemy5** [Deadlock989/IndustrialRevolution#398]
The stone furnace can take copper and tin in all of their variants as ingredients (ore, crushed ore, pure mineral, scrap).
It can also take gold in all its forms but not iron.
So far so good.

What is puzzling to me is that it can also take lead (pure and scrap) but not nickel nor platinum.

The bronze furnace can take the four main ores in their four states but only three of the four derived ores in their pure mineral form: it cannot take chromium.

Is there some logic to those choices that I don't see?

**Factorio version, IR version**
Factorio 1.1.104
IR 3.1.20

**Comment by Deadlock989** [comment]
It is largely based on melting point, with lower-tech furnaces only being able to achieve lower temperatures, although unlocking order is also a factor. There may be inconsistencies but I don't think it's particularly important and I have no plans to make changes to this at this late stage of the mod's life.
