### ISSUE TITLE
No rubber trees?

### ISSUE THREAD

**Issue by Ralithune** [Deadlock989/IndustrialRevolution#40]
I've been trying out a game with Alien Biomes, Krastorio 2, and Industrial revolution.

I've walked all over the place - headed waaaayyyy out in to the boonies in all directions away from my base, and I simply cannot find Rubber Trees anywhere.

Is this a potential bug?  Is there some debug command I can run to label them on the map?

**Comment by Deadlock989** [comment]
It's a known issue with AB - it disables every tree previously set up by vanilla or any other mod and then replaces them with its own set. If your mod combo entails that it loads _after_ IR2 then it will disable IR2's trees as well. I don't have any plans to support it, sorry.

**Comment by Ralithune** [comment]
Ok, thanks.  Could we have that in the mod description please?  I'm glad I tried it out, but I'm a little disappointed at the 26 hours of time I wasted not knowing about the incompatibility.

**Comment by Deadlock989** [comment]
There are most likely hundreds of incompatible mods out there. Listing them is not how I envisage my leisure time being spent, sorry. In general if you try and mash two large mods together you can expect shenanigans.
