### ISSUE TITLE
IR3 Loaders & Stacking: Can't change the "Machines enabled" setting

### ISSUE THREAD

**Issue by DarioGdR** [Deadlock989/IndustrialRevolution#403]
**This bug is for the mod "Industrial Revolution 3: Powered Loaders & Ingot Stacking"**

When changing the "Machines enabled" setting to "Only loaders":
![image](https://github.com/Deadlock989/IndustrialRevolution/assets/11424248/9164471b-8a77-455d-9b06-c2d808ff3390)

I get the following error while the game is launching:
![image](https://github.com/Deadlock989/IndustrialRevolution/assets/11424248/68a7f628-547c-494e-9f5e-654b81b974bb)

Restarting the settings to default fixes the issue.

I'm using the latest Factorio and IR3 versions for every mod:
- Factorio: 1.1.104
- IR3: 3.1.20
- IR3 Loaders & Stackers: 1.0.9

**Comment by Deadlock989** [comment]
Thanks for the report. This explains #402.
