### ISSUE TITLE
Steam inserter able to connect systems of different fluids

### ISSUE THREAD

**Issue by Dev-iL** [Deadlock989/IndustrialRevolution#406]
I'm not sure if this is a Factorio bug, or a bug in the mod, but:

![Screenshot from 2024-03-21 10-29-14](https://github.com/Deadlock989/IndustrialRevolution/assets/6509619/0178912b-d13f-4aa3-9671-6e6e39e9035c)

I had a steam pipe system and a water pipe system, then I placed a steam inserter in the middle and it connected to both (expected behavior: error saying that one cannot connect different fluids). The strange thing is I couldn't place any other steam inserters _anywhere_ (even disconnected) because now the incompatible fluids error did pop up. Saving and loading the game allowed me to keep the mis-connected inserter as well as place new ones.

**Factorio version, IR version**
Factorio 1.1.104
IR3 3.1.20

**Comment by Deadlock989** [comment]
This isn't something mods have access to or any control over. The "cannot connect systems with different fluids" restrictions are hard-coded but there are several ways they can be (accidentally or deliberately) circumvented.

**Comment by Dev-iL** [comment]
Would it make any difference if I reported it to the game devs? Or are they familiar with this issue and "that's just the way it is"?

**Comment by Deadlock989** [comment]
I couldn't say - I know that people are regularly tripped up by fluid mixing situations but some of them have been dismissed as "working as intended". If it were just the former issue (you were able to place an inserter that resulted in a mixed fluid system) I wouldn't rate your chances, personally. The latter issue (not being able to place more until reloading) sounds a lot weirder to me. But mainly my impression is that they are focused on the expansion and only addressing issues that result in hard crashes or are obviously game-breaking bugs.
