### ISSUE TITLE
Recipe Loop with Advanced Furnaces 2

### ISSUE THREAD

**Issue by MajicSilver** [Deadlock989/IndustrialRevolution#407]
**Describe the issue**
Fails on startup with a recipe loop when ir3 and dependencies are on along with Advanced Furnaces 2

**Factorio version, IR version**
FV-1.1.104
IRV-3.1.21

**Other mods installed**
disabled all others and found AF2 to be the issue

**Comment by MajicSilver** [comment]
*correction- research loop not a recipe loop

**Comment by Deadlock989** [comment]
See "Cyclical dependency errors" in Frequently Reported Issues (#254). 

AF2 looks like it had IR1 and IR2 support but it hasn't been updated for over 2 years; it is a hotfix for another mod which had its last update 4 years ago. This isn't something I'm interested in supporting, sorry.
