### ISSUE TITLE
Electrum research has "Reinforced null field plate (Recipe)" as result

### ISSUE THREAD

**Issue by belgianguy** [Deadlock989/IndustrialRevolution#409]
**Describe the issue**
I wonder whether the "null" in the "Reinforced null field plate (Recipe)" is intentional or if this is a missing text.

**Factorio version, IR version**
1.1.104 (build 62119, linux64), 3.1.21

**Other mods installed**
None.

**Comment by Deadlock989** [comment]
It's intentional.
