### ISSUE TITLE
no active cutscene @ client_quits_during_teleport

### ISSUE THREAD

**Issue by Quezler** [Deadlock989/IndustrialRevolution#41]
```53592.360 Error MainLoop.cpp:1285: Exception at tick 14007705: The mod Industrial Revolution 2 (2.1.4) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event IndustrialRevolution::on_player_left_game (ID 45)
Player does not have a cutscene active
stack traceback:
    [C]: in function 'exit_cutscene'
    ...ustrialRevolution__/code/functions/functions-control.lua:891: in function 'client_quits_during_teleport'
    __IndustrialRevolution__/control.lua:174: in function <__IndustrialRevolution__/control.lua:172>
253592.360 Error ServerMultiplayerManager.cpp:91: MultiplayerManager failed: "The mod Industrial Revolution 2 (2.1.4) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event IndustrialRevolution::on_player_left_game (ID 45)
Player does not have a cutscene active
stack traceback:
    [C]: in function 'exit_cutscene'
    ...ustrialRevolution__/code/functions/functions-control.lua:891: in function 'client_quits_during_teleport'
    __IndustrialRevolution__/control.lua:174: in function <__IndustrialRevolution__/control.lua:172>"
253592.360 Info ServerMultiplayerManager.cpp:780: updateTick(14007705) changing state from(InGame) to(Failed)
253592.360 Quitting: multiplayer error.
253593.375 Info ServerMultiplayerManager.cpp:140: Quitting multiplayer connection.

**Comment by Deadlock989** [comment]
Some description of how you got into this state, reproduction steps, any minimal context etc. would be appreciated, as well as confirmation of any other mods involved.

**Comment by Quezler** [comment]
the entire context can be found on this discord: https://discord.gg/FWQWKKA 
(related to the https://www.bigcommunitygames.com/factorio-ir2/ event)

grab the factorio role in `#role-assignment` and then head to the `#factory-chat` channel in the `-factorio` subcategory:
https://discord.com/channels/662813412413276191/687992923341586439/834038331494760508
this is where the thread starts, we kinda went over it with a few people and discussed it a bunch ^

(i understand that it might be a hassle to join a discord for the context, but copy pasting it entirely would be a mess)

**Comment by Deadlock989** [comment]
I tried that and the role assignment reaction thing seems to be broken, I can't select any of the options (the next page / previous page reactions or any of the roles at all). This was in the web version of Discord. I don't use Discord any more and I'm not going to install the client to chase down a bug report.

I can fix this symptom as it has been reported, but ideally I would be given reproduction steps that help me understand how you got the player variables into this state, and then I can maybe fix the real cause.

**Comment by Quezler** [comment]
understandable,

as for reproducing it was all a bit vague, in the discord we basically threw theories around and tried to piece things together, it seemed to be related to quitting when teleporting, or more likely once the player reconnects and/or the server unpauses (even the autosave got corrupted, as in that this same error constantly returned), rolling back several autosaves (multiple seemed to be broken?) it returned to a state where it could load again, but its all a bit of a mystery 🤔

**Comment by LasXor** [comment]
Hi 
Im the admin that set that event up. Quetzler just brought this bugreport to my attention.

All mods used are:
![2021-04-21 16_20_25-Factorio 1 1 32](https://user-images.githubusercontent.com/38936297/115569487-8e02d100-a2bd-11eb-829f-45434975222e.png)


Sadly there is no confirmable information what actions exactly occured leading up to the problem.
All I have is the player that produced the last available server log message by leaving. Assuring me firmly that he did not leave while teleporting.

I am happy to provide you with the 2 presumedly corrupted saves i have if you think this could help you.

**Comment by Deadlock989** [comment]
It might help to have one of the saves, if that is possible to arrange - I don't think I will get much useful info out of it but it might be more useful in checking that a fix actually works (or at least allows the game to continue). Testing out multiplayer shenanigans is difficult on your own.

**Comment by LasXor** [comment]
Here you go:
https://www.dropbox.com/s/9acj1eb8066pir6/broken_world.zip?dl=0

**Comment by Deadlock989** [comment]
Thanks. What was the in-game name of the player who triggered the error?

**Comment by LasXor** [comment]
Dont know for shure. last log message is Laar

**Comment by Deadlock989** [comment]
Thanks. I have a simple fix for the error which halts play. But I want to spend a bit more time trying to work out how this happened. 

It looks like Laar somehow got into a state where they were able to cancel the transmat cutscene without leaving the game or cleaning up their per-player variables - so when they did leave the game, the control script broke because it expected them to be still in a cutscene. Oddly, there is one transmat (far west named "ocean") in the mid-cutscene inoperable state, but only that one ... there should be two.

**Comment by Quezler** [comment]
yea that sounds familair, i sometimes troll afk players by transmatting them, and the last time i did that (feels like forever ago compared to when the crash happened) i "thought" it finished teleporting and deconstruction marked it again, probably a little too soon since a few seconds after it got deconstructed the player appeared back at where the telepad was, didn't think much off it other than a failed attempt 😳

**Comment by LasXor** [comment]
Thanks for the update. Laar has confirmed this as possible and claims to remember the pad missing on return.

**Comment by Quezler** [comment]
that might have been a previous attempt (or a successful attempt afterwards), since im pretty sure it failed _that_ time 🤔

**Comment by Deadlock989** [comment]
That all fits what I'm finding. It's my oversight for not realising that non-destructible != non-minable. 

The fix then is:

1) Check that players really are in a cutscene before assuming they are when they quit the server (this will also allow "corrupted" saves to load)

2) Make transmats non-minable during the cutscene sequence

I will try and upload this later tonight although I've been having bandwidth issues so can't 100% guarantee it. If you find any transmats like "ocean" that are in an inoperable state, you'll have to mine them and replace them.

**Comment by Quezler** [comment]
alright lovely, no need to rush a release though, we now know what to avoid, not so sure about third parties though 😃
