### ISSUE TITLE
Barrels are substantially worse than canisters.

### ISSUE THREAD

**Issue by Hyomoto** [Deadlock989/IndustrialRevolution#410]
**Describe the issue**
The basic canisters you get from iron for transporting fluids can hold 30 units and stack to 50 yielding a density of 1,500.  Barrels require a more expensive material, steel, and also their own technology that uses a more advanced science.  In short, they are considerably more expensive overall.  They, however, hold 60 units and stack to 10 yielding an density of 600.  Cue womp womp music.

I can't imagine any balance reasons for this, at the absolute worst they should have the same energy density.  If we do our calculations on the fluid wagon is 25,000.  Using barrels we get 24,000 so I'm guessing this is where it's balanced around.  But, naturally, balance blindness leads to silly situations where using canisters yields a hot hot hot 60,000.  So, are barrels just being mistreated due to barrel bigotry or are canisters getting special treatment?  I don't know, but it's hilarious how much worse barrels are compared to the objectively primitive technology.

**Factorio version, IR version**
Factorio version 1.1.104, IR3 version 3.1.2.1

**Comment by Deadlock989** [comment]
There are reasons. I'm not going to bother explaining them to someone with such a piss-poor attitude.
