### ISSUE TITLE
Oddities in resistance and health of buildings

### ISSUE THREAD

**Issue by Alex-1248** [Deadlock989/IndustrialRevolution#413]
**Describe the issue**
There are some oddities in the resistances and health of vanilla buildings that are noticeable when compared to other buildings. It looks like the stats were kept from vanilla Factorio and weren't revised. I don't know if this was done intentionally or not, so I'll list them just in case.

1. Large steel pylon and substation have only fire resistance, while medium steel pole has five types of resistance and large wooden pole has impact resistance.
2. Flamethrower turret has the least number of types of resistance among turrets, although it is not made from the worst materials.
3. Roboport has fewer types of resistance than robotower.
4. Storage tank has no resistance unlike small tanks.
5. Steam turbine has less health and resistance than steam engine although it is made of higher tier materials.
6. Solar panel has 6.25 times less health than solar array. It seems to me that the difference is too big, perhaps it should be 5 like between robotower and roboport, but I'm not sure.

There are other vanilla buildings that retain the health and resistance (or lack of resistance) from vanilla Factorio that I haven't listed because I'm not sure that's a problem. It seems to me that all vanilla buildings need to be checked.

**Factorio version, IR version**
Factorio 1.1.104, IR 3.1.21

**Comment by Deadlock989** [comment]
It's not entirely intentional, but I have to ask: are these minor inconsistences actually causing problems?

**Comment by Alex-1248** [comment]
No, I didn't notice that these inconsistencies caused problems, they just seemed strange to me.

**Comment by Deadlock989** [comment]
OK. I can live with minor flaws/inconsistencies like this if they have no practical consequences. I have almost no free time available at the moment. I will mark this as "not an issue" for now but if things change then I might get around to it.
