### ISSUE TITLE
Graphene recipe asks for 'gas' helium

### ISSUE THREAD

**Issue by Shakunya** [Deadlock989/IndustrialRevolution#414]
**Describe the issue**
Isn't it supposed to ask for liquid helium, like recipes with nitrogen ? I couldn't find any way to make gas helium
(ps : i love your mod !)

**Factorio version, IR version**
1.1.104, 3.1.21

**Other mods installed**
storage / qol stuff

**Comment by Deadlock989** [comment]
No - this is working as intended. Ambient heat exchangers are a 1x1 pipe-like device that can warm and expand any liquified cryogenic gas into the room temperature gaseous form, for free; they are unlocked alongside cryogenic plants. 

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/3128845/cba9db39-9a2d-4f51-9455-bfb2c50c88bb)
