### ISSUE TITLE
The "gas" helium problem from yesterday

### ISSUE THREAD

**Issue by Shakunya** [Deadlock989/IndustrialRevolution#415]
**Describe the issue**
I already tried the heat exchanger and was able to insert helium in it, but the machine tells me "no ingredient" and nothing more happens... could you please tell me what did i do wrong ? Thanks for your quick answer

![helium](https://github.com/Deadlock989/IndustrialRevolution/assets/166734258/1ad495f8-59bd-48a9-96cd-4dd4920333c8)

**Comment by Cadams111** [comment]
I think the recipe is 10 LHe -> 40 Helium Gas, you just need more

**Comment by Shakunya** [comment]
Oh, indeed ! Thanks !
