### ISSUE TITLE
Item description seems to be a placeholder

### ISSUE THREAD

**Issue by Ace-346** [Deadlock989/IndustrialRevolution#416]
**Describe the issue**
The item description visible when hovering over the Advanced battery charger recipe simply says "Battery charger". Screenshot below.

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/22972904/7901e12d-8410-48e7-bf0f-50debfb8fb57)

Since the Advanced battery generator has the same description as the Battery generator, I think this is likely just a placeholder that never got updated.

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/22972904/fbd975ba-3d76-4cba-b404-dac9790220ca)

**Factorio version, IR version**
Factorio: 1.1.104
IR3 Version: 3.1.21

**Other mods installed**
None that are relevant, I disabled all mods but IR3 and this is still present.

Thanks for your work on IR3, it has been a ton of fun so far!

**Comment by Deadlock989** [comment]
It seems the advanced battery charger has been told to use the lower tier charger's name localisation for its description instead of its description. Fixed for next version.
