### ISSUE TITLE
Steam pipe to steampipe

### ISSUE THREAD

**Issue by kanalgrufti** [Deadlock989/IndustrialRevolution#419]
**Describe the issue**
es ist nicht möglich ein dampfrohr an ein dampfrohr zu bauen. Es sind unterschiedliche Flüssigkeiten vorhanden. Nur über einen Blueprint lassen sich die Rohre verbinden.

**Factorio version, IR version**
Factorio version: 1.1.107; Industrial revolution 3 version: 3.1.22

**Other mods installed**
Autobild, todo list

**Comment by kanalgrufti** [comment]
Describe the issue
it is not possible to install a steam pipe on a steam pipe. Different fluids are available. The pipes can only be connected using a blueprint.

Factorio version, IR version
Factorio version: 1.1.107; Industrial revolution 3 version: 3.1.22

Other mods installed
Autobild, todo list

Factorio version, IR version
Factorio version: 1.1.107; Industrial revolution 3 version: 3.1.22

Other mods installed
Autobild, todo list

**Comment by Deadlock989** [comment]
This is how vanilla Factorio handles fluid mixing. There is nothing I can do about it. See the wiki for details: https://wiki.factorio.com/Fluid_system
