### ISSUE TITLE
Monowheel collision rectangle too low

### ISSUE THREAD

**Issue by jeison-souza** [Deadlock989/IndustrialRevolution#420]
The collision rectangle of the monowheel is too low, making it collide with almost everything since you got the false feeling that the vehicle is going to fit in the gap.

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/3654646/63408e70-9541-4b20-b893-8df32101534a)

Factorio 1.1.107
IR3 3.1.22

All Mods:
AbandonedRuins 1.1.6
Automatic_Train_Painter 1.2.0
BlueprintSignals 0.3.0
BottleneckLite 1.2.8
CursorEnhancements 2.1.0
DeadlockBlackRubberBelts 1.0.4
DeadlockLargerLamp 1.5.1
FNEI 0.4.2
FactorySearch 1.11.0
IndustrialRevolution3 3.1.22
IndustrialRevolution3Airships 1.0.1
IndustrialRevolution3LoadersStacking 1.0.11
IndustrialRevolution3SpaceMining 1.0.2
Infinizoom 0.1.9
Inventory Sensor 1.10.7
LandfillEverythingButTrains 1.1.1
Landfill_plus 1.0.19
Milestones 1.3.25
ModuleInserterSimplified 1.1.4
PickerAtheneum 1.2.5
PickerDollies 1.2.6
PipeVisualizer 2.2.1
QuickItemSearch 2.1.8
RateCalculator 3.2.4
RecipeBook 3.5.7
RemoteConfiguration 1.2.6
ShuttleTrainRefresh 1.2.0
Tapeline 2.0.10
TaskList 0.4.8
Todo-List 19.3.0
TrainGroups 1.4.3
Train_Control_Signals 1.0.6
VehicleSnap 1.18.5
automatic-station-painter-continued 1.1.0
base 1.1.107
bullet-trails 0.6.2
clock 1.1.0
electric-shuttle-train 1.0.9
even-distribution 1.0.10
factoryplanner 1.1.78
flib 0.14.0
ghost-counter 1.2.1
grappling-gun 0.3.3
helmod 1.0.9
manual-inventory-sort 2.2.5
power-grid-comb 1.1.0
pushbutton 1.1.1
stack-combinator 1.6.1
textplates 0.6.10

**Comment by Deadlock989** [comment]
It's been this way since IR1 - several years now. The game is 2.5D and there is no best fit solution. I don't have any plans to change this.
