### ISSUE TITLE
Turrets

### ISSUE THREAD

**Issue by DeathPhoenix22** [Deadlock989/IndustrialRevolution#423]
**Assets**
Hi Deadlock,
Would you be interested in making game assets for another game? I'm a solo dev working on an RTS and your turrets and buildings art is amazing.
Let me know ;)
Respectfully!

**Comment by Deadlock989** [comment]
Hi,

Thanks for asking. Unfortunately I don't think I have the capacity. I'm holding down two jobs and there is a lot going on at the moment - this isn't likely to change before the end of the year.

You might try the mod user raspberrypuppies (https://mods.factorio.com/user/raspberrypuppies) - those are the next best looking turrets in a Factorio mod in my opinion. I don't think they made them themselves, but they know their way around a Factorio sprite and hold the license to use them.

Cheers

**Comment by DeathPhoenix22** [comment]
Hi,

Thx for the valuable insight. I'll try to reach out the owner of the other turrets.

I must admit that I still prefer yours and would "simply" (with all the respect that your incredible work deserves) need access and permission to use them. I can easily work with the factorio sprites format "as is" :D I would love to integrate some of these assets as is :D But they're yours so ;) Let me know if an "as is" & " no extra work on your side" is interesting for you?

With all respects, have a nice day!
JR

________________________________
De : Deadlock989 ***@***.***>
Envoyé : jeudi, mai 16, 2024 3:38:34 p.m.
À : Deadlock989/IndustrialRevolution ***@***.***>
Cc : DeathPhoenix22 ***@***.***>; Author ***@***.***>
Objet : Re: [Deadlock989/IndustrialRevolution] Turrets (Issue #423)


Hi,

Thanks for asking. Unfortunately I don't think I have the capacity. I'm holding down two jobs and there is a lot going on at the moment - this isn't likely to change before the end of the year.

You might try the mod user raspberrypuppies (https://mods.factorio.com/user/raspberrypuppies) - those are the next best looking turrets in a Factorio mod in my opinion. I don't think they made them themselves, but they know their way around a Factorio sprite and hold the license to use them.

Cheers
