### ISSUE TITLE
Steam Derrick

### ISSUE THREAD

**Issue by CrCh38** [Deadlock989/IndustrialRevolution#429]
The steam derrick doesn't have a recipe at the start of the game, recipe book shows there is no technology requirement and even so, it has no way of crafting.

**Factorio version, IR version**
Factorio Version 1.1.109
IR Version 3.1.24

**Other mods installed**
Was starting to play a new save with some mods, but i also check with just IR and the minimum dependencies and the problem continue.

**Comment by Deadlock989** [comment]
Oops. Fixed for next version.
