### ISSUE TITLE
Mod loading conflict with Rampant mod.

### ISSUE THREAD

**Issue by Kokuhatsu** [Deadlock989/IndustrialRevolution#430]
Hi, I have encountered a compatibility error when [Rampant ](https://mods.factorio.com/mod/Rampant)has been installed
Loading error:
![obraz](https://github.com/Deadlock989/IndustrialRevolution/assets/34172652/64036ecf-9550-40ba-b2a3-d37c8e828def)
It would be nice to play these mods together.

Versions:
```
Factorio 1.1.107
IR3      3.1.25
Rampant  3.3.4
```
Thanks for your work on this mod, it's great :)

**Comment by Deadlock989** [comment]
This was caused by the new rocket turret trying to list the enemy types it is ignoring, but Rampant adds so many biter variants that the resulting description was invalid. Fixed for next version (generic description instead).
