### ISSUE TITLE
LOVE the looks, but not what it does. IR3 is...

### ISSUE THREAD

**Issue by CopperBoltwire** [Deadlock989/IndustrialRevolution#431]
**Describe the issue**
LOVE the looks, but not what it does. IR3 is unbelievable beautiful. I dare say it puts the original Factorio artists to shame.
Would love an IR3 Reskin for Factorio + Bobs **normal** gameplay, but looking like IR3 just to be able to continue to admire this magnificent piece of art!

Again, i don't like how IR3 changes the game, and I have to much of a love for Bots and Assemblers early game, which IR3 seems to be designed not to work towards.
I decided to rip open the mod and just admire the sprite work, and i'm in awe.
Simply just beautiful, and i feel most of the sprite work is going to waste for a casual player like me.
Would love a texture replacement mod that uses IR3, but for normal playthrough + Bobs + Angel + Schall.
I have a strong feeling this'll never happen, but why should that stop me from sharing my wish?

I could not make a post on the mod page, and there was no other obvious way to say thank you for something this gorgeous.
So instead, enjoy this "fake" issue.

Simply gorgeous!

**Factorio version, IR version**
1.1.x
IR3

**Other mods installed**
Bob's mods
Creative mod
AAI loaders + AAI loaders: Bob's compat
Angel's Warehouse mod
Space Extension (Feoras Fork) (Not the massive exploration mod, to much work.)
Schall Pickup Tower (Seriously, with Bob's Enemies enabled, and Alien artifact enabled, this mod is a MUST o.o )

**Comment by Deadlock989** [comment]
Thanks. But your feeling is accurate - there won't be any future support for Angelbob mods.
