### ISSUE TITLE
version dependency mismatch

### ISSUE THREAD

**Issue by wellexcusemeprincess** [Deadlock989/IndustrialRevolution#434]
**Describe the issue**
when searching for the mod via the built in mod manager, version 3.1.26 of the main mod lists the proper dependencies (IR Assets 1-4), but the assets themselves list IR 3.1.24 as a dependency, not version 3.1.26.  this results in being unable to play the mod without manually installing 3.1.24 as the mod manager will not activate the mods if the dependencies are not correct

**Factorio version, IR version**
Factorio version 1.1.107, IR version 3.1.26.

**Other mods installed**
I have a couple installed but most are small QOL mods.  this should not matter though as the issue is not in game as the mod will not activate

I would love it if you could patch this real quick man i have the next three days off and loved IR2 so I'm excited for a challenge trying it out on a ribbon world.  cheers

**Comment by Deadlock989** [comment]
Can't reproduce. The dependencies are for any version equal _or higher_. All you have to do is install the main IR3 mod.

**Comment by wellexcusemeprincess** [comment]
thanks for your response.  I will try to reinstall my game and see if it fixes it

**Comment by wellexcusemeprincess** [comment]
ah i'm a fool i had squeek through enabled which was disabling IR3.  thanks for everything you do as a mod author, i'm psyched for IR3 ribbon world
