### ISSUE TITLE
[Inspiration] Crude Oil

### ISSUE THREAD

**Issue by jtplay158** [Deadlock989/IndustrialRevolution#437]
**Describe the issue**
Is there some trick for crude oil? It's my first fluid inspiration. I have already 2 tanks full of crude oil. I try use barrel, pump. Nothing works. 

**Factorio version, IR version**
factorio and IR3 in last version

**Other mods installed**
some QOL mods.
time saver crafting mod
production scrap for IR3

** my save if this help**
[ir3.zip](https://github.com/user-attachments/files/15938370/ir3.zip)

**Comment by Deadlock989** [comment]
This save's global data has gotten into a strange state. Did you start the game with an earlier version of Inspiration - before crude oil inspiration was added (1.0.2)? Either way, I have added an `on_configuration_changed` check for next version, which fixes this save and should prevent this kind of issue in future. I will it upload it in the next half hour or so.

**Comment by jtplay158** [comment]
You are right . I start game with previous version of inspiration. Thank you. Now I can continue in my journey through your wonderful mod.
