### ISSUE TITLE
[Inspiration] Manifesto image size bug

### ISSUE THREAD

**Issue by StephenBarnes** [Deadlock989/IndustrialRevolution#438]
**Describe the issue**
See screenshot. My monitor is 1920x1080, images look like 2x scale, so maybe it's correct size for a 4k monitor.

![20240623184737_1](https://github.com/Deadlock989/IndustrialRevolution/assets/5836352/f1f276f5-1d6d-4e6c-b32c-40671fc7ff20)

**Factorio version, IR version**
IR3: 3.1.27
Factorio: 1.1.107

**Other mods installed**
None

**Comment by Deadlock989** [comment]
Ugh. Senior moment. This is not directly a resolution issue but a GUI scaling one, which is determined by resolution if you are using "Automatic scaling" in game settings (the default). Fixed for next version.
