### ISSUE TITLE
Crash with temporary station when 'Color trains' is ON

### ISSUE THREAD

**Issue by searcher-123** [Deadlock989/IndustrialRevolution#439]
**Describe the issue**
If the Color trains parameter is enabled, and specify the points between stations for the train.
![state](https://github.com/Deadlock989/IndustrialRevolution/assets/137143311/47df6dea-12bc-484f-a6a1-c13734a156df)
When the train reaches this point, an error occurs.
![error wo_stations](https://github.com/Deadlock989/IndustrialRevolution/assets/137143311/116bea72-a4c8-4f41-b349-144c112fb09d)
![With_stations](https://github.com/Deadlock989/IndustrialRevolution/assets/137143311/6151740b-d874-49f8-9544-bc9c13db8ffc)

**Factorio version, IR version**
Factorio 1.1.107
IR3 3.1.26

**Other mods installed**
Some small mod - JetPack, many QoL. Full list
![modlist_all](https://github.com/Deadlock989/IndustrialRevolution/assets/137143311/ccd99948-0353-4cf4-b8b7-db70ed02a060)
or just clean start game archive
[Ir3_.zip](https://github.com/user-attachments/files/15977646/Ir3_.zip)
---------------------

I assume this is due to the fact that the temporary station does not have a backer_name field.

function CONTROL.train_changed_state(event)
    local enabled = (settings.global["ir-colour-trains"].value ~= "no")
    if enabled and event.train and event.train.valid and event.train.state == defines.train_state.wait_station then
        local stop = event.train.station
        **local c = match_hue(stop.backer_name)**

**Comment by Deadlock989** [comment]
Good catch, fixed for next version.

> I assume this is due to the fact that the temporary station does not have a backer_name field.

It's more fundamental than that - there is no "station" (i.e. event.train.station is nil) when the stop is temporary.

**Comment by Deadlock989** [comment]
Made some additional changes and improvements to this option.

- Improved caching of known icon colours (especially re: icons with no known colour)
- Wagons are now coloured as well by default; new option to colour locomotives only
- Virtual signal colours now also supported
