### ISSUE TITLE
Technology mistakenly shown

### ISSUE THREAD

**Issue by Cadams111** [Deadlock989/IndustrialRevolution#448]
**Describe the issue**
Clockwork Scatterbot tech is visible even when Hide Military Tech map option is toggled on. Other military technologies are correctly hidden and Scatterbot tech is not researched, yet it’s shown as available to research

**Factorio version, IR version**
Base 1.1.109
IR3 3.1.29

**Other mods installed**
Full IR3 suite minus Forestry Combinator, no mods by other authors

**Comment by Deadlock989** [comment]
This is fixed for the next version. If it is still visible after updating, you may need to set the "Hide military technologies" setting back to visible, then return it to hidden.
