### ISSUE TITLE
Incongruent recipe for Portable Steam Engine

### ISSUE THREAD

**Issue by Cadams111** [Deadlock989/IndustrialRevolution#451]
**Describe the issue**
Possible non-issue. Portable Steam Engine seems to have an old recipe, the technology and recipe include a Combustion Engine while the module doesn’t consume combustible fuels anymore, it discharges steam capsules. This in some circumstances bumps up the technology requirements of Modular Armor unnecessarily.
Possible fix includes opting for a motor or rotor instead.

**Factorio version, IR version**
Base 1.1.109
IR3 3.1.29

**Other mods installed**
IR3 suite, Factory Planner

**Comment by Deadlock989** [comment]
I agree that this recipe is a little incongruous post-3.1.x and you are right that it is an old recipe, but this is not a major issue. Motors are already required by the armour itself, so removing the engines doesn't change the cost or depth of the technology, it would just have a very minor influence on possible unlocking orders. I don't feel like this is something worth addressing at this late stage.

![image](https://github.com/user-attachments/assets/fcae5dbd-03cd-4d7f-8220-3dccbbb42a33)
