### ISSUE TITLE
Informatron Manifesto conflict

### ISSUE THREAD

**Issue by Foeglas** [Deadlock989/IndustrialRevolution#452]
**Describe the issue**
If [Informatron](https://mods.factorio.com/mod/informatron) is enabled, IR3's blue Manifesto book button is grayed out and doesn't open.

**Factorio version, IR version**
Factorio 1.1.110 (experimental for PC), IndustrialRevolution3_3.1.30, IndustrialRevolution3Assets1_1.1.11, IndustrialRevolution3Assets2_1.1.2, IndustrialRevolution3Assets3_1.1.7, IndustrialRevolution3Assets4_1.1.0

**Other mods installed**
informatron_0.3.4

**Comment by Deadlock989** [comment]
This isn't a conflict, it's deliberate. If Informatron is installed then it handles the Manifesto documentation instead.
