### ISSUE TITLE
Transfer plates pull from the beginning of the container, not the end

### ISSUE THREAD

**Issue by vapopescu** [Deadlock989/IndustrialRevolution#453]
**Describe the issue**
When walking over the transfer plate, items are being pulled starting from the first slots instead of starting from the bottom (like inserters, bots and loaders do). This is inconvenient because if you slot-limit a full chest, the extra items in the red area are not consumed

**Factorio version, IR version**
Base 1.1.110
IR 3.1.29

**Other mods installed**
Just QoL stuff

**Comment by Deadlock989** [comment]
This is working as intended and I don't have any plans to change it.
