### ISSUE TITLE
Airship station name character limit is too low

### ISSUE THREAD

**Issue by vapopescu** [Deadlock989/IndustrialRevolution#454]
**Describe the issue**
I was trying to name the airship refueling station as `[item=rocket-fuel][virtual-signal=signal-L]`, taking advantage of Factorio's rich text system, and keeping the same naming scheme as for the train station names. However, I seem to hit a character limit that doesn't take icons into account.

Airship station rename:
![image](https://github.com/user-attachments/assets/b45c90d3-4c2b-41f0-843f-65d38df21185)

Train station rename:
![image](https://github.com/user-attachments/assets/90dbc22b-566f-4222-99b6-6aeaa90a4b65)

**Factorio version, IR version**
Base 1.1.110
IR 3.1.29

**Other mods installed**
Just QoL stuff

**Comment by Deadlock989** [comment]
There needs to be a character limit of some kind because unlike train stations, all the airship station data is kept in a Lua table and needs to be processed by script. Rich text syntax consumes a lot of those characters. I don't currently have any plans to change the way this works.
