### ISSUE TITLE
Rocket Turret doesn't make any sounds when shooting

### ISSUE THREAD

**Issue by TheKingJo** [Deadlock989/IndustrialRevolution#455]
**Describe the issue**
What is happening?
- When the rocket-turret is shooting at enemies it's not doing the rocket shooting sound as it would when you use a rocket launcher as player

What did I expect?
- The rocket launcher sound

Reproduction
- Place rocket turret, arm it, have it shoot enemies

How to fix:
- In MOD/code/entities/entities-turrets.lua at Line 591 it says `sound = table.deepcopy(data.raw.gun["rocket-launcher"].sound)`. A gun doesn't have a plain sound parameter, it's missing the `attack_parameters.` It should be:
`sound = table.deepcopy(data.raw.gun["rocket-launcher"].attack_parameters.sound)`

**Factorio version, IR version**
Factorio - 1.1.110
IR - 3.1.30

**Other mods installed**
Way too many and actually irrelevant, since it also appears in vanilla + bare minimum IR mods enabled.

**Comment by Deadlock989** [comment]
Fixed for the 3.2.x branch.
