### ISSUE TITLE
Return burnt fuel when deconstructing a vehicle with partially-burned fuel

### ISSUE THREAD

**Issue by geekofalltrades** [Deadlock989/IndustrialRevolution#458]
**Describe the issue**
As a vehicle starts burning fuel, the fuel disappears from the fuel slot. Once the fuel is fully burnt, the burnt result appears in the burned fuel slot. If the vehicle is deconstructed while the fuel is not fully burnt, the burned result is lost. The constant loss of high pressure canisters if I put down vehicles temporarily is irksome.

It would be lovely if a vehicle with partially-burned fuel could return the burnt result when deconstructed. I would sacrifice the high octane fuel in the canister, but at least I'd have my canister back.

**Factorio version, IR version**
Factorio 1.1.110, IR3 2.1.29

**Comment by Deadlock989** [comment]
Related to #200; discussion of the issues on the Factorio forum [here](https://forums.factorio.com/viewtopic.php?f=28&t=91653).

This doesn't bother me for vehicles particularly (I rarely pick them up) but the same issue applies to grid equipment with burnt fuel slots, where it is possible to lose 10 or more canisters/cells/batteries at once with a mis-click. 

For entities with a "burner" energy source (including vehicles) it is possible to see whether something is currently "being burned" and what it is, which means you could look up the "burnt result" and return it when the entity is picked up (you'd also have to manually handle the case where your inventory is full and spill the item on the ground). So this could be done for vehicles specifically.

However the event that handles grid equipment removals does not return a reference to the instance of the equipment, only to the name of its prototype, so there is no way in Factorio 1.1 to do this for equipment.

My gut feeling is that this is something the base game should be addressing. However it's unlikely to get any traction from them as vanilla Factorio currently makes only one use of the burnt fuel slot, in nuclear reactors.

I will take another look at this in future when it has been decided whether IR3 is updating to 1.2 or not.
