### ISSUE TITLE
Suggestion about gases

### ISSUE THREAD

**Issue by tolikzodrot** [Deadlock989/IndustrialRevolution#459]
Add a flare stack to burn flammable glasses such as sour gas and natural gas to reduce pollution from getting rid of them as opposed to wenting

**Comment by Deadlock989** [comment]
There was a flare stack in IR1 and IR2 but I removed it on purpose because it trivialises play. I don't have any plans to return it. There may be third party flare stack mods that work with IR3 on the mod portal, I haven't checked.

**Comment by tolikzodrot** [comment]
Hi. That makes sense, sorry for taking your time, should have checked the development history first. Also, can I ask you something, were you given early access to 2.0 to start working on the update? Because I heard some of the overhaul mod's developers got it. Again, I am sorry for taking your time especially if you are already working on an update for 2.0 release.

**Comment by Deadlock989** [comment]
Yes, but they made me sign an NDA. I can say more about the issues after the DLC is released later this month.
