### ISSUE TITLE
marathon settings

### ISSUE THREAD

**Issue by neviktor** [Deadlock989/IndustrialRevolution#46]
Hi!
I'm trying go start new IR2 game with marathon settings but it seems:
- recipes difficulty settings don't affect recipes
- technology difficulty settings don't affect upgrades
- price multiplier don't  multiply prices

**Comment by Deadlock989** [comment]
Hi,

Recipe difficulties aren't supported by IR2 I'm afraid. Recipes are what they are. It was the same in IR1. There used to be a note about this in the mod's portal description but it appears to have been lost in subsequent edits.

Technology difficulty - I don't really know why that option is even in the settings, it doesn't even do anything in vanilla.

Price multiplier - I can't reproduce your finding, when I set it to 100, technology science pack costs are correctly increased by a factor of 100. Basic automation technology is immune to this setting (design feature inherited from vanilla).
