### ISSUE TITLE
Air purification tower run constantly

### ISSUE THREAD

**Issue by pyrignis** [Deadlock989/IndustrialRevolution#47]
This could be a design decision or a game limitation but I feel the mod could be improved by turning the air purification towers only when required.
I haven't found any way to detect the pollution level near the air purification towers and, according to the test I've done, the tower consume charcoal/gold foil at the same rate, no matter the pollutions levels.
Is the air purification tower designed as a sink or do you feel that a on-demand activation would be interesting?

**Comment by RepairmanSki** [comment]
You could get the desired outcome by adding another mod (presuming compatibility):
https://mods.factorio.com/mod/pollution-combinator

**Comment by Deadlock989** [comment]
There isn't support in the base game for this. It could be scripted but generally I avoid scripted mechanics, especially anything that would need constant polling (like this). Third party mods are your best bet.
