### ISSUE TITLE
liquid-concrete does not exist.

### ISSUE THREAD

**Issue by ESPATAR** [Deadlock989/IndustrialRevolution#48]
![image](https://user-images.githubusercontent.com/85032710/120078994-2b7ecb00-c0dc-11eb-8cc8-79fa7a190300.png)

![image](https://user-images.githubusercontent.com/85032710/120079158-da230b80-c0dc-11eb-8d99-2e7925dcbce2.png)

![image](https://user-images.githubusercontent.com/85032710/120079162-dee7bf80-c0dc-11eb-8a18-9f6a9bbabc11.png)

mod list
- Angel
- Yuoki
- KS_power
- NPUtils

**Comment by Deadlock989** [comment]
IR2 isn't compatible with Angel's mods. I don't know anything about the other three.

It does look like there is a minor issue in IR2 where the scrapping algorithm isn't anticipating crafting-type recipes from other mods that only output a single fluid result. (for example, liquid concrete in Angel's Smelting).

I have fixed that for the next version but I still don't support Angel's mods and I don't think they will ever work well together, there is too much overlapping ground.
