### ISSUE TITLE
Crash with Transmat while using Jetpack

### ISSUE THREAD

**Issue by RusselRaZe** [Deadlock989/IndustrialRevolution#50]
Not sure if you'd be interested in fixing this, since it looks to be a specific mod issue, but I figured I'd report it anyways, If you're flying with the Jetpack and you use the Transmat, the game will crash after the teleporting cutscene.

![factorio_2021_05_30200740](https://user-images.githubusercontent.com/73858455/120124688-891a2280-c183-11eb-82dd-441651c76e64.png)

**Comment by Deadlock989** [comment]
I took a look at this and I don't see an easy fix at my end without specifically adding tailor-made support to work around what Jetpack is doing, which could change at any time without notice, and it's not a mod I use myself.

The transmat cutscene has to make use of an "invisible car" to hide the character during the transmat cutscene. This is currently the least intrusive way to make a character invisible and was recommended to me by a Wube staff member. (There are a couple of alternative solutions but they cause more problems than they solve.)

But Jetpack unconditionally evicts players from vehicles every single tick while the jetpack is active, even if they have entered a cutscene (line 91 of Jetpack/scripts/jetpack.lua). I can see that there is a TODO comment in the Jetpack control script about interaction with vehicles, which to me says they are aware that entering vehicles could be handled differently. I can also see a typo on line 353 of Jetpack/scripts/jetpack.lua which is preventing the vehicle-related code in lines 471-477 from ever running, though I'm not completely sure what that was intended to do and don't think it would help this issue.

The ideal way to handle it would be that IR2 adds "character is flying" to its list of reasons to deny a transmat connection. However Factorio has no native support for flying characters, it's simulated by Jetpack via scripted manipulation of shadows and the character position, so I don't know how I would go about detecting "flying" in a generic way.

I recommend raising this issue with the author of Jetpack. One potential generic solution is that Jetpack should avoid making any changes to player character states if they are in a cutscene. Another is that they could specifically handle entering a vehicle (e.g. looking for on_player_driving_changed_state events and cancelling the jetpack state).

**Comment by RusselRaZe** [comment]
Hello, I brought this up to Earendel, the author of Jetpack, and this was the response with a fix included if you're still interested:
![Discord_2021_05_31184149](https://user-images.githubusercontent.com/73858455/120247000-05723b80-c240-11eb-9b74-7d4254471088.png)
