### ISSUE TITLE
[API request] Add a way to change technology cost progression

### ISSUE THREAD

**Issue by Genhis** [Deadlock989/IndustrialRevolution#51]
In "technologies-recost.lua", there is a `local costs` variable. Would it be possible to include it in "globals.lua" as part of DIR interface?

AAI Industry compatibility makes the technology tree a bit deeper early on and then technologies are a lot more expensive than they should be.  Space Exploration might be able to make use of it, too.

Ideally, I would put this to data-updates.lua to make changes:

```
DIR.technology_costs = {1, 2, 3, 4, 5} -- My custom cost progression
```

Or do you think it could be done in a better way, if I want to consider AAII technologies as `IR_native`?

**Comment by Deadlock989** [comment]
That sounds reasonable. I will take a look later in the week.

**Comment by Deadlock989** [comment]
OK, for the next version I exposed the `DIR.technology_costs` list as suggested and also a further value `DIR.technology_costs_beyond_max_depth` (1000 by default). If a tech is found with depth value that goes beyond the last item in the costs list, it will take that last value and then add the "beyond" value for every additional level. This produces exactly the same scheme for IR2 as it is but allows you to set a costs scheme for any arbitrary depth and then specify what the increment is beyond that list.

Does that work?

**Comment by Genhis** [comment]
That is perfect, thank you!
