### ISSUE TITLE
Module slot alt-mode graphic badly positioned on Electric mining drill

### ISSUE THREAD

**Issue by Bilka2** [Deadlock989/IndustrialRevolution#6]
The module slot alt-mode graphic covers the indicator lamps on the drill. I had this written down to change in a third party mod by shifting the graphic downwards. (IR Version 2.1.0, Factorio 1.1.21)

![image](https://i.imgur.com/Pp3H7yW.png)

**Comment by Deadlock989** [comment]
Thanks, shifted down to between the feet, ditto for the chrome plated drill.
