### ISSUE TITLE
Upgrade steam inserters with upgrade tool

### ISSUE THREAD

**Issue by DurinMusicspear** [Deadlock989/IndustrialRevolution#62]
The upgrade tool only allows upgrade from steam inserter to long hand steam inserter and no other inserters. I would like to have an option to upgrade them to electric steam inserter. Is there a reason that is not possible/implemented?

**Comment by Deadlock989** [comment]
Duplicate of #13

**Comment by DurinMusicspear** [comment]
Right, did not see that one, thanks!
