### ISSUE TITLE
Spidertron not loading fuel into reactor

### ISSUE THREAD

**Issue by JuicyJuuce** [Deadlock989/IndustrialRevolution#68]
I have spidertrons with miniature fission reactors that I manually put a few uranium fuel cells into. Once those fuel cells run out though, the spidertron doesn't load the uranium fuel cells in its trunk into the reactor.

I've attached a save. There are three spidertrons exiting my base to the north that are chained together. You can see one lagging behind because its exoskeletons are no longer powered due to this bug.
[IR2 18.zip](https://github.com/Deadlock989/IndustrialRevolution/files/6683431/IR2.18.zip)

**Comment by Deadlock989** [comment]
This isn't a bug. Vehicles don't load their equipment grids with fuel at all in vanilla. 

They only load generators with fuel in IR2 if (a) you are driving the vehicle and (b) you have the generator manager turned on. In your save, you're not driving the spider and the manager is not toggled on. 

Also, in 2.1.7 (the current version) the generator manager doesn't access vehicle trunks. In 2.2.0 (the next release) it will access trunks but still, only when you are driving the vehicle.

**Comment by JuicyJuuce** [comment]
Sure, I understand why they don't do it in vanilla because portable reactors in vanilla don't need fuel and neither do spidertrons. One of the main features of spidertron is the ability to control it remotely. You can do this in vanilla to great effect but the fact that
a) portable reactors need fuel in IR2 and
b) the generator manager doesn't top it up unless there is a driver
means that long term remote usage of spidertrons is a gameplay feature in vanilla that is effectively removed in IR2.

All that to say, if it is not difficult to code, it seems that avoiding the removal of a vanilla ability is a compelling enough reason to enable topping up without a driver.

**Comment by Deadlock989** [comment]
It's not a bug and this is a bug report tracker.

Spidertrons did not exist when IR2 changed the reactor and added the fuel manager.

You're asking for a new feature. It would have to be scripted, which could affect UPS. Then some other mod will come along and break the script (see transmats).

End of the day, I just don't care about spidertrons.
