### ISSUE TITLE
Electric assembler is missing a shadow casted by robotic arms

### ISSUE THREAD

**Issue by Genhis** [Deadlock989/IndustrialRevolution#69]
Electric assembler (assembling-machine-2) is missing a shadow casted by its robotic arms. Steam and laser assemblers have their own shadows.

It's just a very minor issue not important for gameplay but I thought you may want to know about it.

![image](https://user-images.githubusercontent.com/11155942/122971092-f12ce480-d38e-11eb-836a-f13b57d1e529.png)

**Comment by Deadlock989** [comment]
That's weird because I definitely rendered it but looking back it's been missing since before 1.0.12.

It will have to be re-rendered, I don't know what happened to the sheet.
