### ISSUE TITLE
Crash when player joins multiplayer server

### ISSUE THREAD

**Issue by fd347657835178** [Deadlock989/IndustrialRevolution#70]
IR2 Version: 2.2.0
Factorio Version: 1.1.35
Other Mods: "Big_Brother", "deadlock-beltboxes-loaders", "DeadlockLargerLamp", "factorio-reach", "flib", "FNEI", "helmod", "IndustrialRevolution", "IndustrialRevolutionStacking", "informatron", "LogisticTrainNetwork", "SpidertronWaypoints", "textplates" (latest version of all)

I have been running an IR2 server and after the 2.2.0 upgrade, the server started crashing on new players joining, with the following error message:
```

 590.627 Error MainLoop.cpp:1285: Exception at tick 34122096: The mod Industrial Revolution 2 (2.2.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event IndustrialRevolution::on_player_created (ID 25)
__IndustrialRevolution__/code/control/control-events.lua:45: bad argument #2 of 2 to 'table_size' (table expected, got nil)
stack traceback:
        [C]: in function 'table_size'
        __IndustrialRevolution__/code/control/control-events.lua:45: in function <__IndustrialRevolution__/code/control/control-events.lua:5>
 590.627 Error ServerMultiplayerManager.cpp:91: MultiplayerManager failed: "The mod Industrial Revolution 2 (2.2.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event IndustrialRevolution::on_player_created (ID 25)
__IndustrialRevolution__/code/control/control-events.lua:45: bad argument #2 of 2 to 'table_size' (table expected, got nil)
stack traceback:
        [C]: in function 'table_size'
        __IndustrialRevolution__/code/control/control-events.lua:45: in function <__IndustrialRevolution__/code/control/control-events.lua:5>"

```

**Comment by Deadlock989** [comment]
Thanks for reporting. It is a MP situation I hadn't taken account of. New MP games started in 2.2.0 should work fine but games continued from 2.1.7 will break in this way when new players join. It is an easy fix but I will not get around to it until next weekend.

**Comment by Deadlock989** [comment]
As a temporary fix, try running the following command as admin before any other players join:

`/c remote.call("ir2-world", "set-crate-items", {} )`

**Comment by fd347657835178** [comment]
I can confirm that this command allowed new players to join, thank you.

**Comment by Deadlock989** [comment]
This has been fixed for the next version, I will close this issue when it has been uploaded (most likely Friday 2 July). In the meantime the command above can help migrate a pre-2.2.0 multiplayer save.
