### ISSUE TITLE
Steam Mining Drill

### ISSUE THREAD

**Issue by Scorpion80MS** [Deadlock989/IndustrialRevolution#73]
First off, love the MOD, thank you for all that you do with this.

I love the addition of the Steam Mining Drill however when the drill is picked up either by player or with bot, it turns into a Burner Mining Drill at deconstruction. Hope this is a simple fix and can't wait more more updates. Have a great day.

**Comment by Scorpion80MS** [comment]
Oh, forgot to add, Factorio version 1.1.36 with no other MODS loaded, it happened on my current save that had other MODS, but removed other MODS to test, still happened, I have not tried with a new save but can do that if you want. Just let me know.

**Comment by Deadlock989** [comment]
Ugh, rookie mistake. Will fix.

**Comment by Scorpion80MS** [comment]
Thank you for replying so soon. I can't wait for the fix as I had plans to play Industrial Rev all weekend, hope this doesn't take you took long, don't need to take time away from what you planned to do, just excited to try them out. I might even start a new map as I can already picture new layouts for early game.

**Comment by Deadlock989** [comment]
You can patch this quickly for yourself while you wait by editing code/entities/entities-drills.lua and inserting the following line after line 150:

```
drill.minable.result = "steam-drill"`
```

Straight after the following:

```
local drill = table.deepcopy(drill)
drill.name = "steam-drill"
```

**Comment by Scorpion80MS** [comment]
That did it, thank you so much. Keep up the great work. I need to get back to MOD making, used to for Farming Sim, so I know my way around LUA files and such, but I am sure I would need a refresher course LOL.
