### ISSUE TITLE
Ore washing - only gold

### ISSUE THREAD

**Issue by jonathanjones2** [Deadlock989/IndustrialRevolution#8]
I'm playing IR2 with K2.. I'm at the stage were I'm starting to use ore washing to get Tellurium and running into problems. Mixing acid and crushed rare metals in the ore washer always gives gold. There's no option to select a recipe. Am I missing something?

Love the IR2 look and feel, the graphics are beautiful.

**Comment by Deadlock989** [comment]
The compatibility patch for IR2-K2 is part of K2 - you'll have to report this to them, sorry.

Thanks for the compliment.
