### ISSUE TITLE
Burner generator equipment does not accept fuel

### ISSUE THREAD

**Issue by hunstree** [Deadlock989/IndustrialRevolution#86]
I have a burner generator equipment in my heavy armor, and it signals "empty fuel", but I cannot put any kind of fuel (coal, wood) into it. It stopped working about a week ago, after an update, unfortunately I have no idea from which version.
Mods:
base v1.1.48 build 59155 win64
Enable Research Queue 1.0.4
Factorio Library 0.9.2
IR2 2.3.2
InformaTron 0.2.2.
Jetpack 0.2.13
SneakThrough 1.8.2

**Comment by Deadlock989** [comment]
I can't replicate this with IR2 alone in Factorio 1.1.48 so either it is "user error" or some other mod is interfering.

**Comment by hunstree** [comment]
Thanks for the quick reply. I am going to remove some mods to figure it out.
User error: open armor grid and drag&drop fuel from inventory into the burner, right?

**Comment by hunstree** [comment]
It was user error. :)
